<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Pocket Money – My-Peasant-Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">My-Peasant-Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Pocket Money</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggformula)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: scales

Attaching package: 'scales'

The following object is masked from 'package:purrr':

    discard

The following object is masked from 'package:readr':

    col_factor

Loading required package: ggridges

New to ggformula?  Try the tutorials: 
    learnr::run_tutorial("introduction", package = "ggformula")
    learnr::run_tutorial("refining", package = "ggformula")</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(crosstable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'crosstable'

The following object is masked from 'package:purrr':

    compact</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'mosaic':
  method                           from   
  fortify.SpatialPolygonsDataFrame ggplot2

The 'mosaic' package masks several functions from core packages in order to add 
additional features.  The original behavior of these functions should not be affected by this.

Attaching package: 'mosaic'

The following object is masked from 'package:Matrix':

    mean

The following object is masked from 'package:scales':

    rescale

The following objects are masked from 'package:dplyr':

    count, do, tally

The following object is masked from 'package:purrr':

    cross

The following object is masked from 'package:ggplot2':

    stat

The following objects are masked from 'package:stats':

    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,
    quantile, sd, t.test, var

The following objects are masked from 'package:base':

    max, mean, min, prod, range, sample, sum</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>pmoney <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../../data/PocketMoney.csv"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>pmoney</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Sr.no         Name Gender Money_spent
1      1        Aagam   Male         150
2      2       Aakash   Male         240
3      3      Aarushi Female         382
4      4      Abheeta Female          60
5      5      Adithya   Male          68
6      6       Aditya   Male         300
7      7     Akanksha Female         270
8      8       Amruta Female         190
9      9       Anaaya Female         300
10    10        Anish   Male           0
11    11       Ankush   Male         250
12    12      Anousha Female          85
13    13     Anoushka Female         700
14    14      Anushka Female         140
15    15        Arjun   Male        1143
16    16         Arya   Male         100
17    17        Aryan   Male       10000
18    18         Asra Female        1070
19    19         Aziz   Male        1433
20    20      Bhumika Female        1200
21    21        Daana Female          66
22    22          Dan   Male         600
23    23    Deborishi   Male         205
24    24     Devanshi Female         700
25    25       Dhiman   Male         910
26    26        Dhruv   Male         900
27    27        Dhurv   Male         185
28    28        Eisha Female         300
29    29      Ezhilan   Male         842
30    30         Geet   Male          50
31    31       Harjot Female        3000
32    32      Janhavi Female         150
33    33         Jeff   Male         200
34    34      Jeffrey   Male         150
35    35      Kalyani Female           0
36    36       Kartik   Male         145
37    37       Kashvi Female         430
38    38       Kavana Female         500
39    39       Khushi Female         785
40    40      Koustav   Male         250
41    41        Krish   Male          70
42    42     Kshirija Female         100
43    43       Lekith   Male         100
44    44       Maahin   Male         310
45    45       Maanya Female          15
46    46       Madhav   Male        4000
47    47        Manav   Male          40
48    48      Nandana Female           0
49    49        Navya Female          55
50    50    Nayantara Female         192
51    51        Neeti Female         280
52    52       Nithya Female          85
53    53       Nivaan   Male         220
54    54       Parisa Female          80
55    55        Rikit   Male         259
56    56        Risha Female           0
57    57        Ritik   Male        1000
58    58       Rudraj   Male         478
59    59      Rukaiya Female          20
60    60         Ryan   Male         330
61    61       Shaivi Female         318
62    62     Shashank   Male         400
63    63     Shashwat   Male         149
64    64        Shiva   Male         250
65    65       Shreya Female         585
66    66       Simran Female         340
67    67 Simran Anand Female         660
68    68      Snigdha Female         100
69    69       Suhaas   Male         997
70    70      Suprita Female         500
71    71        Sutej   Male           0
72    72       Tanmay Female         800
73    73        Tanya Female           0
74    74        Taran   Male        1399
75    75       Tarini Female         200
76    76     Tathastu   Male        1535
77    77        Vanya Female         350
78    78        Varad   Male         154
79    79     Vasantha Female         418
80    80   Vasundhara Female       13000
81    81         Veer   Male         566
82    82        Viraj   Male         315</code></pre>
</div>
</div>
<p>This dataset consists of 1 quant and 3 qual variables</p>
<section id="data-dictionary" class="level3">
<h3 class="anchored" data-anchor-id="data-dictionary">Data Dictionary</h3>
<ul>
<li><p>S.No - Qualitative</p></li>
<li><p>Name - Qualitative</p></li>
<li><p>Gender - Qualitative</p></li>
<li><p>Money_Spent - Quantitative</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>pmoney_modified <span class="ot">&lt;-</span>pmoney <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Gender =</span> <span class="fu">as_factor</span>(Gender)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>pmoney_modified</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Sr.no         Name Gender Money_spent
1      1        Aagam   Male         150
2      2       Aakash   Male         240
3      3      Aarushi Female         382
4      4      Abheeta Female          60
5      5      Adithya   Male          68
6      6       Aditya   Male         300
7      7     Akanksha Female         270
8      8       Amruta Female         190
9      9       Anaaya Female         300
10    10        Anish   Male           0
11    11       Ankush   Male         250
12    12      Anousha Female          85
13    13     Anoushka Female         700
14    14      Anushka Female         140
15    15        Arjun   Male        1143
16    16         Arya   Male         100
17    17        Aryan   Male       10000
18    18         Asra Female        1070
19    19         Aziz   Male        1433
20    20      Bhumika Female        1200
21    21        Daana Female          66
22    22          Dan   Male         600
23    23    Deborishi   Male         205
24    24     Devanshi Female         700
25    25       Dhiman   Male         910
26    26        Dhruv   Male         900
27    27        Dhurv   Male         185
28    28        Eisha Female         300
29    29      Ezhilan   Male         842
30    30         Geet   Male          50
31    31       Harjot Female        3000
32    32      Janhavi Female         150
33    33         Jeff   Male         200
34    34      Jeffrey   Male         150
35    35      Kalyani Female           0
36    36       Kartik   Male         145
37    37       Kashvi Female         430
38    38       Kavana Female         500
39    39       Khushi Female         785
40    40      Koustav   Male         250
41    41        Krish   Male          70
42    42     Kshirija Female         100
43    43       Lekith   Male         100
44    44       Maahin   Male         310
45    45       Maanya Female          15
46    46       Madhav   Male        4000
47    47        Manav   Male          40
48    48      Nandana Female           0
49    49        Navya Female          55
50    50    Nayantara Female         192
51    51        Neeti Female         280
52    52       Nithya Female          85
53    53       Nivaan   Male         220
54    54       Parisa Female          80
55    55        Rikit   Male         259
56    56        Risha Female           0
57    57        Ritik   Male        1000
58    58       Rudraj   Male         478
59    59      Rukaiya Female          20
60    60         Ryan   Male         330
61    61       Shaivi Female         318
62    62     Shashank   Male         400
63    63     Shashwat   Male         149
64    64        Shiva   Male         250
65    65       Shreya Female         585
66    66       Simran Female         340
67    67 Simran Anand Female         660
68    68      Snigdha Female         100
69    69       Suhaas   Male         997
70    70      Suprita Female         500
71    71        Sutej   Male           0
72    72       Tanmay Female         800
73    73        Tanya Female           0
74    74        Taran   Male        1399
75    75       Tarini Female         200
76    76     Tathastu   Male        1535
77    77        Vanya Female         350
78    78        Varad   Male         154
79    79     Vasantha Female         418
80    80   Vasundhara Female       13000
81    81         Veer   Male         566
82    82        Viraj   Male         315</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>pmoney_modified <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_density</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="sc">~</span> Money_spent,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="sc">~</span> Gender,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Money spent"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Male vs Female"</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>pmoney_modified <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_boxplot</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    Money_spent <span class="sc">~</span> Gender,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="sc">~</span> Gender,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Math Anxiety Score Box Plots"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Boys vs Girls"</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">##</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>pmoney_modified <span class="sc">%&gt;%</span> <span class="fu">count</span>(Gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Gender  n
1   Male 41
2 Female 41</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>pmoney_modified <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Gender) <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(Money_spent))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  Gender  mean
  &lt;fct&gt;  &lt;dbl&gt;
1 Male    749.
2 Female  693.</code></pre>
</div>
</div>
</section>
<section id="inference" class="level3">
<h3 class="anchored" data-anchor-id="inference">Inference</h3>
<ul>
<li><p>Majority of people, men and female included spend around 0 to a few hundreds per day</p></li>
<li><p>Men seem to spend a little more than women not including outliers</p></li>
<li><p>There is a pretty big overlap in general in the male and female category</p></li>
<li><p>The graph is left-skewed with one peak</p></li>
<li><p>In boxplot, median value is similar in both categories</p></li>
<li><p>There is more variance in the male category above the median</p></li>
<li><p>There are few outliers in both categories</p></li>
<li><p>Mean money spent of male (748.6) is larger than female (693.3)which means on average, males spend more</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_histogram</span>(<span class="sc">~</span>Money_spent,<span class="at">fill=</span><span class="sc">~</span>    </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>Gender,<span class="at">data=</span>pmoney_modified,<span class="at">bins =</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="inference-1" class="level3">
<h3 class="anchored" data-anchor-id="inference-1">Inference</h3>
<ul>
<li><p>most people spend from around 0 to a few hundreds</p></li>
<li><p>most people spend under 2000 per day expect a few outliers</p></li>
<li><p>males on average spend slightly more than females</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>pmoney_modified <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_density</span>( <span class="sc">~</span> Money_spent,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="sc">~</span> Gender,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.5</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">title =</span> <span class="st">"Money spent for males and females"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_facet_grid</span>(<span class="sc">~</span> Gender) <span class="sc">%&gt;%</span> </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_fitdistr</span>(<span class="at">dist =</span> <span class="st">"dnorm"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">##</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>pmoney_modified <span class="sc">%&gt;%</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_qqline</span>(<span class="sc">~</span> Money_spent, <span class="at">color =</span> <span class="sc">~</span> Gender,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">title =</span> <span class="st">"Money Spent..is it Normally Distributed?"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_qq</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_facet_wrap</span>(<span class="sc">~</span> Gender)  <span class="co"># independent y-axis</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="do">##</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>male_moneyspent <span class="ot">&lt;-</span> pmoney_modified <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Gender<span class="sc">==</span> <span class="st">"Male"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Money_spent)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="do">##</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>female_moneyspent <span class="ot">&lt;-</span> pmoney_modified <span class="sc">%&gt;%</span> </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Gender<span class="sc">==</span> <span class="st">"Female"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Money_spent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="inference-2" class="level3">
<h3 class="anchored" data-anchor-id="inference-2">Inference</h3>
<ul>
<li><p>both of the graphs are left skewed for both male and female</p></li>
<li><p>the density curve of both graphs do not align with the normal fit curve which suggests the distribution may not be normal</p></li>
<li><p>In the qq plot, the dots are close to the normal but do not align perfectly to it, there are also outliers in both categories</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(male_moneyspent<span class="sc">$</span>Money_spent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  male_moneyspent$Money_spent
W = 0.40726, p-value = 1.136e-11</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(female_moneyspent<span class="sc">$</span>Money_spent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  female_moneyspent$Money_spent
W = 0.29606, p-value = 8.961e-13</code></pre>
</div>
</div>
</section>
<section id="inference-3" class="level3">
<h3 class="anchored" data-anchor-id="inference-3">Inference</h3>
<ul>
<li>Since the p-value is less than 0.05 in both categories, it indicates that the data significantly deviates from a normal distribution. This means that the money spent by males and that spent by females are both not normally distributed</li>
</ul>
</section>
<section id="variance-test" class="level2">
<h2 class="anchored" data-anchor-id="variance-test">Variance Test</h2>
<p>var.test() is designed to perform an F-test to compare the variances of two groups</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(Money_spent <span class="sc">~</span> Gender, <span class="at">data =</span> pmoney_modified, </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Multiple parameters; naming those columns num.df, den.df</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 9
  estimate num.df den.df statistic p.value conf.low conf.high method alternative
     &lt;dbl&gt;  &lt;int&gt;  &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;      
1    0.646     40     40     0.646   0.172    0.345      1.21 F tes… two.sided  </code></pre>
</div>
</div>
<section id="inference-4" class="level3">
<h3 class="anchored" data-anchor-id="inference-4">Inference</h3>
<ul>
<li>since the p-value is higher than 0.05, there is not significant difference in variance between the two groups</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(<span class="fl">0.646</span>,<span class="dv">40</span>,<span class="dv">40</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.126616</code></pre>
</div>
</div>
<p>This output indicates that about 64.6% of the area under the F-distribution curve with the specified degrees of freedom lies to the left of this value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>mosaic<span class="sc">::</span><span class="fu">t_test</span>(Money_spent <span class="sc">~</span> Gender, <span class="at">data =</span> pmoney_modified) <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 10
  estimate estimate1 estimate2 statistic p.value parameter conf.low conf.high
     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1     55.3      749.      693.     0.136   0.893      76.5    -757.      868.
# ℹ 2 more variables: method &lt;chr&gt;, alternative &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="inference-5" class="level3">
<h3 class="anchored" data-anchor-id="inference-5">Inference</h3>
<ul>
<li><p>Since p value is greater than 0.05, it indicates that there is no significant difference between the groups, which indicates similar money spending behaviour in male and female categories.</p></li>
<li><p>Thus null hypothesis cannot be rejected</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(Money_spent <span class="sc">~</span> Gender, <span class="at">data =</span> pmoney_modified, </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">conf.int =</span> <span class="cn">TRUE</span>, </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">conf.level =</span> <span class="fl">0.95</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot
compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot
compute exact confidence intervals with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  estimate statistic p.value conf.low conf.high method               alternative
     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;                &lt;chr&gt;      
1     55.0      936.   0.381    -70.0      180. Wilcoxon rank sum t… two.sided  </code></pre>
</div>
</div>
<ul>
<li><p>since p-value is greater than 0.05, there is insufficient evidence to suggest a difference in median money spent between male and female groups</p></li>
<li><p>the confidence interval shows the range of possible median differences. Since the confidence interval contains 0 within its bounds, this means there is no significant difference between the groups</p></li>
</ul>
</section>
</section>
<section id="permutation-test" class="level2">
<h2 class="anchored" data-anchor-id="permutation-test">Permutation Test</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>null_dist_moneyspent <span class="ot">&lt;-</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">do</span>(<span class="dv">4999</span>) <span class="sc">*</span> <span class="fu">diffmean</span>(<span class="at">data =</span> pmoney_modified, Money_spent <span class="sc">~</span> <span class="fu">shuffle</span>(Gender))</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>null_dist_moneyspent</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         diffmean
1      37.3902439
2     -59.3414634
3     196.9024390
4     -93.8780488
5     541.9756098
6     365.2439024
7      16.0243902
8    -569.8780488
9     -57.3902439
10   -126.9024390
11    606.2195122
12    363.6341463
13   -650.3170732
14    495.1951220
15   -173.5365854
16    417.2926829
17   -663.3902439
18      0.4634146
19   -607.4390244
20    154.4634146
21    302.1219512
22   -401.0000000
23   -696.0243902
24    104.8048780
25   -252.8536585
26     29.3414634
27   -118.7560976
28     71.3902439
29    234.0731707
30   -382.0731707
31    482.3170732
32   -735.3414634
33    510.9512195
34    -83.3414634
35   -457.0975610
36     66.3658537
37     73.0975610
38    230.5609756
39    -18.8048780
40     46.3170732
41    286.3170732
42    576.0731707
43    372.4146341
44   -253.2439024
45   -112.1219512
46   -533.2926829
47     24.6585366
48    746.9024390
49   -107.9756098
50    142.1219512
51    -71.2439024
52    -58.5121951
53    763.5853659
54     -2.9024390
55   -136.3170732
56    272.9024390
57   -175.2439024
58   -568.3658537
59   -580.8536585
60   -149.9756098
61    192.0731707
62    593.2439024
63   -251.8780488
64   -351.4390244
65    800.4634146
66   -420.2195122
67    -57.9268293
68   -479.4878049
69    104.4634146
70     66.3170732
71   -483.4390244
72    716.0243902
73    233.5365854
74    639.5365854
75    -55.3414634
76    533.7804878
77   -658.0243902
78   -724.1219512
79   -497.3414634
80    200.1219512
81    351.2926829
82   -103.5365854
83   -605.2439024
84   -290.1707317
85     35.2439024
86   -249.0000000
87    629.1463415
88     25.5853659
89    521.0975610
90   -273.0000000
91    703.1951220
92   -337.6829268
93    596.7560976
94    869.0975610
95   -641.0487805
96    -84.1219512
97    266.3658537
98    114.7560976
99   -368.7560976
100  -149.9756098
101  -593.3902439
102  -194.7560976
103  -447.9268293
104   513.3902439
105   460.9512195
106  -354.9512195
107  -457.4390244
108  -483.1951220
109   253.6829268
110  -205.0487805
111   158.8048780
112   -54.0731707
113   -25.2439024
114   637.5365854
115  -538.4146341
116    53.5365854
117  -564.4634146
118   -46.6097561
119  -566.3170732
120  -464.9024390
121   666.9024390
122  -504.7560976
123  -130.6585366
124  -507.7804878
125   279.9756098
126   -15.9756098
127  -673.5365854
128   -26.1219512
129    16.7073171
130  -699.8292683
131   133.1951220
132  -789.5853659
133  -114.8536585
134   285.2439024
135    92.4634146
136  -426.1707317
137   275.6829268
138  -436.8536585
139    39.5365854
140    67.7317073
141   133.4878049
142  -127.0975610
143    64.6585366
144  -446.1219512
145   -53.7317073
146  -229.0975610
147    44.4634146
148   718.0731707
149    -5.0975610
150    48.5609756
151  -713.0487805
152  -409.4390244
153   671.0975610
154   612.8536585
155  -843.9756098
156   -41.7804878
157  -283.1951220
158    22.7073171
159   -60.9512195
160   628.2195122
161   -30.4634146
162  -385.7317073
163   -44.7073171
164   547.4878049
165   139.3414634
166   -67.0975610
167  -591.8292683
168   186.5121951
169   175.0487805
170    38.8048780
171  -181.9756098
172  -721.2926829
173   -44.8048780
174   521.6829268
175  -441.0487805
176   183.7317073
177   -81.2926829
178  -519.1463415
179    90.3658537
180   440.8536585
181  -165.7317073
182   220.9512195
183  -612.9512195
184  -161.4878049
185  -484.7560976
186  -605.5365854
187  -370.7073171
188   395.0975610
189  -395.8292683
190  -246.6097561
191   608.2195122
192    15.8292683
193   -49.9756098
194  -712.0731707
195  -391.5365854
196   744.4146341
197   -70.2195122
198  -813.2439024
199   362.0731707
200  -626.1707317
201  -571.2439024
202  -567.3414634
203  -774.0243902
204  -596.9512195
205   526.1707317
206   639.8292683
207   384.2195122
208  -160.1219512
209   702.7073171
210   -57.1463415
211    95.6341463
212  -475.1951220
213  -513.1951220
214    80.8536585
215  -519.9268293
216   429.9268293
217  -587.8292683
218  -537.2439024
219  -155.2926829
220  -471.7317073
221     1.8780488
222   887.7804878
223  -651.9268293
224  -227.0975610
225   549.1463415
226  -391.9756098
227    38.7560976
228  -326.3658537
229    80.6585366
230    27.0000000
231   -47.0487805
232   553.8292683
233   632.2682927
234   581.5853659
235  -588.7073171
236    57.8780488
237    91.7317073
238   130.4634146
239    20.8048780
240    88.7073171
241  -409.0000000
242  -306.7560976
243  -622.6097561
244   540.9512195
245   148.1219512
246  -604.6585366
247    76.5609756
248    61.4390244
249   394.2682927
250   568.7073171
251   -81.5365854
252   725.3902439
253  -376.6585366
254    93.9756098
255   -13.3902439
256   581.4878049
257   554.4634146
258   570.3170732
259  -287.2926829
260    42.0731707
261   696.5609756
262   726.7560976
263  -314.3170732
264  -638.0243902
265   146.0243902
266   -18.2195122
267  -141.8780488
268   720.9512195
269  -110.7073171
270    -8.1219512
271  -500.9024390
272   -59.8292683
273   -57.0975610
274   108.5609756
275   -76.5609756
276   341.8780488
277  -459.9756098
278  -582.3658537
279  -769.2926829
280   444.3170732
281  -653.2926829
282  -132.8536585
283  -491.0487805
284   -40.0731707
285    31.0487805
286   166.7560976
287  -645.5853659
288   702.1219512
289  -367.3414634
290   325.0000000
291   274.5609756
292    52.4634146
293   169.0000000
294  -466.2195122
295   542.0243902
296   227.4390244
297  -580.1219512
298  -554.9512195
299   459.0975610
300   351.2926829
301  -305.1463415
302  -130.7560976
303  -643.8780488
304  -198.9024390
305  -335.2439024
306   540.6097561
307   532.3658537
308   495.4390244
309  -589.7317073
310  -195.8292683
311   183.9268293
312   158.4146341
313  -278.9024390
314   364.8536585
315  -242.2195122
316   626.6097561
317   387.5365854
318     5.6829268
319   660.9512195
320  -390.2195122
321  -711.6341463
322   533.6829268
323    76.7560976
324   590.7073171
325   154.7073171
326   453.6829268
327   -26.9024390
328   676.7560976
329  -631.3902439
330  -409.3414634
331   -47.8780488
332   207.0487805
333   510.9024390
334  -580.4146341
335  -241.0487805
336   164.9024390
337   198.7560976
338    24.8536585
339    48.8048780
340  -157.3414634
341    91.3414634
342   -29.2926829
343  -141.1463415
344  -180.5121951
345   353.3902439
346  -257.7317073
347   -82.9024390
348  -694.3658537
349   731.0975610
350    70.5121951
351   161.1951220
352  -754.8048780
353  -289.6829268
354  -267.4878049
355   620.5609756
356  -229.3902439
357   423.1951220
358  -133.7804878
359  -115.9268293
360  -354.6585366
361   663.8292683
362  -508.9512195
363    34.4634146
364  -461.9268293
365   276.6097561
366  -587.0000000
367    -5.2926829
368  -577.3414634
369  -608.4146341
370   327.0000000
371   105.6341463
372  -438.6585366
373  -224.1707317
374    68.1707317
375  -520.0243902
376  -141.2926829
377  -780.7560976
378   -58.1219512
379  -513.1951220
380  -300.0243902
381   473.4390244
382  -209.7804878
383   266.9512195
384  -460.2195122
385  -577.2926829
386  -112.7073171
387  -469.6341463
388   183.6829268
389   765.2439024
390  -178.6097561
391    -6.9512195
392    86.9024390
393   601.7317073
394   120.1219512
395   107.8780488
396   -49.0975610
397   399.2439024
398   118.9024390
399   639.2926829
400  -714.6097561
401  -518.4146341
402   365.0975610
403  -550.3170732
404  -413.3902439
405  -206.7560976
406  -499.2926829
407   -31.8780488
408  -138.0243902
409   121.1463415
410    39.8292683
411    62.0731707
412  -136.3170732
413  -553.7317073
414   191.5853659
415  -453.3414634
416  -683.4878049
417  -794.1219512
418   749.4390244
419   -55.7804878
420   -60.4146341
421   272.1219512
422   -12.2682927
423    53.0975610
424  -261.7317073
425   223.7804878
426  -223.1951220
427   621.1951220
428   672.7560976
429   -55.0000000
430  -438.4634146
431  -589.0487805
432   511.0487805
433  -181.6341463
434   -89.7804878
435    46.3170732
436  -582.8048780
437    85.0975610
438  -246.8536585
439    57.7317073
440  -529.8292683
441   638.7073171
442   734.9024390
443  -119.0487805
444   721.7317073
445   133.3414634
446   -92.2682927
447    37.5365854
448    -0.6585366
449  -289.5853659
450   -94.1707317
451  -703.1951220
452    89.2439024
453   185.0000000
454  -454.9512195
455    16.2195122
456  -550.7073171
457  -275.0975610
458  -799.4878049
459  -414.9024390
460  -625.6829268
461   157.8292683
462   549.4390244
463   115.7804878
464  -572.8536585
465   590.9512195
466    75.0000000
467   827.3902439
468   213.4878049
469  -577.1951220
470  -442.7560976
471    68.9512195
472   -18.6097561
473  -211.1951220
474  -118.7073171
475  -208.4634146
476  -497.0487805
477    28.4146341
478   431.0975610
479   173.7317073
480  -337.1951220
481    -0.8536585
482  -513.3902439
483   625.0487805
484   416.8048780
485  -113.8292683
486   716.8048780
487  -750.6097561
488   173.0000000
489   -34.8048780
490   487.4878049
491   178.8536585
492   -48.1707317
493   672.7073171
494  -531.7317073
495    -8.9024390
496    37.7804878
497   684.5121951
498  -498.8048780
499  -473.8780488
500   -35.8292683
501  -279.9268293
502    79.4878049
503  -320.9024390
504  -136.3170732
505  -492.4634146
506  -362.0243902
507   -24.7073171
508  -116.4146341
509  -658.6097561
510  -423.7317073
511  -199.6341463
512   601.8292683
513   352.1219512
514   553.1951220
515   718.0731707
516  -431.6829268
517    51.8292683
518     7.6829268
519  -443.8780488
520  -557.7317073
521   -18.4634146
522    84.1707317
523    40.7073171
524   668.4634146
525    81.4390244
526   171.8292683
527  -161.4390244
528   -87.8780488
529  -267.1463415
530   -55.2439024
531    19.7804878
532  -322.0243902
533  -143.2439024
534    37.2926829
535   297.0000000
536  -125.2439024
537  -624.5609756
538   -87.8292683
539   627.3902439
540   499.9268293
541   -52.6585366
542  -657.5853659
543    11.2926829
544   542.1219512
545    94.3170732
546   -38.4634146
547  -247.8292683
548   -23.3902439
549  -256.0731707
550   -85.1463415
551   599.3414634
552   106.8048780
553   610.6585366
554    28.3170732
555   687.6341463
556   -72.9024390
557    52.7073171
558   413.4390244
559    26.4146341
560   538.6097561
561  -741.1463415
562    59.6341463
563   549.8780488
564   128.6585366
565  -159.3902439
566   326.8048780
567   322.0243902
568   -95.0000000
569  -417.6829268
570   517.9756098
571  -768.4634146
572   407.5365854
573   -11.0975610
574   542.7560976
575   105.7804878
576   159.0487805
577  -498.0243902
578     4.5121951
579  -113.9268293
580   108.1219512
581  -390.0731707
582  -238.8048780
583  -572.6097561
584  -161.3902439
585   206.2682927
586  -249.3902439
587  -480.4634146
588   173.8780488
589   800.0243902
590   111.2926829
591   -15.5365854
592   108.6585366
593   304.7560976
594   491.3902439
595  -730.5121951
596    33.8292683
597   706.0243902
598  -469.9268293
599    45.2926829
600   205.6829268
601   176.9024390
602    40.0243902
603   -56.6097561
604   -22.7560976
605  -666.2195122
606  -698.8536585
607  -118.8536585
608  -184.4634146
609  -535.7317073
610   142.8536585
611  -103.9268293
612   -87.0000000
613  -645.6341463
614  -431.4878049
615  -904.9512195
616  -503.1951220
617  -255.4878049
618   477.6829268
619  -277.0000000
620   224.1219512
621  -495.0000000
622    80.0731707
623    36.4634146
624  -266.9024390
625   349.6341463
626    62.4634146
627    69.7317073
628  -652.0731707
629   367.0975610
630   244.7073171
631  -356.2195122
632  -517.4878049
633   592.1219512
634  -165.6829268
635   404.2195122
636   717.9756098
637   683.8292683
638   717.0487805
639  -565.2439024
640   315.3414634
641  -365.0487805
642   120.9512195
643   118.7560976
644  -577.6341463
645    12.2195122
646   188.1707317
647  -538.5121951
648   304.2682927
649   191.3902439
650    66.0731707
651   578.2682927
652  -743.3902439
653  -711.6341463
654  -713.1951220
655   539.9756098
656  -129.3902439
657  -137.4390244
658   715.7804878
659    11.3902439
660  -502.5121951
661   267.0000000
662  -321.3902439
663   654.5609756
664    99.2439024
665   570.6097561
666   594.3658537
667   659.0000000
668    37.8292683
669  -541.6829268
670   -42.0243902
671  -633.1951220
672    -5.6341463
673   171.0000000
674   491.8292683
675   -67.7804878
676   561.5853659
677  -556.9024390
678  -749.3414634
679  -456.9512195
680    99.0487805
681   824.9512195
682   461.9268293
683   419.4390244
684  -505.6341463
685  -248.1219512
686     3.3902439
687  -292.8536585
688    84.5609756
689    17.8292683
690   -88.5609756
691  -482.5609756
692  -320.0731707
693  -592.8536585
694  -252.0731707
695   443.6341463
696    30.9024390
697  -285.0487805
698   154.4634146
699  -115.1463415
700  -496.6585366
701   740.5121951
702  -772.4146341
703   227.6341463
704  -116.8536585
705   677.7317073
706   -83.2926829
707   119.7317073
708  -573.7317073
709   535.0487805
710   375.2926829
711  -461.0487805
712  -438.1219512
713    67.0975610
714    84.4634146
715  -623.3902439
716  -252.0243902
717  -328.9512195
718   525.4878049
719  -755.3902439
720   -21.3902439
721   599.7317073
722    59.7317073
723  -596.6097561
724   496.7073171
725  -286.1707317
726   637.6341463
727   234.8536585
728  -589.7804878
729  -608.3170732
730    91.6341463
731  -628.3170732
732  -424.4146341
733   542.0731707
734   -17.8780488
735  -354.0243902
736    51.5365854
737   122.2682927
738   260.9024390
739  -534.6585366
740   624.4146341
741  -724.2682927
742  -704.9512195
743   176.1707317
744  -163.6341463
745    87.3902439
746   690.8536585
747   -35.5853659
748   618.4146341
749  -710.1707317
750  -419.8780488
751  -459.2439024
752   211.0975610
753  -320.0731707
754   -45.5853659
755   271.8780488
756   551.5365854
757    -6.0243902
758   338.4634146
759   442.5121951
760   -17.6341463
761   596.8048780
762   370.8536585
763  -147.7804878
764  -543.3414634
765   179.9268293
766  -607.1951220
767    -3.1463415
768   765.0487805
769  -855.9756098
770    51.9756098
771   638.3658537
772  -501.6341463
773  -148.7560976
774   124.9512195
775   729.5365854
776   434.3170732
777    70.7560976
778   503.2439024
779   445.8780488
780  -560.7560976
781  -293.1463415
782    88.2195122
783  -202.3658537
784   484.3170732
785  -601.5365854
786   240.0243902
787  -571.5853659
788    -7.2439024
789   676.0243902
790  -551.2439024
791  -499.0000000
792  -273.0975610
793   678.5609756
794  -100.0731707
795  -386.8536585
796  -461.4878049
797   -64.7560976
798  -546.7073171
799   732.7560976
800  -425.1951220
801   -90.1219512
802   -62.5609756
803   639.5853659
804    48.9024390
805    21.9268293
806  -516.0731707
807  -806.9512195
808   -11.2439024
809   601.9756098
810  -161.5365854
811   487.5853659
812     0.9024390
813  -229.5853659
814   388.3658537
815   588.5609756
816    51.0975610
817     1.4390244
818   -25.6341463
819   -67.0000000
820  -604.1219512
821   108.5609756
822    -9.3414634
823    18.5609756
824   220.3658537
825   471.7317073
826   120.6585366
827  -600.9512195
828  -434.2682927
829  -422.7560976
830  -165.4878049
831   734.0731707
832  -184.0731707
833   366.5121951
834  -575.8292683
835   210.0731707
836  -528.1219512
837  -227.9756098
838  -380.7560976
839   559.4390244
840   455.2926829
841  -571.4878049
842   154.5609756
843  -597.8780488
844   661.2926829
845  -177.2926829
846  -134.7560976
847    75.0000000
848   -80.5121951
849   194.0243902
850  -180.7073171
851  -149.1951220
852    29.6341463
853  -485.0487805
854   461.2439024
855   -52.3658537
856  -627.5853659
857  -164.3170732
858    86.6097561
859   -58.4146341
860    61.3902439
861   -98.7073171
862   701.0000000
863  -217.3902439
864   679.1463415
865   397.4878049
866   316.4146341
867  -163.9268293
868  -127.6341463
869   -26.4634146
870  -636.3658537
871  -483.2926829
872   114.0243902
873  -524.4146341
874    -2.3658537
875    -4.4634146
876  -523.7804878
877   -90.5609756
878  -578.2682927
879  -555.4878049
880  -331.5365854
881  -325.7804878
882  -663.1951220
883    47.1463415
884  -627.6341463
885  -557.8780488
886   373.6829268
887  -543.9756098
888     5.7317073
889  -360.1707317
890   676.8536585
891  -323.4390244
892  -440.1219512
893  -272.2682927
894   223.4390244
895  -423.0487805
896   725.9756098
897   112.7073171
898   -45.9268293
899  -640.4634146
900  -691.7804878
901   698.6097561
902   -52.8536585
903  -726.6097561
904  -413.1951220
905  -760.9024390
906  -743.1463415
907   257.2926829
908  -123.5365854
909    43.3902439
910   553.6341463
911  -557.4390244
912   517.3414634
913  -187.0487805
914     6.7560976
915   590.4146341
916  -533.4878049
917     4.6097561
918  -123.5853659
919    18.9024390
920  -550.1707317
921  -237.6341463
922   460.5121951
923    53.3902439
924   544.0243902
925  -146.8536585
926    89.5853659
927  -568.5121951
928     5.4390244
929  -402.9512195
930  -230.5609756
931  -599.1463415
932    45.6341463
933   583.1951220
934   450.3170732
935  -362.5121951
936   129.1951220
937   119.9756098
938  -168.2195122
939   501.7804878
940  -290.9512195
941  -751.4878049
942  -673.6341463
943  -136.2195122
944   214.2195122
945   130.9024390
946     0.5609756
947   684.1219512
948  -324.5121951
949   270.2682927
950  -119.2926829
951  -147.9268293
952   649.6341463
953  -188.8536585
954  -422.6097561
955    61.2439024
956  -588.4146341
957   167.9268293
958   -34.5609756
959  -201.6341463
960   -37.1951220
961    88.6097561
962  -187.4390244
963  -129.0487805
964  -230.9512195
965   615.4390244
966   644.5121951
967  -383.6341463
968  -131.6829268
969   372.4634146
970   499.9268293
971  -658.6097561
972   503.6341463
973   -86.0731707
974  -143.1463415
975   762.2195122
976   110.5609756
977  -236.5121951
978  -390.0243902
979   102.7560976
980   -50.2682927
981   269.0000000
982   237.0975610
983  -804.9024390
984   385.9756098
985   171.6829268
986    80.1219512
987   321.5365854
988  -113.0975610
989     8.6585366
990  -662.8048780
991   499.6829268
992   501.0487805
993    56.4634146
994  -139.4390244
995   133.7804878
996  -172.8048780
997   582.7073171
998    21.6829268
999   -27.2439024
1000  114.2682927
1001 -308.7560976
1002 -681.4878049
1003   23.2926829
1004 -709.2439024
1005  508.2682927
1006 -540.9024390
1007  682.8536585
1008  428.3170732
1009 -566.9024390
1010  486.4146341
1011  -40.3658537
1012   71.9268293
1013 -132.0731707
1014   37.0487805
1015  -43.9268293
1016 -297.2439024
1017  201.8780488
1018 -200.7073171
1019  708.1219512
1020 -541.0000000
1021 -731.6829268
1022 -119.0000000
1023 -574.0243902
1024  112.0731707
1025  -40.0243902
1026 -657.8292683
1027 -111.0000000
1028  466.3170732
1029  -14.0243902
1030 -540.3658537
1031   80.9512195
1032  -55.2926829
1033  717.1951220
1034 -410.2682927
1035  133.2439024
1036 -384.9024390
1037  401.3902439
1038 -496.2682927
1039 -371.3414634
1040  -91.0975610
1041 -155.9756098
1042 -543.4878049
1043  576.1707317
1044   88.3170732
1045  440.0731707
1046  210.7073171
1047 -174.7073171
1048  695.3414634
1049 -765.2439024
1050   98.1707317
1051 -170.4146341
1052  391.8780488
1053  525.1951220
1054  198.1707317
1055 -719.1463415
1056 -783.0000000
1057 -557.7317073
1058  132.0731707
1059   87.2439024
1060   -5.0975610
1061  764.7073171
1062  -91.4390244
1063  -77.4390244
1064 -592.6097561
1065 -404.7560976
1066 -487.9756098
1067  746.2195122
1068  414.7073171
1069 -759.0000000
1070  427.2926829
1071  141.5853659
1072 -709.5853659
1073   -5.6341463
1074 -177.2439024
1075  380.7073171
1076  -97.8780488
1077 -528.5121951
1078 -568.2682927
1079 -426.1219512
1080  556.9024390
1081  663.4390244
1082  -75.9268293
1083  -71.8292683
1084 -514.3658537
1085   16.6097561
1086 -551.4390244
1087   95.0975610
1088  164.4634146
1089 -517.7804878
1090  495.5853659
1091  587.3414634
1092  690.5609756
1093   42.5121951
1094  479.7804878
1095  394.3170732
1096  -87.0975610
1097  538.4634146
1098 -543.0000000
1099 -281.9756098
1100   29.0487805
1101  461.0000000
1102  762.4634146
1103   -1.4390244
1104  798.3170732
1105  471.8292683
1106  170.6097561
1107  717.3414634
1108  557.8292683
1109   40.1219512
1110 -589.9268293
1111 -449.7317073
1112  606.4146341
1113  237.3414634
1114  130.9024390
1115  753.0487805
1116  664.9024390
1117 -487.2926829
1118 -498.0731707
1119  118.6097561
1120  -80.0731707
1121   43.9756098
1122  380.9024390
1123   58.8048780
1124  -12.1707317
1125  -70.2682927
1126  126.5121951
1127 -717.4878049
1128  -33.8292683
1129  692.2195122
1130 -309.7317073
1131  114.7560976
1132  597.2926829
1133 -120.4146341
1134 -645.1951220
1135  151.1463415
1136 -583.1951220
1137  -30.2682927
1138 -406.8536585
1139  499.0000000
1140  159.8292683
1141 -181.6829268
1142  405.1463415
1143   46.3170732
1144  132.8536585
1145 -154.6097561
1146  145.1463415
1147    5.2926829
1148 -139.2926829
1149  456.3170732
1150 -673.6829268
1151 -710.1707317
1152 -649.6341463
1153  -18.2195122
1154   35.8780488
1155  131.8780488
1156  129.1951220
1157  595.0000000
1158   64.8536585
1159  432.8536585
1160  810.8048780
1161  686.3170732
1162  907.1463415
1163  696.5121951
1164  -91.0000000
1165  179.4878049
1166   23.8780488
1167 -679.4390244
1168 -638.7073171
1169 -439.3902439
1170  -66.8536585
1171 -301.4390244
1172  -48.9512195
1173   42.8048780
1174 -469.4390244
1175 -671.4878049
1176  -22.8048780
1177 -429.3902439
1178  351.5853659
1179  501.7317073
1180 -193.3902439
1181  703.6829268
1182 -230.2195122
1183 -702.9512195
1184 -483.2926829
1185 -136.5121951
1186  537.4390244
1187 -149.8780488
1188 -378.9024390
1189 -218.7560976
1190  -29.3414634
1191    6.5121951
1192 -481.4390244
1193 -246.9024390
1194  118.3170732
1195 -190.7560976
1196  -24.1219512
1197   85.2439024
1198  638.2195122
1199 -700.0731707
1200 -189.2926829
1201  558.2682927
1202  169.1951220
1203  -17.7804878
1204 -280.3658537
1205  143.9268293
1206  213.5365854
1207 -741.9756098
1208  213.6829268
1209 -487.5853659
1210  511.3414634
1211  241.7317073
1212  636.9024390
1213  410.0731707
1214 -375.2439024
1215 -446.2195122
1216  598.3170732
1217  424.8048780
1218 -450.5121951
1219 -655.4390244
1220  -13.0975610
1221 -593.0975610
1222 -261.5365854
1223 -527.5853659
1224  607.0975610
1225  252.4146341
1226  670.4146341
1227    4.0243902
1228 -626.0731707
1229   97.7804878
1230 -238.5609756
1231 -611.3414634
1232 -345.1463415
1233 -267.1951220
1234   18.8048780
1235 -626.1219512
1236 -325.1951220
1237  227.6829268
1238   17.9268293
1239  -69.7317073
1240 -250.9024390
1241 -128.1707317
1242 -166.0731707
1243  126.8048780
1244  125.1951220
1245 -561.2439024
1246  166.2195122
1247  -88.6097561
1248  309.0487805
1249  -16.5121951
1250 -131.6341463
1251  -16.1219512
1252  641.5365854
1253 -455.3414634
1254  -83.1463415
1255 -551.8292683
1256 -143.6829268
1257 -608.7073171
1258  317.7317073
1259 -445.8292683
1260  152.5609756
1261 -163.1951220
1262 -619.2439024
1263 -439.3414634
1264  296.0731707
1265  -25.0000000
1266 -275.2439024
1267 -611.9756098
1268  480.8536585
1269 -510.5121951
1270   97.4390244
1271 -311.4390244
1272  603.8292683
1273 -461.9268293
1274  395.1463415
1275  427.5365854
1276  586.5121951
1277 -148.1219512
1278 -334.2682927
1279  690.5609756
1280  562.8536585
1281  -19.0975610
1282  470.8048780
1283  587.9268293
1284   53.3414634
1285 -534.1707317
1286    3.2926829
1287 -159.9756098
1288  114.5121951
1289  190.0243902
1290 -611.5365854
1291  499.5853659
1292  299.8780488
1293   27.8780488
1294 -329.4878049
1295 -395.8780488
1296 -586.0731707
1297  587.3414634
1298  658.7560976
1299  623.6341463
1300  542.6585366
1301 -434.5121951
1302 -128.4146341
1303  233.6341463
1304  297.2439024
1305  -89.2926829
1306 -479.0487805
1307    7.3414634
1308  176.7073171
1309 -508.4146341
1310 -548.3658537
1311   67.3414634
1312   96.6585366
1313  -90.8536585
1314  432.4146341
1315 -217.5853659
1316 -553.0487805
1317  569.9756098
1318 -571.4390244
1319 -115.2439024
1320 -678.1707317
1321    2.5121951
1322   34.5609756
1323 -680.4634146
1324 -704.6585366
1325  139.0975610
1326 -167.4390244
1327  522.2682927
1328 -501.6829268
1329 -146.6585366
1330 -461.8780488
1331  -61.0487805
1332 -163.6829268
1333 -490.2682927
1334  143.6341463
1335 -742.8048780
1336  752.1219512
1337  541.6829268
1338  -91.5365854
1339  414.5609756
1340   28.5121951
1341 -746.3658537
1342  471.9756098
1343  144.3658537
1344  -10.3658537
1345 -499.3414634
1346 -680.5121951
1347  610.3658537
1348   64.9024390
1349 -470.1707317
1350  125.0487805
1351 -576.3658537
1352  -60.6097561
1353 -229.5365854
1354 -123.5365854
1355 -473.7804878
1356 -284.9512195
1357  669.2926829
1358 -275.9756098
1359 -126.0243902
1360   93.2926829
1361 -581.6829268
1362  -29.0000000
1363  675.2926829
1364   86.2195122
1365  662.8048780
1366  -68.4634146
1367   -9.5365854
1368 -453.7804878
1369 -454.3170732
1370   17.0000000
1371  -47.9268293
1372  742.6097561
1373 -122.1219512
1374 -433.3902439
1375  135.2926829
1376 -252.6097561
1377 -570.6585366
1378   50.8536585
1379  -56.6097561
1380  603.1951220
1381  671.7317073
1382  727.8780488
1383  225.0975610
1384  -78.5121951
1385  108.4146341
1386  479.4390244
1387 -180.3170732
1388  270.0731707
1389  857.4878049
1390   33.8292683
1391 -590.7560976
1392   72.8048780
1393  589.5365854
1394 -619.1951220
1395   50.1219512
1396 -385.8292683
1397  850.3170732
1398 -140.2195122
1399 -539.3414634
1400  -20.5609756
1401  149.7317073
1402  243.3902439
1403  265.5853659
1404 -475.3414634
1405   39.1463415
1406  609.8780488
1407  141.6341463
1408  582.7073171
1409  -50.1219512
1410  381.1463415
1411  -55.4390244
1412 -558.8536585
1413  752.5121951
1414 -273.1463415
1415   91.2926829
1416  360.6097561
1417 -274.5609756
1418  -55.9268293
1419 -680.5121951
1420  156.4634146
1421   -1.5853659
1422  492.8048780
1423  127.2926829
1424  -13.9268293
1425 -351.8292683
1426  290.0243902
1427   28.5121951
1428 -558.3170732
1429  615.5853659
1430 -129.5853659
1431 -352.5121951
1432  643.4390244
1433 -127.4390244
1434 -808.9024390
1435  420.5609756
1436  228.0731707
1437 -584.8048780
1438  544.9512195
1439  331.3902439
1440  254.5609756
1441  -19.0975610
1442 -371.0000000
1443  596.1707317
1444  482.0731707
1445  463.9268293
1446  150.0243902
1447 -635.8780488
1448   60.0731707
1449  730.4146341
1450  551.6829268
1451 -423.2926829
1452  394.3658537
1453  308.4146341
1454   -4.5121951
1455  234.5609756
1456  453.3902439
1457 -428.4634146
1458  109.2926829
1459  753.1951220
1460 -378.0731707
1461 -385.4878049
1462 -795.3414634
1463 -500.4146341
1464  157.5365854
1465 -621.7317073
1466  337.6829268
1467 -526.3658537
1468  343.5365854
1469  577.0000000
1470  189.7317073
1471 -506.4634146
1472 -525.5365854
1473  587.6829268
1474 -670.4146341
1475  487.4878049
1476 -431.0000000
1477  569.0000000
1478   87.6829268
1479   77.9756098
1480  249.5853659
1481  607.8292683
1482  -27.7317073
1483  -44.2195122
1484 -613.1463415
1485 -503.7804878
1486 -168.2682927
1487 -603.1951220
1488  290.1219512
1489 -310.9512195
1490  424.9512195
1491 -577.2439024
1492 -185.0000000
1493  -83.8292683
1494  394.7073171
1495   -3.3902439
1496   25.9756098
1497   18.7073171
1498 -164.8536585
1499   10.4146341
1500 -465.6829268
1501  225.6829268
1502  154.3170732
1503  569.4390244
1504  175.0000000
1505 -279.7317073
1506 -450.8536585
1507  563.2439024
1508  338.3170732
1509 -242.6585366
1510   70.7073171
1511 -507.0487805
1512  105.0975610
1513 -675.2439024
1514 -368.3170732
1515 -174.6097561
1516  674.0243902
1517  -20.0731707
1518 -620.2195122
1519  423.9756098
1520   96.4634146
1521 -155.6829268
1522 -513.5365854
1523  627.4878049
1524    9.3902439
1525   -1.7804878
1526    8.5121951
1527  602.9024390
1528 -169.9268293
1529  737.8292683
1530 -649.7804878
1531  -53.1463415
1532  514.1707317
1533 -237.5365854
1534  -55.0000000
1535 -725.3902439
1536  569.3902439
1537 -371.5365854
1538 -649.0000000
1539 -689.3414634
1540 -345.5853659
1541  360.0243902
1542 -743.7804878
1543    2.5121951
1544 -729.2439024
1545 -868.3658537
1546 -586.6097561
1547  720.6585366
1548  477.6829268
1549 -433.4878049
1550  670.6097561
1551  348.2195122
1552 -345.5853659
1553  117.9756098
1554 -262.0243902
1555 -382.3170732
1556   -5.5365854
1557  -73.7804878
1558  628.4146341
1559   82.8536585
1560  723.0487805
1561 -160.2682927
1562 -592.0731707
1563   69.0975610
1564  146.8048780
1565 -530.7560976
1566 -547.7804878
1567 -615.0975610
1568  105.4390244
1569   84.7560976
1570  591.3414634
1571    7.9756098
1572  548.4634146
1573 -521.7317073
1574  218.6585366
1575   35.5853659
1576 -465.8292683
1577  123.8780488
1578  666.7560976
1579  467.4878049
1580 -552.1219512
1581   -5.3902439
1582 -329.4390244
1583  848.6585366
1584  484.6097561
1585   41.2926829
1586  510.2682927
1587  549.6341463
1588   35.0975610
1589 -475.7804878
1590  790.5609756
1591 -336.6585366
1592 -245.2439024
1593  -43.4878049
1594  787.1951220
1595  594.6585366
1596  244.9024390
1597  538.1707317
1598  -76.9024390
1599  512.4634146
1600  -93.2439024
1601  295.3902439
1602  540.2195122
1603  -39.4878049
1604 -527.7317073
1605  178.3170732
1606  561.9756098
1607  -94.7560976
1608  613.9756098
1609 -602.4146341
1610  -16.7560976
1611 -322.8048780
1612   -3.7317073
1613 -432.3170732
1614  138.6585366
1615 -499.1951220
1616  -10.7560976
1617 -104.4634146
1618  -11.4390244
1619 -155.6341463
1620 -491.0000000
1621 -450.1219512
1622 -119.6341463
1623  -71.8292683
1624 -585.9268293
1625 -409.1463415
1626  100.3658537
1627  -77.4878049
1628  682.0731707
1629  494.1707317
1630 -160.7560976
1631  574.3170732
1632   89.6341463
1633  627.4390244
1634 -484.0731707
1635 -568.8048780
1636 -247.1463415
1637  -12.0731707
1638 -676.1707317
1639  286.4634146
1640  135.3902439
1641 -146.4634146
1642  215.9756098
1643  267.5853659
1644  435.7317073
1645  -29.7317073
1646  144.7560976
1647 -458.1707317
1648 -456.0731707
1649  -82.9024390
1650  550.2682927
1651 -425.0975610
1652 -116.3658537
1653 -341.8780488
1654 -179.0000000
1655  -73.5853659
1656   17.9756098
1657 -428.5121951
1658  -47.1951220
1659 -298.5121951
1660   -6.7560976
1661  139.5365854
1662  -58.5609756
1663   50.3170732
1664  -25.5365854
1665   58.6097561
1666 -568.6097561
1667 -669.3902439
1668  391.4390244
1669  527.8292683
1670  179.4390244
1671  338.2682927
1672 -155.3902439
1673  468.1707317
1674 -201.7317073
1675 -211.9268293
1676  136.9024390
1677  211.7317073
1678  -91.7804878
1679 -510.0731707
1680  791.4390244
1681  -29.0487805
1682 -735.2439024
1683  642.0243902
1684 -515.6829268
1685  326.8048780
1686 -427.3414634
1687  439.3902439
1688 -419.8292683
1689  113.8780488
1690   27.9268293
1691 -512.9512195
1692   -3.0487805
1693 -559.6341463
1694 -490.5609756
1695 -123.2439024
1696 -410.9024390
1697  485.7804878
1698 -441.5853659
1699   89.3414634
1700  -99.8780488
1701  118.0243902
1702 -592.4634146
1703  -20.9512195
1704 -198.8048780
1705  284.4146341
1706  419.8292683
1707  -86.0731707
1708 -586.1707317
1709 -136.0731707
1710 -164.5121951
1711  493.3414634
1712 -412.7073171
1713  -72.3658537
1714  520.4634146
1715   54.6585366
1716 -616.1219512
1717 -124.4634146
1718  613.7804878
1719  241.2439024
1720  -13.9268293
1721  541.5365854
1722 -466.2195122
1723 -506.9024390
1724 -350.7560976
1725  -17.9756098
1726 -575.1463415
1727   19.6341463
1728  -67.9756098
1729 -249.9268293
1730  126.7073171
1731 -116.0731707
1732  -15.9756098
1733   87.7804878
1734 -547.0975610
1735 -236.4634146
1736 -514.6097561
1737  258.6585366
1738  475.9268293
1739  509.4390244
1740   -5.5853659
1741  -16.4634146
1742  294.0731707
1743  277.4878049
1744  -31.3414634
1745  617.3902439
1746  -72.9512195
1747  226.4146341
1748 -528.9512195
1749   79.2439024
1750 -539.0975610
1751 -295.1951220
1752   31.7804878
1753   35.2926829
1754  526.0731707
1755  138.1219512
1756 -554.4634146
1757 -177.1951220
1758 -662.9024390
1759  170.8048780
1760 -369.7317073
1761 -853.0487805
1762   78.2195122
1763   44.3170732
1764  -17.3414634
1765   85.2439024
1766  284.0731707
1767  115.1951220
1768 -296.7073171
1769  521.3414634
1770  -27.5365854
1771   11.6341463
1772  130.6585366
1773   23.1463415
1774 -115.1463415
1775 -620.1707317
1776   57.7317073
1777 -595.3902439
1778  670.6585366
1779   76.5121951
1780  -92.1707317
1781 -166.1219512
1782  -47.3414634
1783   88.2195122
1784 -534.7560976
1785  119.9268293
1786 -138.2682927
1787  613.8780488
1788  -20.5121951
1789  538.6585366
1790  383.0487805
1791  176.9512195
1792   67.6341463
1793  699.6341463
1794  -81.8292683
1795 -509.0000000
1796  629.4878049
1797 -579.1463415
1798 -649.5853659
1799  -18.8048780
1800   59.4878049
1801  326.4634146
1802  521.4390244
1803 -204.6097561
1804 -601.5853659
1805   22.5121951
1806  274.6097561
1807  290.3170732
1808  221.1951220
1809  623.1951220
1810  254.8048780
1811  193.9756098
1812 -608.1219512
1813 -134.1707317
1814 -687.5853659
1815  141.6341463
1816  -97.5853659
1817  122.0243902
1818 -503.2926829
1819 -460.9024390
1820  -30.8048780
1821 -114.5609756
1822  471.8780488
1823   99.3902439
1824 -132.5609756
1825 -630.0731707
1826 -261.3414634
1827  199.7317073
1828  269.7317073
1829   35.6829268
1830  140.4634146
1831   83.5365854
1832 -100.0243902
1833  469.9268293
1834  536.6585366
1835  -60.1219512
1836  118.6585366
1837 -513.6341463
1838 -454.0731707
1839  -78.6097561
1840 -276.8048780
1841  421.7804878
1842  -69.6829268
1843 -288.1219512
1844  240.4634146
1845 -621.4390244
1846  164.0243902
1847 -561.8292683
1848  -75.0000000
1849  440.3658537
1850   78.8536585
1851  379.0975610
1852  112.0731707
1853 -686.9512195
1854  322.5121951
1855  410.2682927
1856  250.1707317
1857 -501.8292683
1858  -11.9756098
1859  505.0000000
1860 -143.9268293
1861   -0.5609756
1862   43.1951220
1863 -375.4390244
1864  -39.7804878
1865 -541.1951220
1866   20.7073171
1867 -454.2195122
1868  219.5365854
1869 -567.0975610
1870 -634.1707317
1871  671.3414634
1872  517.4878049
1873  -16.7073171
1874  525.7317073
1875  137.3902439
1876  -35.2439024
1877  261.8780488
1878   95.6829268
1879   16.5609756
1880  771.5853659
1881 -135.0487805
1882  171.9268293
1883  -35.2439024
1884 -160.7560976
1885 -112.0731707
1886  -66.7073171
1887  -96.4146341
1888 -542.3658537
1889  133.9268293
1890  104.4146341
1891    2.3170732
1892 -271.2439024
1893 -572.9512195
1894  478.5609756
1895  -96.8536585
1896  475.3902439
1897 -407.0000000
1898 -374.0731707
1899  565.1951220
1900   69.4390244
1901 -295.0000000
1902  -50.5121951
1903 -780.1219512
1904   41.9268293
1905 -202.5609756
1906  703.9756098
1907 -186.1707317
1908 -302.0731707
1909 -141.9756098
1910  357.6341463
1911  629.6341463
1912   98.3658537
1913  102.7073171
1914  152.9024390
1915  491.1951220
1916  326.1219512
1917 -596.9512195
1918  616.3170732
1919  464.5609756
1920  311.2439024
1921    5.6829268
1922  739.0975610
1923 -230.2195122
1924  747.4390244
1925  427.1951220
1926  391.8292683
1927 -244.6585366
1928 -378.6585366
1929    1.4878049
1930  -53.9268293
1931  -17.9268293
1932  421.2926829
1933  151.0975610
1934 -600.9512195
1935  479.0487805
1936 -775.0000000
1937  485.1951220
1938  -27.8292683
1939  657.5365854
1940  492.7560976
1941 -602.1707317
1942 -102.3658537
1943 -520.1219512
1944  514.1707317
1945 -114.8536585
1946  251.0487805
1947    9.5853659
1948 -674.3170732
1949  521.8780488
1950  210.5609756
1951 -158.1219512
1952  212.9512195
1953  649.4878049
1954 -632.5121951
1955  306.0243902
1956  -95.6341463
1957  194.7073171
1958 -470.1219512
1959 -139.1951220
1960 -403.6829268
1961  700.4634146
1962 -847.0975610
1963 -604.4634146
1964  -73.5853659
1965  319.0000000
1966  -74.5121951
1967  218.1219512
1968   84.7073171
1969  -12.7560976
1970   15.0975610
1971  166.6097561
1972 -285.2439024
1973    0.7560976
1974 -371.0975610
1975 -183.2439024
1976    9.3902439
1977  -13.5365854
1978  489.5853659
1979  770.2682927
1980  -78.9512195
1981  -16.6585366
1982  147.8292683
1983  178.8048780
1984 -544.6585366
1985  691.7804878
1986 -244.1707317
1987  150.5609756
1988  263.6829268
1989  528.4146341
1990  -95.1951220
1991 -224.5609756
1992  204.0243902
1993   -6.7073171
1994 -567.1463415
1995  301.6341463
1996  -39.3414634
1997  380.6097561
1998  327.7317073
1999   35.3414634
2000  298.9024390
2001 -371.4390244
2002  660.5609756
2003 -522.6097561
2004 -461.2439024
2005 -340.0731707
2006 -203.5853659
2007  655.8292683
2008  290.7073171
2009  122.4634146
2010  543.2926829
2011 -599.2439024
2012   21.3902439
2013 -138.1707317
2014  642.1707317
2015   17.9268293
2016  -72.4146341
2017  -47.7804878
2018 -111.4878049
2019  732.9512195
2020   45.7317073
2021 -206.7073171
2022  -57.0000000
2023    0.2195122
2024  -32.8536585
2025  356.4146341
2026  728.5609756
2027 -628.8536585
2028  282.0243902
2029  456.9512195
2030  110.6585366
2031  583.0000000
2032 -743.9756098
2033  651.7317073
2034  639.5365854
2035 -105.9268293
2036 -135.6829268
2037  572.5609756
2038   86.0731707
2039 -134.7073171
2040  -45.7804878
2041  283.2439024
2042  571.5365854
2043  534.5609756
2044  -58.9024390
2045  329.9268293
2046  214.0243902
2047 -429.7317073
2048 -441.5365854
2049 -510.4146341
2050  591.4390244
2051 -169.1951220
2052  309.4390244
2053  -37.4878049
2054  102.5609756
2055 -525.5365854
2056   99.9268293
2057  401.1951220
2058   -2.3170732
2059  783.9268293
2060  585.5365854
2061 -124.9024390
2062 -103.7804878
2063  136.2195122
2064  828.1707317
2065 -436.5609756
2066 -397.1463415
2067 -209.7317073
2068 -424.5121951
2069  550.2195122
2070  103.2439024
2071 -502.3170732
2072 -147.9268293
2073  251.1951220
2074  628.9024390
2075  151.8780488
2076 -445.3902439
2077  358.5121951
2078 -194.6097561
2079  485.7317073
2080 -595.6341463
2081   -0.2195122
2082  427.8292683
2083   -2.6585366
2084 -698.7560976
2085   41.6829268
2086 -648.4146341
2087  808.7560976
2088 -388.8536585
2089  168.0243902
2090 -394.7560976
2091  112.7560976
2092 -146.0731707
2093  231.1463415
2094  157.6829268
2095 -364.7073171
2096 -235.6829268
2097  -11.2439024
2098 -111.7317073
2099 -103.0487805
2100 -133.2439024
2101  566.2195122
2102 -315.1463415
2103 -176.1219512
2104 -696.1707317
2105  604.0243902
2106 -646.3170732
2107 -330.7073171
2108 -659.4390244
2109 -175.8780488
2110  120.6585366
2111   49.6829268
2112 -261.3902439
2113  340.3170732
2114 -286.2682927
2115 -725.7317073
2116   20.6097561
2117  -42.8536585
2118  193.7317073
2119  132.1219512
2120  305.2926829
2121 -527.8780488
2122 -156.5609756
2123  -48.2195122
2124  543.6341463
2125  -90.5609756
2126 -566.4146341
2127 -497.6341463
2128  -39.5853659
2129  154.9024390
2130 -594.3658537
2131  468.1707317
2132  687.7317073
2133   -4.9512195
2134  551.0975610
2135  866.7560976
2136  557.1951220
2137 -113.3414634
2138  416.8048780
2139  -34.0731707
2140  -28.7073171
2141  149.1951220
2142  747.4878049
2143  -56.6585366
2144 -883.9756098
2145  -69.0000000
2146   61.8292683
2147   32.0731707
2148  133.1463415
2149 -543.9268293
2150  101.1463415
2151 -538.0243902
2152  100.4634146
2153  -59.7317073
2154  -95.7804878
2155   32.7560976
2156  745.2439024
2157  156.1707317
2158   61.0000000
2159    4.0243902
2160 -256.4146341
2161  591.5853659
2162  137.3414634
2163 -430.1219512
2164 -401.7317073
2165  314.8536585
2166 -511.3414634
2167  135.1463415
2168  117.5853659
2169 -342.7073171
2170 -367.9756098
2171 -520.4634146
2172 -416.9024390
2173  392.0731707
2174 -390.1219512
2175  537.1463415
2176 -488.4634146
2177 -555.2926829
2178  240.0243902
2179  443.6341463
2180 -578.3170732
2181  436.0731707
2182  113.8780488
2183  745.4878049
2184  104.6585366
2185  129.2439024
2186  -73.4390244
2187  463.5365854
2188   -8.4146341
2189  454.5121951
2190  454.9512195
2191  350.1219512
2192 -486.0243902
2193  123.1951220
2194 -480.5121951
2195 -577.1463415
2196  105.1463415
2197 -289.5853659
2198 -868.5609756
2199 -429.5365854
2200 -789.0975610
2201   -7.7804878
2202 -581.6829268
2203  258.0243902
2204  522.1219512
2205 -543.5853659
2206 -619.3414634
2207 -684.9512195
2208 -414.9512195
2209  703.9756098
2210  654.2682927
2211  -19.4390244
2212  201.0975610
2213  608.5609756
2214  421.2926829
2215  121.7804878
2216 -685.3902439
2217 -578.2682927
2218 -352.3170732
2219 -777.2926829
2220 -325.4878049
2221   95.2439024
2222 -201.6829268
2223 -178.7560976
2224   95.6829268
2225  123.4390244
2226 -526.9512195
2227   91.4390244
2228  -81.5365854
2229 -338.5121951
2230 -546.6097561
2231 -622.3658537
2232  319.0000000
2233  445.7317073
2234  142.7073171
2235 -443.0000000
2236 -488.2195122
2237 -103.3902439
2238 -167.9268293
2239  -78.0243902
2240  179.4390244
2241 -576.8536585
2242 -441.3902439
2243  -75.3414634
2244 -165.8292683
2245  795.5365854
2246    4.1707317
2247 -160.6097561
2248  109.6829268
2249 -552.9512195
2250 -123.0000000
2251  242.1219512
2252  107.3902439
2253  272.6585366
2254    7.1463415
2255  261.6829268
2256  -50.7560976
2257 -496.2195122
2258   27.2926829
2259 -244.2195122
2260  -63.7317073
2261   76.3658537
2262  120.6097561
2263  -28.5121951
2264 -645.0487805
2265 -244.4146341
2266  129.4390244
2267 -277.2439024
2268  232.6585366
2269   49.5365854
2270 -612.5609756
2271  388.3658537
2272 -101.8780488
2273 -336.4146341
2274  533.8780488
2275  -64.9024390
2276 -137.0000000
2277 -292.9024390
2278  101.3902439
2279  480.6097561
2280   63.9268293
2281 -476.6097561
2282  448.1707317
2283 -535.7317073
2284 -120.6097561
2285 -411.6341463
2286 -509.0000000
2287 -450.6097561
2288 -561.0000000
2289  165.5365854
2290  532.6585366
2291  462.3658537
2292 -528.0731707
2293 -586.5121951
2294  425.2926829
2295   -6.4634146
2296 -131.7804878
2297  638.5609756
2298  102.4146341
2299  409.8780488
2300  591.6341463
2301  660.3170732
2302  -92.4634146
2303 -384.4146341
2304 -458.4634146
2305 -109.4390244
2306 -107.7317073
2307   11.4878049
2308  510.5609756
2309  545.5853659
2310 -788.2195122
2311   23.0487805
2312  -94.9024390
2313 -312.3658537
2314 -412.6585366
2315  196.1707317
2316  415.4390244
2317  112.5121951
2318  148.9512195
2319  -30.0731707
2320  117.8292683
2321  160.2682927
2322  -53.3414634
2323  198.0731707
2324  102.5121951
2325   35.0975610
2326 -121.9756098
2327 -149.1463415
2328 -123.8780488
2329   62.8536585
2330  618.3170732
2331  548.1219512
2332  124.1707317
2333 -141.2439024
2334 -736.6097561
2335  111.8780488
2336  687.1463415
2337  317.2439024
2338   48.2682927
2339  647.7317073
2340 -632.0731707
2341 -565.1951220
2342 -301.4390244
2343 -273.1463415
2344  793.6829268
2345 -230.8048780
2346  -17.4390244
2347   87.4390244
2348  337.8292683
2349 -333.5853659
2350  327.1951220
2351 -557.5853659
2352 -165.1951220
2353 -721.6829268
2354  -17.1951220
2355  -82.4634146
2356  460.1219512
2357  372.7073171
2358  569.3414634
2359  724.8048780
2360  -20.0243902
2361  171.0975610
2362  612.1707317
2363 -680.6097561
2364 -138.2682927
2365 -495.9268293
2366  -28.8536585
2367 -463.1463415
2368  485.9268293
2369 -385.1463415
2370 -139.0975610
2371  493.0000000
2372   -0.1219512
2373  -18.5121951
2374  602.4634146
2375 -612.4146341
2376  127.1463415
2377 -640.0731707
2378  336.2195122
2379  552.5609756
2380 -325.7804878
2381   -7.7804878
2382 -316.3170732
2383 -487.4878049
2384  182.7073171
2385  277.0487805
2386  203.0000000
2387  186.9024390
2388 -186.2195122
2389 -731.8292683
2390  452.4146341
2391 -177.7317073
2392  -25.3902439
2393 -671.6829268
2394 -129.0487805
2395   65.7804878
2396  332.5121951
2397  -42.5121951
2398 -504.7560976
2399 -132.5609756
2400 -396.8536585
2401  244.8536585
2402  518.6585366
2403  481.0975610
2404 -102.5609756
2405 -188.4634146
2406 -425.3902439
2407  659.6341463
2408  683.9756098
2409   47.7317073
2410  341.3902439
2411  -63.3902439
2412   70.1219512
2413   57.2439024
2414  409.7804878
2415  147.8292683
2416 -128.6097561
2417    9.1951220
2418 -110.5121951
2419  484.1219512
2420 -148.6097561
2421 -608.6097561
2422 -646.1707317
2423  141.6829268
2424 -559.0487805
2425 -115.6829268
2426  555.6341463
2427  -89.7804878
2428  -65.3414634
2429 -158.2682927
2430  461.0487805
2431 -245.6829268
2432 -207.5365854
2433 -185.3414634
2434 -276.9512195
2435  551.6829268
2436  166.9512195
2437 -699.0975610
2438 -373.6829268
2439 -287.5853659
2440  407.3414634
2441  178.9512195
2442 -491.1463415
2443  -52.4634146
2444  587.6829268
2445  484.3658537
2446  471.0975610
2447  646.8048780
2448  486.0243902
2449   25.3414634
2450  481.2926829
2451 -735.6341463
2452 -256.7560976
2453  755.1951220
2454 -775.3414634
2455  655.9268293
2456  469.0000000
2457  184.2195122
2458  446.4146341
2459 -274.0731707
2460  -67.1463415
2461  -55.9268293
2462   54.3658537
2463 -198.1219512
2464 -204.2682927
2465 -129.7317073
2466   14.7073171
2467   13.0487805
2468   90.6097561
2469 -497.6341463
2470  640.3170732
2471 -844.6585366
2472  423.9268293
2473  360.5121951
2474 -753.6829268
2475 -761.0487805
2476  113.0000000
2477  360.4146341
2478  550.4146341
2479  799.5365854
2480 -139.5853659
2481 -101.1463415
2482   48.1219512
2483  -63.3414634
2484  650.7073171
2485  -11.3902439
2486  569.5853659
2487 -400.4146341
2488 -122.5609756
2489 -622.1707317
2490 -462.4634146
2491   24.6585366
2492 -698.2682927
2493   59.6341463
2494 -403.2926829
2495  -29.5853659
2496 -291.1463415
2497  458.7560976
2498 -223.4878049
2499   96.5609756
2500  -96.4634146
2501 -922.1219512
2502  589.3414634
2503  -53.4390244
2504   23.8292683
2505   29.8292683
2506   24.3170732
2507   22.4634146
2508   -5.7804878
2509  163.4390244
2510    2.3170732
2511   98.8048780
2512 -443.2439024
2513  204.7560976
2514  -38.3658537
2515  -45.6341463
2516  -56.4634146
2517  560.9024390
2518  292.7073171
2519  471.7317073
2520 -208.2195122
2521  386.0731707
2522  252.5121951
2523  255.2926829
2524 -435.0487805
2525  156.5121951
2526  179.5365854
2527  603.7804878
2528 -102.1707317
2529 -112.5609756
2530 -523.6829268
2531 -259.0000000
2532  -69.4390244
2533    9.6829268
2534 -378.9024390
2535 -525.4390244
2536   19.1463415
2537   92.1707317
2538 -277.1463415
2539 -509.1463415
2540  684.8048780
2541  209.0000000
2542 -500.4634146
2543   43.6829268
2544 -124.0243902
2545   59.5365854
2546 -731.8292683
2547  489.0487805
2548 -363.9756098
2549  635.0000000
2550 -279.2439024
2551 -658.7560976
2552  -39.3902439
2553  183.5853659
2554   50.8048780
2555 -548.4146341
2556  -59.7317073
2557  235.8292683
2558  -43.1463415
2559  341.6341463
2560   68.5609756
2561  145.0975610
2562  346.2195122
2563 -147.2439024
2564  173.0975610
2565  554.7073171
2566 -605.3414634
2567 -545.8780488
2568 -241.7804878
2569  543.3414634
2570 -156.1219512
2571  455.3414634
2572  599.7804878
2573  -80.4146341
2574 -168.2195122
2575    1.0000000
2576 -723.1951220
2577   45.1463415
2578  462.7073171
2579 -106.1707317
2580  -90.0243902
2581  -29.5365854
2582   92.2195122
2583  484.0731707
2584 -547.9268293
2585   -8.8536585
2586 -741.6341463
2587 -546.0731707
2588 -503.0000000
2589  592.9024390
2590 -619.5853659
2591  441.4878049
2592 -832.5121951
2593  251.5365854
2594  725.7317073
2595  577.4390244
2596 -129.3902439
2597  726.2195122
2598 -610.6585366
2599  124.7073171
2600 -493.0000000
2601 -197.8780488
2602 -400.7073171
2603  155.3414634
2604 -262.6097561
2605 -444.7560976
2606   56.1219512
2607 -534.0243902
2608  422.7073171
2609 -712.6585366
2610  849.0000000
2611 -546.4146341
2612 -113.6341463
2613  440.3658537
2614  575.5853659
2615  107.1951220
2616    9.8780488
2617  802.5121951
2618 -197.4390244
2619  573.2926829
2620  619.0487805
2621  -62.2682927
2622 -140.3658537
2623  161.0975610
2624  -63.3414634
2625  -52.8536585
2626 -585.0975610
2627  280.3658537
2628 -707.5853659
2629 -506.2195122
2630   68.7073171
2631  843.2926829
2632   92.5121951
2633  150.9512195
2634  -60.7560976
2635 -505.4390244
2636  -29.2439024
2637 -464.0243902
2638  357.4390244
2639   62.5609756
2640 -323.4390244
2641   31.2439024
2642 -628.3658537
2643 -561.7804878
2644  475.3414634
2645  642.9024390
2646 -489.6341463
2647  616.2195122
2648   91.7317073
2649  353.0487805
2650  598.8536585
2651   24.1707317
2652 -624.9512195
2653   24.3170732
2654  -18.6097561
2655  385.3902439
2656 -588.6097561
2657  574.6585366
2658 -264.5609756
2659  132.4634146
2660 -284.2682927
2661 -425.8780488
2662  434.0243902
2663  -95.1951220
2664 -635.6341463
2665  -85.4878049
2666  187.5853659
2667  -92.5609756
2668 -543.2926829
2669   26.1219512
2670  101.6829268
2671 -669.6341463
2672 -618.1707317
2673    8.3170732
2674  513.4390244
2675  392.5121951
2676   51.5365854
2677  129.8292683
2678  626.2195122
2679 -150.4634146
2680 -506.9512195
2681 -323.0000000
2682  -78.2682927
2683  703.4390244
2684  601.9756098
2685 -513.6341463
2686   24.3170732
2687    9.6829268
2688 -539.9756098
2689 -423.2926829
2690 -166.0731707
2691  -16.3170732
2692  -78.6097561
2693  437.5365854
2694  312.7560976
2695  151.3414634
2696 -105.9756098
2697 -151.7804878
2698 -370.2682927
2699 -375.2926829
2700  -11.0000000
2701   83.1951220
2702  455.0000000
2703  170.9512195
2704  229.9268293
2705  669.1463415
2706 -434.1219512
2707  458.3658537
2708    0.6585366
2709 -604.4634146
2710  143.2439024
2711  357.0487805
2712   49.9756098
2713  489.3414634
2714  577.0000000
2715  566.4634146
2716 -767.6341463
2717 -225.5365854
2718   81.5853659
2719   74.9024390
2720  -24.1219512
2721 -240.1219512
2722  204.4146341
2723  599.7317073
2724 -582.7073171
2725  259.4878049
2726  542.9024390
2727 -412.3658537
2728   98.6097561
2729  182.4634146
2730 -406.4146341
2731  339.3902439
2732  169.8292683
2733  -66.6097561
2734  -44.0731707
2735 -112.5609756
2736  433.6829268
2737  127.6829268
2738  521.7804878
2739  695.0975610
2740 -389.9268293
2741  144.0243902
2742  -77.5853659
2743 -248.4634146
2744 -755.3902439
2745  -56.0243902
2746  -88.8048780
2747  204.4634146
2748  -55.6341463
2749 -363.4390244
2750 -252.5121951
2751 -315.8780488
2752  -33.0975610
2753 -159.9756098
2754  249.5365854
2755   77.4390244
2756 -566.4634146
2757   44.8048780
2758   21.9756098
2759 -691.0975610
2760 -115.2439024
2761 -240.6585366
2762 -428.8536585
2763 -598.9512195
2764 -302.7073171
2765 -150.9512195
2766 -120.2195122
2767 -788.7073171
2768  551.8780488
2769 -449.6829268
2770  -27.5365854
2771 -332.5609756
2772   -6.9512195
2773 -798.1707317
2774 -600.5121951
2775 -515.2439024
2776  -77.3414634
2777 -622.2682927
2778 -476.9024390
2779 -800.1219512
2780 -611.5853659
2781 -673.2926829
2782 -466.3658537
2783  165.0487805
2784 -420.1707317
2785   21.6341463
2786  568.7560976
2787 -326.9512195
2788  208.9512195
2789  517.5853659
2790 -643.8780488
2791  560.9024390
2792 -625.7317073
2793  460.6097561
2794  763.0487805
2795  356.1219512
2796 -277.6341463
2797  210.0731707
2798 -563.8780488
2799 -126.3658537
2800  647.9268293
2801 -318.0243902
2802  295.3902439
2803   21.4390244
2804 -522.7560976
2805 -325.8292683
2806  191.8780488
2807 -287.1463415
2808  381.1951220
2809  368.2195122
2810  467.0975610
2811 -248.9024390
2812 -483.7317073
2813 -170.2195122
2814  510.0243902
2815 -536.2195122
2816  335.1951220
2817  -56.4146341
2818  -34.6097561
2819 -701.0000000
2820 -169.3414634
2821  102.7560976
2822  -60.0243902
2823  -10.5121951
2824 -155.3414634
2825 -139.1463415
2826   22.5609756
2827  777.6341463
2828   11.6829268
2829 -447.3902439
2830 -568.4146341
2831 -478.1707317
2832 -710.7073171
2833 -118.8536585
2834  101.5853659
2835  591.4390244
2836   45.1951220
2837   81.7317073
2838 -492.9512195
2839 -524.3658537
2840   90.0243902
2841   59.2439024
2842  108.2682927
2843 -281.6829268
2844 -351.1463415
2845 -234.0731707
2846 -129.3902439
2847  -87.4878049
2848   37.4878049
2849  581.8292683
2850 -387.6341463
2851   71.3414634
2852  -45.0975610
2853 -168.4146341
2854  664.1219512
2855 -135.5853659
2856 -103.9756098
2857   -7.3902439
2858  106.7073171
2859  242.2682927
2860  -80.0243902
2861   93.7804878
2862 -602.5121951
2863 -454.2195122
2864  -13.5853659
2865  172.9024390
2866 -241.4390244
2867  306.2195122
2868  347.4878049
2869  441.7317073
2870  -90.2195122
2871 -497.0975610
2872    9.6341463
2873 -364.9512195
2874 -556.2682927
2875 -395.8780488
2876  129.5853659
2877  732.0243902
2878  199.7317073
2879   24.1707317
2880 -492.7073171
2881  655.4390244
2882  -95.0487805
2883   -3.2439024
2884  445.7804878
2885  539.5853659
2886  494.4146341
2887  662.2195122
2888  394.1707317
2889  793.5853659
2890  -59.9268293
2891  -67.7804878
2892  306.4146341
2893 -410.2682927
2894  357.3902439
2895  632.9024390
2896  -51.7804878
2897   75.2926829
2898 -113.0000000
2899 -129.1463415
2900 -297.1951220
2901 -106.5609756
2902   90.8536585
2903 -478.8048780
2904 -720.4634146
2905 -579.5853659
2906 -300.9024390
2907 -451.7804878
2908  272.8536585
2909  171.9268293
2910 -358.1219512
2911  806.9512195
2912  463.1463415
2913 -667.3414634
2914 -698.1707317
2915   -0.3170732
2916  -17.8780488
2917 -187.0000000
2918  247.6341463
2919 -218.3658537
2920  326.5609756
2921  129.0975610
2922    3.9268293
2923   73.9268293
2924    4.8048780
2925 -410.8048780
2926  327.6829268
2927   35.2926829
2928 -792.1707317
2929 -116.7073171
2930  550.7073171
2931  589.6829268
2932 -132.0243902
2933   99.6341463
2934 -647.9268293
2935   91.7317073
2936  108.7560976
2937  603.3902439
2938  -50.1707317
2939 -770.5121951
2940 -246.8536585
2941  127.0000000
2942 -705.6341463
2943  -52.7560976
2944  -67.0975610
2945 -122.6585366
2946  613.9756098
2947  652.6585366
2948 -132.3170732
2949  -83.6829268
2950 -190.4634146
2951  511.5853659
2952 -127.2439024
2953 -382.9512195
2954 -483.1463415
2955 -425.1951220
2956 -163.0975610
2957 -368.2195122
2958 -548.8536585
2959  556.1707317
2960  139.3902439
2961   53.4390244
2962  606.7073171
2963   21.9268293
2964 -173.2926829
2965  597.0975610
2966  118.1707317
2967 -619.4878049
2968  132.1219512
2969 -509.6829268
2970 -177.5853659
2971 -530.8048780
2972 -491.5365854
2973 -550.6585366
2974  190.3170732
2975   86.3170732
2976  168.0243902
2977  343.9756098
2978  -89.9756098
2979 -566.2195122
2980  442.3658537
2981  283.0000000
2982  515.0000000
2983 -675.0000000
2984 -547.4878049
2985 -226.6585366
2986 -426.8536585
2987 -572.0731707
2988 -542.3170732
2989  -81.8292683
2990 -122.0731707
2991 -647.6341463
2992  319.8292683
2993 -106.7560976
2994  150.6097561
2995 -283.8780488
2996 -614.1707317
2997  760.6585366
2998  565.5853659
2999 -314.4634146
3000   34.9024390
3001 -565.4878049
3002   58.2682927
3003 -140.6585366
3004  -79.0000000
3005  105.1463415
3006 -401.3902439
3007 -196.2195122
3008  546.7560976
3009 -446.8048780
3010  182.2682927
3011  354.0731707
3012 -604.4634146
3013  601.7804878
3014  649.0487805
3015  564.8048780
3016 -441.5853659
3017  210.8048780
3018 -713.5365854
3019  108.2682927
3020  601.5365854
3021   -7.0975610
3022  327.6829268
3023  593.8780488
3024  616.3658537
3025   26.9024390
3026 -133.9268293
3027  607.8780488
3028  718.7560976
3029 -598.7560976
3030  597.4390244
3031 -304.1707317
3032 -458.8048780
3033  693.1951220
3034   73.2439024
3035 -104.3658537
3036  529.1951220
3037  302.0243902
3038 -660.9024390
3039  857.8780488
3040 -175.3902439
3041   18.6097561
3042 -494.1707317
3043 -115.7317073
3044  414.3658537
3045  365.9756098
3046 -500.0731707
3047  727.3414634
3048 -560.2195122
3049 -458.3170732
3050  231.5853659
3051 -623.0000000
3052   35.6829268
3053  515.2926829
3054  582.9512195
3055 -172.3658537
3056  113.0975610
3057   -7.8292683
3058 -108.4634146
3059  -38.1707317
3060  602.2195122
3061 -576.4634146
3062  130.0731707
3063  -72.0243902
3064 -768.2682927
3065  296.9512195
3066 -461.2439024
3067  650.7560976
3068  640.5121951
3069  448.2195122
3070  320.8536585
3071 -291.2926829
3072  -83.0000000
3073  788.3658537
3074  675.5365854
3075  262.1707317
3076  153.1951220
3077  296.9512195
3078 -568.3658537
3079  601.0487805
3080 -879.2926829
3081  136.6585366
3082  263.2439024
3083   41.9268293
3084 -135.4390244
3085  132.6585366
3086  -79.6341463
3087  679.3414634
3088  119.4390244
3089 -512.1219512
3090  -73.2926829
3091   -3.6829268
3092  490.3170732
3093  -44.3658537
3094   26.7073171
3095  581.8292683
3096  549.9268293
3097  -72.8048780
3098  -35.5365854
3099   79.6829268
3100  -44.4634146
3101 -167.7317073
3102  -95.9268293
3103  503.8292683
3104 -339.2439024
3105  150.2682927
3106  194.6097561
3107 -672.9512195
3108 -634.2682927
3109  -73.2926829
3110   98.7073171
3111  121.1463415
3112  192.3658537
3113 -175.5853659
3114 -308.6097561
3115   97.1951220
3116  -75.3414634
3117   -8.4634146
3118  850.1707317
3119  451.6829268
3120 -326.9512195
3121  597.2926829
3122  521.9268293
3123  644.0731707
3124 -133.7804878
3125  -90.5609756
3126 -835.8780488
3127  526.3658537
3128 -493.4390244
3129 -452.0243902
3130  513.1951220
3131 -670.7560976
3132 -483.6829268
3133 -198.3170732
3134  392.1219512
3135  217.5853659
3136  276.9512195
3137 -184.6097561
3138 -204.4146341
3139 -454.8536585
3140  117.7804878
3141  573.9268293
3142 -558.0243902
3143  695.2439024
3144  626.7073171
3145   44.5609756
3146 -385.3414634
3147   41.0487805
3148 -375.1463415
3149  329.0487805
3150  277.8780488
3151   13.0487805
3152  198.8536585
3153  457.2439024
3154  -73.6341463
3155   14.5609756
3156  565.0000000
3157   12.5121951
3158 -706.3170732
3159  212.4146341
3160  -96.6585366
3161 -228.8536585
3162  303.9756098
3163  240.6097561
3164  -28.4634146
3165  318.3658537
3166 -438.0243902
3167  170.4634146
3168  464.4634146
3169 -119.9268293
3170  344.2682927
3171  239.2926829
3172  309.0975610
3173  -50.0243902
3174  440.6585366
3175 -217.5365854
3176  320.4634146
3177  502.1707317
3178   -4.2682927
3179 -775.9268293
3180  -33.9268293
3181 -234.3658537
3182 -145.2926829
3183  748.7560976
3184  132.2195122
3185 -465.0975610
3186  -83.8292683
3187   15.2439024
3188 -397.7804878
3189   61.2926829
3190  600.2195122
3191  188.3170732
3192 -626.2195122
3193 -452.3170732
3194 -581.6829268
3195   13.0487805
3196 -264.9024390
3197 -706.7073171
3198 -285.1951220
3199 -529.0487805
3200  532.9512195
3201  -94.7073171
3202 -665.5365854
3203 -743.2926829
3204 -497.1463415
3205 -251.6341463
3206  -58.1707317
3207 -817.9268293
3208  -99.3414634
3209 -449.9756098
3210  -46.8536585
3211 -637.8780488
3212 -141.1463415
3213  -93.4878049
3214   92.8048780
3215  -92.7073171
3216 -315.9756098
3217  513.6829268
3218  -15.2926829
3219 -814.2195122
3220   53.2439024
3221  735.2439024
3222 -156.5609756
3223 -622.5121951
3224  -49.6341463
3225  -72.5609756
3226 -222.3658537
3227  -23.9756098
3228  774.5121951
3229  205.3902439
3230 -610.3658537
3231 -129.0000000
3232  613.1463415
3233 -529.4878049
3234 -426.0243902
3235  147.3414634
3236  484.7560976
3237 -191.9756098
3238    5.2926829
3239 -181.3902439
3240 -181.2439024
3241  124.8536585
3242 -626.3658537
3243  -78.7560976
3244  138.3170732
3245  119.6829268
3246 -116.8536585
3247   74.5609756
3248  408.4146341
3249 -389.9268293
3250 -200.1707317
3251 -116.6097561
3252 -188.8048780
3253 -167.0487805
3254 -384.7073171
3255    1.0975610
3256 -519.0975610
3257  492.4634146
3258  -96.3170732
3259   91.1951220
3260 -306.4146341
3261 -501.3902439
3262 -588.0243902
3263  -13.5853659
3264   87.9268293
3265 -135.2926829
3266 -652.6585366
3267  -60.7073171
3268 -468.1707317
3269  602.4634146
3270  696.5121951
3271 -412.5609756
3272  663.2439024
3273  411.5853659
3274  -88.6585366
3275 -618.1707317
3276  398.4146341
3277 -596.5121951
3278   89.5853659
3279  378.1219512
3280 -107.5365854
3281 -667.5853659
3282  156.4146341
3283 -450.3658537
3284 -260.8048780
3285  555.1951220
3286   43.6341463
3287  -95.3414634
3288 -110.7560976
3289 -422.9024390
3290 -691.2926829
3291  519.7804878
3292  103.7804878
3293  375.0487805
3294   83.2926829
3295  -54.2682927
3296 -118.1219512
3297  111.3414634
3298 -557.9756098
3299  252.5121951
3300  282.2195122
3301 -134.1219512
3302 -139.9756098
3303   77.8780488
3304  133.1463415
3305 -543.7317073
3306 -874.9512195
3307 -488.8048780
3308   69.6829268
3309 -361.8780488
3310  494.7073171
3311  557.4390244
3312  917.2926829
3313  723.1951220
3314   39.3414634
3315  586.3658537
3316 -143.3902439
3317   79.3902439
3318  460.3170732
3319 -529.8780488
3320  227.8780488
3321  540.8536585
3322  112.7073171
3323 -170.0243902
3324  195.4878049
3325  102.7073171
3326  -62.8048780
3327  350.8048780
3328  651.2926829
3329   31.8292683
3330 -612.1219512
3331  701.1951220
3332 -226.6097561
3333  -55.2926829
3334 -462.5609756
3335 -351.9756098
3336  -44.0243902
3337  158.6097561
3338 -237.4878049
3339  100.8536585
3340  541.4878049
3341  416.5121951
3342  -49.9756098
3343  283.9756098
3344 -323.3414634
3345 -597.4390244
3346   72.2682927
3347   25.1951220
3348 -439.0487805
3349  709.4390244
3350 -198.5609756
3351  105.2439024
3352  527.6829268
3353   29.5365854
3354  383.2439024
3355 -279.0975610
3356 -159.9268293
3357    1.0487805
3358  330.4146341
3359 -568.8048780
3360  538.2682927
3361 -557.9268293
3362  -18.1219512
3363  316.6585366
3364  500.4146341
3365  -54.0243902
3366  178.3170732
3367 -159.2439024
3368   97.7804878
3369 -760.5121951
3370  460.7560976
3371 -623.7317073
3372  608.5121951
3373  -30.6585366
3374   16.6585366
3375  624.2682927
3376  740.2682927
3377 -322.5609756
3378   77.5365854
3379 -224.3658537
3380   87.5853659
3381 -421.7317073
3382 -596.5121951
3383 -123.9756098
3384 -177.1951220
3385  -62.5121951
3386  439.4878049
3387 -649.8780488
3388 -368.4146341
3389  -96.4634146
3390  564.6585366
3391 -491.0000000
3392 -381.9756098
3393  -91.2439024
3394 -140.6097561
3395  -92.3658537
3396 -533.8292683
3397 -499.8292683
3398 -236.9024390
3399  -43.2439024
3400   74.3170732
3401   46.4146341
3402 -158.5121951
3403  204.8536585
3404 -155.6341463
3405 -299.6829268
3406  179.8292683
3407 -253.7804878
3408 -521.0975610
3409 -309.6829268
3410  526.8048780
3411 -217.2926829
3412   12.1707317
3413  722.1707317
3414   75.8292683
3415  150.2682927
3416  114.1707317
3417  294.7073171
3418  469.1951220
3419 -495.0487805
3420  541.3414634
3421   42.7073171
3422 -576.2195122
3423  510.8048780
3424 -459.0975610
3425 -443.1463415
3426 -737.0000000
3427  -85.1463415
3428 -443.2926829
3429   95.8780488
3430  677.0000000
3431  -77.0975610
3432 -566.5121951
3433 -149.5365854
3434  677.7804878
3435  463.3414634
3436  559.6341463
3437   46.4146341
3438 -453.4390244
3439  685.5365854
3440  457.9268293
3441   25.9756098
3442  132.2682927
3443 -117.3902439
3444  673.2926829
3445  594.5609756
3446 -314.8536585
3447 -565.0487805
3448  -21.0000000
3449 -536.1219512
3450  502.8536585
3451 -129.9756098
3452 -245.8292683
3453   57.6829268
3454   34.1219512
3455  552.3170732
3456  -54.5609756
3457 -593.2926829
3458 -593.8780488
3459  484.7560976
3460 -564.2682927
3461 -662.5121951
3462 -181.8292683
3463 -162.8536585
3464 -314.8536585
3465 -102.6097561
3466 -487.0000000
3467  335.5365854
3468   46.8536585
3469  185.0975610
3470 -672.7560976
3471 -161.6341463
3472  -18.7073171
3473 -217.6341463
3474  636.2195122
3475  -92.4146341
3476  142.6097561
3477  306.2195122
3478 -215.3902439
3479 -354.1219512
3480 -531.5365854
3481  763.2926829
3482  783.2439024
3483   86.7560976
3484 -545.2439024
3485   20.9512195
3486  193.3414634
3487  352.2195122
3488  -68.8536585
3489 -636.7560976
3490 -531.6829268
3491  292.6097561
3492  165.5853659
3493 -535.8780488
3494 -678.9024390
3495  266.7560976
3496  442.6097561
3497 -288.7560976
3498  418.1219512
3499  220.4146341
3500   25.2926829
3501  -66.0731707
3502  683.3902439
3503  582.3170732
3504  725.0487805
3505  365.0975610
3506  242.0731707
3507   55.9756098
3508 -515.9756098
3509 -255.5365854
3510 -516.5121951
3511   43.4390244
3512 -644.9512195
3513 -381.2926829
3514   51.1951220
3515 -490.3170732
3516   -5.3902439
3517   79.9268293
3518  372.9024390
3519  263.8780488
3520   86.8536585
3521 -454.4146341
3522 -441.1951220
3523 -210.6585366
3524 -114.5121951
3525 -151.0975610
3526  -53.0975610
3527 -108.7073171
3528 -139.5365854
3529 -357.2439024
3530  610.8536585
3531  699.4878049
3532  864.2195122
3533 -150.8048780
3534  882.7560976
3535 -501.4390244
3536  -12.7073171
3537  282.6585366
3538  -78.3658537
3539   -5.0975610
3540  -18.2682927
3541  390.0243902
3542 -601.7317073
3543  166.1219512
3544  481.2926829
3545   -1.1951220
3546 -135.1463415
3547  -28.3170732
3548 -390.4146341
3549  622.1219512
3550   16.5121951
3551   72.8048780
3552   18.2682927
3553 -651.0000000
3554 -436.8536585
3555   73.8292683
3556  404.4634146
3557   17.1951220
3558  194.2682927
3559   -4.1219512
3560  385.8292683
3561 -678.9512195
3562 -672.4634146
3563  464.8536585
3564 -586.3658537
3565 -551.7317073
3566 -425.1951220
3567   52.3658537
3568  513.7317073
3569 -669.2439024
3570 -312.2682927
3571  113.3902439
3572  -83.4878049
3573  -31.3902439
3574 -128.1219512
3575   14.0731707
3576 -429.2439024
3577  627.8780488
3578 -189.8780488
3579  524.4146341
3580  -99.7804878
3581 -615.1463415
3582  -90.1707317
3583 -736.8048780
3584  413.8292683
3585    7.6341463
3586 -154.1219512
3587  246.5121951
3588 -327.0975610
3589  101.1951220
3590  687.5365854
3591 -464.1219512
3592 -308.1707317
3593  548.9512195
3594   75.2926829
3595  186.6585366
3596   33.6829268
3597  729.5365854
3598  -55.0000000
3599 -294.4146341
3600  -53.7317073
3601  143.0487805
3602 -258.5609756
3603   33.3902439
3604  -33.1463415
3605 -470.6097561
3606 -554.4146341
3607   52.1707317
3608   31.6341463
3609    2.3658537
3610 -758.8536585
3611  457.7804878
3612  175.6341463
3613  -68.8048780
3614  346.5121951
3615 -574.1219512
3616 -124.8048780
3617 -384.4146341
3618  588.3658537
3619  765.2926829
3620  -15.9756098
3621  217.3414634
3622  534.1219512
3623 -127.1951220
3624  605.5853659
3625 -739.8780488
3626   78.7560976
3627 -603.0487805
3628   91.9756098
3629 -627.1463415
3630  262.5609756
3631   -2.3658537
3632   55.0000000
3633  622.9024390
3634 -675.1463415
3635  327.7804878
3636  554.5609756
3637  -51.9268293
3638 -368.5121951
3639  396.8048780
3640  413.0487805
3641  -43.0975610
3642  132.0243902
3643  -53.3414634
3644 -172.3658537
3645   45.2926829
3646   77.0487805
3647 -245.5853659
3648 -458.6097561
3649   55.0487805
3650 -104.8048780
3651  652.6097561
3652  -80.6585366
3653 -162.9024390
3654  126.3170732
3655 -483.7317073
3656  750.1219512
3657 -101.5365854
3658  243.9756098
3659  561.4878049
3660  -39.5365854
3661  423.1951220
3662  239.6829268
3663  235.8292683
3664  226.9024390
3665  400.3170732
3666 -663.4878049
3667   19.1951220
3668  245.0000000
3669  259.7317073
3670   48.7073171
3671 -750.0243902
3672  -58.4634146
3673 -606.9512195
3674  150.4146341
3675  333.1951220
3676   42.0243902
3677   44.4146341
3678  102.8048780
3679  648.6097561
3680 -285.8292683
3681  739.3414634
3682  618.7073171
3683  305.7804878
3684  595.6829268
3685 -221.5365854
3686 -551.4878049
3687 -402.8536585
3688 -108.6585366
3689 -602.9512195
3690  264.4634146
3691  201.6341463
3692 -772.4146341
3693 -218.6585366
3694  203.5365854
3695  243.8292683
3696   53.0487805
3697  562.7560976
3698 -525.9756098
3699   23.4878049
3700  702.5121951
3701  569.2439024
3702  127.6341463
3703 -449.0000000
3704  155.4878049
3705  143.0000000
3706  108.9024390
3707    0.1707317
3708  679.7804878
3709  203.6829268
3710  706.4146341
3711   37.8780488
3712 -345.8292683
3713  333.9756098
3714  141.4390244
3715 -100.0731707
3716 -455.0000000
3717 -410.9024390
3718 -496.0731707
3719 -300.9512195
3720  548.5609756
3721  107.3902439
3722 -315.8780488
3723 -420.2682927
3724  162.7073171
3725 -591.7804878
3726  -18.4634146
3727 -492.6585366
3728  342.2682927
3729 -721.3902439
3730  -17.2439024
3731  564.3658537
3732  751.8292683
3733   48.4146341
3734   80.0731707
3735 -564.1707317
3736  655.7317073
3737 -506.2682927
3738  139.0000000
3739  414.9512195
3740   17.6341463
3741 -540.8048780
3742  -48.4146341
3743    5.5365854
3744   95.2926829
3745 -547.1951220
3746  426.0731707
3747  151.5365854
3748  521.9756098
3749 -371.9268293
3750 -429.2926829
3751  -41.5365854
3752  379.2439024
3753 -740.9024390
3754  455.7804878
3755  505.0000000
3756  -70.7560976
3757  -44.2195122
3758 -363.0975610
3759 -135.6829268
3760 -536.1219512
3761  291.8780488
3762   86.0731707
3763  135.4878049
3764 -648.8536585
3765  185.2926829
3766  -42.3170732
3767 -639.7317073
3768  -67.6829268
3769  -29.2926829
3770    6.1707317
3771  159.6829268
3772   45.0000000
3773   53.3414634
3774 -579.7804878
3775 -667.4390244
3776  648.8048780
3777  391.0975610
3778  586.0243902
3779 -233.5853659
3780  622.2682927
3781 -158.7560976
3782 -525.5365854
3783  166.9512195
3784   85.7804878
3785  726.3658537
3786  431.6829268
3787  221.4390244
3788 -733.1463415
3789  453.0487805
3790 -467.8780488
3791 -138.6585366
3792  -33.8780488
3793  402.0243902
3794 -191.0975610
3795  -41.0000000
3796 -306.1707317
3797  -10.1219512
3798 -576.3658537
3799 -631.0975610
3800  150.9512195
3801  -56.8048780
3802 -191.8780488
3803   -7.6829268
3804 -150.0731707
3805   49.6341463
3806 -171.6341463
3807   13.3414634
3808 -650.9512195
3809 -645.1463415
3810  355.2439024
3811  578.6097561
3812  200.9512195
3813  -17.9756098
3814   80.4146341
3815 -498.5609756
3816 -277.1951220
3817   19.7804878
3818 -601.2439024
3819  333.1951220
3820   16.5609756
3821   68.7560976
3822 -433.3902439
3823  -18.5121951
3824  336.2195122
3825  618.4146341
3826  -50.9024390
3827 -147.3414634
3828  695.0000000
3829  148.8048780
3830  133.3414634
3831 -751.0487805
3832  279.4390244
3833 -392.2195122
3834 -206.7073171
3835   78.1219512
3836  -37.7804878
3837 -487.1951220
3838  567.3414634
3839 -162.0731707
3840  -69.3902439
3841 -280.3658537
3842  575.2439024
3843  454.2195122
3844  -10.4634146
3845 -261.8292683
3846 -142.2682927
3847 -436.9512195
3848  -37.2439024
3849  -61.6829268
3850 -417.7804878
3851  781.5853659
3852 -456.5121951
3853  -29.0000000
3854  394.3658537
3855 -383.0975610
3856 -531.7317073
3857  668.5121951
3858  514.7073171
3859 -626.9024390
3860  280.6097561
3861 -214.0243902
3862  693.4878049
3863  553.5853659
3864  538.4146341
3865   99.5853659
3866  720.8048780
3867  616.6585366
3868 -141.5853659
3869  -47.2926829
3870 -624.4634146
3871   54.5609756
3872  508.8536585
3873 -482.1219512
3874  116.2682927
3875 -200.9024390
3876  291.0000000
3877   43.1951220
3878  769.8780488
3879 -492.3170732
3880   71.1463415
3881  182.2195122
3882  552.9024390
3883  534.5609756
3884   54.9512195
3885 -164.9512195
3886 -118.2682927
3887  591.1951220
3888 -434.3658537
3889    8.0243902
3890 -229.1951220
3891 -662.4146341
3892  -50.9024390
3893 -171.2926829
3894  -60.1219512
3895 -702.5121951
3896 -200.1707317
3897  106.1219512
3898  121.8292683
3899 -640.1219512
3900  -19.2439024
3901   65.7804878
3902   30.4634146
3903  -10.3170732
3904  221.2439024
3905 -756.5609756
3906 -512.4634146
3907   54.2195122
3908  467.3414634
3909 -618.4634146
3910    3.1463415
3911  281.4878049
3912   35.7317073
3913  135.3414634
3914  155.2926829
3915   90.8048780
3916  452.2195122
3917  440.8536585
3918 -231.0487805
3919  547.0000000
3920  109.3414634
3921  245.9268293
3922   72.1219512
3923 -350.9024390
3924   78.5121951
3925  571.6341463
3926  150.1707317
3927 -136.3170732
3928  525.9268293
3929 -440.5121951
3930 -636.2195122
3931 -595.8780488
3932 -182.9024390
3933   14.2682927
3934 -382.8536585
3935  487.7804878
3936 -336.9512195
3937  671.2926829
3938 -105.0000000
3939 -597.1951220
3940   38.4146341
3941 -275.4390244
3942 -675.6829268
3943 -275.8292683
3944  515.5853659
3945  100.1219512
3946  448.4146341
3947  462.3658537
3948  613.0000000
3949 -270.1219512
3950 -527.1463415
3951 -131.1463415
3952 -104.0243902
3953  -43.1463415
3954  107.8292683
3955  -67.1463415
3956   92.9512195
3957  772.0243902
3958  257.0487805
3959   62.7560976
3960  496.6585366
3961 -124.0243902
3962   47.4390244
3963 -272.7073171
3964  800.9512195
3965 -600.9512195
3966  313.3414634
3967  578.1219512
3968  630.6585366
3969  175.6829268
3970  319.4878049
3971  333.9268293
3972    8.8536585
3973   32.0243902
3974   24.8048780
3975  292.7073171
3976 -590.3658537
3977 -226.3658537
3978 -169.2439024
3979  187.2926829
3980   -9.2926829
3981 -286.8048780
3982  676.3170732
3983  103.8292683
3984 -117.9756098
3985 -235.3414634
3986  265.4390244
3987    7.1463415
3988  -15.0487805
3989  856.5609756
3990  -67.7804878
3991  -27.6341463
3992  137.0487805
3993  114.1707317
3994   26.7073171
3995  -42.9024390
3996 -659.5365854
3997   66.2195122
3998  587.2439024
3999  109.7804878
4000 -451.0000000
4001  773.6341463
4002  -25.8292683
4003  331.1463415
4004 -301.4878049
4005   83.7804878
4006   34.2682927
4007  -16.4634146
4008 -136.4634146
4009  720.7560976
4010   84.8536585
4011 -384.3658537
4012   65.6341463
4013  640.7560976
4014   41.3414634
4015   28.1707317
4016    5.6829268
4017 -627.9756098
4018 -792.0731707
4019 -209.7804878
4020 -679.5365854
4021  256.3658537
4022   78.3658537
4023 -865.0000000
4024  123.2926829
4025 -245.1951220
4026  283.5365854
4027  599.2439024
4028 -219.4878049
4029 -482.5121951
4030 -123.4390244
4031  209.5365854
4032 -667.3902439
4033   54.5121951
4034  149.5365854
4035  452.9512195
4036 -310.3170732
4037   60.8536585
4038 -772.1707317
4039  343.4878049
4040 -248.5609756
4041  680.6097561
4042  457.6341463
4043  439.5853659
4044 -785.9268293
4045 -682.6097561
4046 -126.3658537
4047 -318.9024390
4048  616.4146341
4049   68.9024390
4050  431.1951220
4051   30.6585366
4052 -702.3170732
4053 -432.5609756
4054 -509.7804878
4055 -203.2439024
4056  579.4878049
4057  -10.1707317
4058 -707.3902439
4059  168.6585366
4060  661.8292683
4061  702.4146341
4062  190.9024390
4063 -739.5365854
4064  514.1707317
4065  -30.6585366
4066  403.4390244
4067  -81.3414634
4068 -775.8292683
4069 -529.0000000
4070  430.3658537
4071  105.1951220
4072 -576.9512195
4073  643.8292683
4074 -291.9268293
4075  451.0975610
4076  -26.4634146
4077 -501.4878049
4078  121.7804878
4079  304.2195122
4080  566.1707317
4081  -20.1707317
4082  274.1707317
4083 -150.7073171
4084 -450.0243902
4085 -661.0487805
4086  244.3658537
4087 -477.8292683
4088  -92.3658537
4089 -219.5365854
4090  601.9268293
4091 -481.0000000
4092 -422.1219512
4093  223.0487805
4094  525.4390244
4095  243.0975610
4096 -353.6341463
4097 -345.2926829
4098  379.0975610
4099 -629.3414634
4100  182.1219512
4101 -161.6829268
4102  463.8780488
4103 -135.1463415
4104 -588.5609756
4105 -393.7804878
4106  -61.0000000
4107  453.4390244
4108 -704.9024390
4109  -13.4878049
4110  -29.5853659
4111  404.5609756
4112    1.1951220
4113  702.0731707
4114 -660.9512195
4115  492.8048780
4116  682.2195122
4117    8.8536585
4118 -547.0000000
4119   82.5121951
4120   37.1463415
4121 -838.4146341
4122  458.6585366
4123  -44.3658537
4124 -143.0487805
4125  180.6097561
4126  164.7560976
4127  537.5365854
4128 -733.3414634
4129  605.0000000
4130 -687.2439024
4131 -528.9024390
4132 -108.0243902
4133 -507.6341463
4134  701.3414634
4135  282.7560976
4136  581.7317073
4137  581.5853659
4138 -275.0487805
4139 -456.0731707
4140  583.0000000
4141   45.9268293
4142  -12.5609756
4143 -369.7804878
4144  164.9024390
4145  220.0243902
4146  105.0000000
4147  349.4878049
4148  105.5365854
4149  709.8292683
4150  447.8292683
4151 -386.2195122
4152  425.9268293
4153 -199.0975610
4154   28.7073171
4155 -750.3658537
4156   79.6341463
4157  428.9024390
4158  777.0000000
4159  -93.2926829
4160  642.3170732
4161  741.5365854
4162   19.4390244
4163  590.4634146
4164 -692.6097561
4165  731.3902439
4166  332.2682927
4167   -7.8292683
4168  556.2682927
4169 -193.3902439
4170  -35.5365854
4171   -2.6097561
4172 -205.3902439
4173 -759.2439024
4174  104.7560976
4175 -426.5609756
4176 -333.2439024
4177 -159.3414634
4178 -466.5609756
4179   58.1219512
4180   82.5121951
4181  -79.5365854
4182  426.3170732
4183 -133.8292683
4184  621.3902439
4185 -218.3658537
4186 -596.3170732
4187 -291.9756098
4188 -772.2195122
4189  596.2195122
4190  570.9024390
4191  129.8780488
4192 -199.0000000
4193 -160.4634146
4194 -393.2439024
4195 -292.8536585
4196  528.4634146
4197  669.3902439
4198   44.4146341
4199  261.0487805
4200  555.1951220
4201  -22.5121951
4202 -603.4390244
4203 -371.6829268
4204 -278.5609756
4205   63.1951220
4206 -126.7560976
4207   30.3658537
4208  -68.0731707
4209  -19.5853659
4210  -36.9024390
4211    1.6829268
4212  517.7317073
4213  -19.0975610
4214   37.4878049
4215  210.3170732
4216  189.2926829
4217  314.2195122
4218  732.9512195
4219   -4.3170732
4220  196.8536585
4221 -490.9512195
4222 -137.0487805
4223 -721.2439024
4224   26.6585366
4225  -27.0487805
4226 -218.6585366
4227  491.9756098
4228 -624.0731707
4229  352.8536585
4230  325.0000000
4231  642.5121951
4232 -509.2926829
4233  626.9512195
4234  319.7317073
4235  552.8048780
4236  488.4634146
4237   72.2682927
4238 -175.7317073
4239 -514.1707317
4240 -812.4146341
4241  112.4146341
4242  530.9024390
4243 -159.5365854
4244 -118.7560976
4245 -110.8048780
4246  162.6097561
4247  519.1951220
4248  175.3902439
4249   -7.0487805
4250   81.9268293
4251 -514.9512195
4252 -355.6829268
4253 -632.3170732
4254  634.9512195
4255 -732.1707317
4256  492.5609756
4257  256.0731707
4258  602.3658537
4259   65.7317073
4260  699.6341463
4261   12.1707317
4262  629.2926829
4263 -133.0000000
4264  579.2926829
4265  145.1463415
4266 -309.1463415
4267  -70.6097561
4268  -66.2682927
4269  -47.7804878
4270  474.7073171
4271 -147.8780488
4272   13.0000000
4273 -349.6341463
4274 -470.7073171
4275  208.6097561
4276  517.1951220
4277 -673.8292683
4278 -807.3902439
4279  713.8780488
4280  226.6097561
4281 -162.1219512
4282  -92.6097561
4283 -578.8536585
4284 -712.1707317
4285  519.2926829
4286 -741.4390244
4287   86.6097561
4288  234.4634146
4289 -419.1463415
4290 -302.2682927
4291 -489.2926829
4292 -337.1951220
4293  469.2439024
4294 -335.1951220
4295 -111.2439024
4296  532.3658537
4297  187.5365854
4298  111.0487805
4299  -31.4390244
4300 -581.3902439
4301  159.8780488
4302   99.0000000
4303  688.1707317
4304  -24.0243902
4305  501.0000000
4306 -120.8536585
4307  199.4878049
4308  -40.4146341
4309 -120.2682927
4310    7.4390244
4311 -567.4390244
4312  -95.5853659
4313   44.2195122
4314  -26.4146341
4315  407.2926829
4316 -195.7317073
4317  -92.1707317
4318 -515.8292683
4319 -360.0731707
4320 -377.5853659
4321  480.2195122
4322  -60.0731707
4323  540.9512195
4324   13.4878049
4325  801.3902439
4326  -74.7560976
4327 -645.3902439
4328  430.1707317
4329 -637.0000000
4330 -433.1463415
4331 -518.6097561
4332   30.4146341
4333  277.6829268
4334  231.0975610
4335 -371.6341463
4336  420.5609756
4337  -45.3902439
4338 -745.1463415
4339   26.2195122
4340   68.4146341
4341  677.8292683
4342   31.9268293
4343 -317.6829268
4344 -711.8780488
4345   39.9756098
4346  110.1707317
4347 -650.3658537
4348  354.0731707
4349  582.7073171
4350   51.1951220
4351  493.1951220
4352  115.0487805
4353 -637.2439024
4354  820.6585366
4355  351.7804878
4356   91.3902439
4357   81.0000000
4358  426.0731707
4359    4.4146341
4360  251.2439024
4361  793.5853659
4362 -473.5853659
4363 -631.1463415
4364 -687.3902439
4365 -133.2926829
4366   14.8048780
4367  765.5853659
4368 -421.2926829
4369 -680.2682927
4370  785.7317073
4371 -120.5121951
4372  588.7560976
4373 -167.7804878
4374 -142.4146341
4375  635.6341463
4376  602.2195122
4377  567.6341463
4378  -29.4878049
4379 -187.2439024
4380   55.0000000
4381 -689.8780488
4382  560.3658537
4383  497.7804878
4384 -567.0487805
4385   43.0487805
4386 -642.2682927
4387 -433.5365854
4388   67.2439024
4389  669.0975610
4390  378.3658537
4391   97.3902439
4392 -339.5853659
4393 -504.3658537
4394  -78.8536585
4395  119.4878049
4396   42.6097561
4397   51.0487805
4398 -261.0975610
4399 -786.4146341
4400  -10.8048780
4401  -66.2195122
4402  290.7073171
4403  163.3414634
4404 -493.9756098
4405  -65.0000000
4406   44.1707317
4407  747.0975610
4408  634.3170732
4409  450.6585366
4410  653.6829268
4411  555.2439024
4412 -456.2195122
4413  -84.3658537
4414 -685.7317073
4415  644.4634146
4416  -70.3658537
4417 -376.0243902
4418  594.9512195
4419  -29.6341463
4420  495.7317073
4421  -86.7560976
4422    4.7560976
4423  516.0731707
4424 -240.2682927
4425  370.7560976
4426  136.5609756
4427 -497.0000000
4428  186.4146341
4429  786.6097561
4430 -535.0487805
4431  773.3902439
4432  190.8048780
4433  207.4390244
4434 -194.3658537
4435 -193.0975610
4436  225.3902439
4437  332.9024390
4438 -416.4634146
4439   17.5365854
4440  349.5853659
4441   84.5121951
4442  157.9268293
4443  125.3414634
4444 -528.3658537
4445   88.6097561
4446  -21.0975610
4447  -32.0731707
4448  600.4146341
4449   41.3414634
4450  433.5853659
4451  606.3658537
4452 -518.4146341
4453 -275.6341463
4454  -13.3414634
4455 -371.5365854
4456 -595.2926829
4457  129.4878049
4458  533.8780488
4459 -830.2195122
4460 -469.1463415
4461  -84.9024390
4462  -78.2195122
4463   17.9268293
4464   92.2682927
4465  127.8292683
4466  -36.0243902
4467 -833.1463415
4468  250.2682927
4469  301.6341463
4470   10.7073171
4471  325.1951220
4472   81.7317073
4473  511.2926829
4474  115.6341463
4475  186.6585366
4476 -246.5121951
4477 -346.7560976
4478  -17.6341463
4479  162.3658537
4480  341.8780488
4481  499.4878049
4482 -126.0243902
4483 -460.7073171
4484 -138.3170732
4485  421.6341463
4486 -633.0000000
4487   70.6097561
4488  324.7073171
4489  180.2195122
4490  433.9756098
4491    9.5853659
4492    5.9268293
4493   73.9268293
4494  668.0243902
4495  -40.2682927
4496 -413.3902439
4497   59.1463415
4498  -63.0487805
4499 -206.5609756
4500 -671.0000000
4501 -301.8780488
4502  206.8048780
4503  579.9756098
4504 -295.1463415
4505    1.7804878
4506  635.7804878
4507 -684.0731707
4508  523.4390244
4509  249.4390244
4510 -289.1951220
4511 -352.0243902
4512  164.3658537
4513 -463.3414634
4514 -503.0000000
4515   21.5853659
4516   41.2926829
4517  249.4878049
4518   77.4390244
4519 -605.5853659
4520   10.0731707
4521 -625.0487805
4522  196.2682927
4523  123.9268293
4524 -139.8292683
4525 -684.5121951
4526   96.1219512
4527 -164.0243902
4528    3.0487805
4529 -337.9756098
4530   23.4390244
4531  162.0243902
4532 -356.3170732
4533  292.4146341
4534   -4.9024390
4535 -155.3902439
4536 -328.4146341
4537  454.2682927
4538  139.9268293
4539 -287.8780488
4540 -200.6585366
4541 -618.2195122
4542 -609.6341463
4543 -400.1219512
4544  111.3414634
4545  150.6585366
4546  636.6585366
4547 -408.8048780
4548  655.0000000
4549 -250.8048780
4550   91.0000000
4551  -17.3902439
4552 -746.1219512
4553   18.2682927
4554  625.1951220
4555 -295.1463415
4556   94.8536585
4557 -273.6341463
4558 -187.7317073
4559 -116.4146341
4560  -22.8048780
4561 -531.7317073
4562    7.1463415
4563 -639.5853659
4564  223.3902439
4565  -61.4390244
4566  162.4146341
4567   87.7804878
4568  385.8292683
4569  315.5853659
4570  743.6341463
4571   -7.2439024
4572  116.3658537
4573  271.0000000
4574  465.2439024
4575 -151.3902439
4576   12.0243902
4577  -65.3414634
4578 -713.4390244
4579 -170.6585366
4580  258.1707317
4581  112.9512195
4582  -17.1463415
4583 -235.6341463
4584  627.8292683
4585  660.7560976
4586   78.8048780
4587  705.1951220
4588 -237.6341463
4589   20.0243902
4590 -453.1463415
4591  203.8780488
4592 -182.9512195
4593 -540.2682927
4594  195.2439024
4595 -132.0731707
4596   92.7073171
4597  582.7560976
4598  -88.8536585
4599 -576.2195122
4600  357.0000000
4601 -597.0000000
4602 -471.4878049
4603 -565.1951220
4604 -754.4634146
4605   57.2926829
4606 -509.9268293
4607 -194.7560976
4608 -154.1219512
4609 -464.7073171
4610   71.9756098
4611  -91.0000000
4612  129.2926829
4613 -120.3658537
4614  499.6829268
4615  -70.2682927
4616 -113.4390244
4617  496.0243902
4618  560.3658537
4619  -82.1219512
4620  531.1463415
4621 -165.6829268
4622  135.7317073
4623 -265.0000000
4624 -102.1707317
4625 -467.8780488
4626 -796.9024390
4627  188.3170732
4628 -176.8048780
4629  588.0243902
4630  643.4390244
4631  -28.7073171
4632 -662.3658537
4633 -144.0243902
4634 -772.1707317
4635 -160.9512195
4636  588.8048780
4637 -104.0243902
4638  -35.9756098
4639    4.2682927
4640  336.2682927
4641 -605.3902439
4642 -611.5365854
4643  632.3658537
4644  -27.2439024
4645 -303.2926829
4646 -131.9268293
4647   29.1463415
4648 -621.1463415
4649   -8.4146341
4650 -379.0487805
4651 -138.5121951
4652   -1.0975610
4653  -27.2926829
4654  269.8780488
4655 -419.8780488
4656  523.0000000
4657  675.7804878
4658  571.0000000
4659  413.8292683
4660 -724.4146341
4661  -30.7073171
4662 -205.9756098
4663  569.2439024
4664  758.9024390
4665    7.6829268
4666 -114.4634146
4667 -478.0731707
4668  366.1707317
4669  713.6829268
4670   69.1463415
4671   86.7073171
4672   -7.1463415
4673  596.3170732
4674 -354.0731707
4675 -555.6829268
4676 -140.6097561
4677  167.8292683
4678  619.7804878
4679 -705.6829268
4680  684.7560976
4681  546.6585366
4682 -254.0731707
4683  419.2926829
4684  -85.7804878
4685   60.5121951
4686 -228.4634146
4687  482.9512195
4688  448.9024390
4689 -588.6585366
4690  377.5853659
4691  403.6829268
4692 -312.2195122
4693 -266.4146341
4694  133.6829268
4695 -348.1219512
4696   70.0243902
4697  -72.3170732
4698  534.0731707
4699  733.8780488
4700   24.8536585
4701   26.5609756
4702  673.3902439
4703   15.6829268
4704  560.2195122
4705 -177.1951220
4706 -148.5609756
4707  654.4634146
4708 -157.8780488
4709  473.3414634
4710 -451.7804878
4711  305.5365854
4712 -118.1707317
4713 -515.7804878
4714   21.9268293
4715  602.6585366
4716 -588.1707317
4717   19.1463415
4718 -208.0731707
4719 -405.4390244
4720 -180.0243902
4721 -266.1707317
4722  308.2195122
4723   38.3170732
4724 -562.9024390
4725 -123.9756098
4726  520.8048780
4727 -553.3414634
4728  548.4146341
4729  836.2195122
4730 -347.6341463
4731  643.4878049
4732 -674.6097561
4733 -386.2195122
4734  -69.5365854
4735 -518.6585366
4736   98.1219512
4737   42.2682927
4738  563.1463415
4739  142.6097561
4740  -37.7804878
4741  -71.2926829
4742 -676.4146341
4743  696.6097561
4744 -539.8292683
4745  -99.7804878
4746  181.0975610
4747  -12.6585366
4748   30.8048780
4749 -177.3902439
4750  590.8536585
4751  715.3414634
4752   36.8048780
4753 -567.5853659
4754 -686.6097561
4755  750.1219512
4756 -273.7317073
4757  -73.3414634
4758 -659.5365854
4759  152.8048780
4760  867.3902439
4761  561.7317073
4762  322.5121951
4763 -158.5121951
4764  197.2439024
4765 -566.6585366
4766  219.6829268
4767  437.5365854
4768 -224.8536585
4769  -82.2195122
4770  -48.5609756
4771 -711.1463415
4772  163.7317073
4773  192.5121951
4774    2.6585366
4775 -125.9756098
4776  -53.5365854
4777 -347.8292683
4778 -441.7804878
4779  -46.0731707
4780 -108.8536585
4781  566.4146341
4782 -237.7804878
4783 -426.6097561
4784  -60.4146341
4785  619.6341463
4786   52.4146341
4787 -317.2439024
4788 -644.4634146
4789 -126.9024390
4790 -527.1463415
4791 -384.2195122
4792   41.3414634
4793  663.7317073
4794  785.4390244
4795   49.4390244
4796  158.3170732
4797  -36.3170732
4798 -154.7560976
4799 -506.0243902
4800   14.1219512
4801   10.7560976
4802 -445.9268293
4803  114.0731707
4804  227.9268293
4805  -29.7317073
4806  -95.9756098
4807  639.9756098
4808  495.0487805
4809  161.1463415
4810  414.5609756
4811  526.6097561
4812 -485.2926829
4813 -726.8048780
4814  378.7073171
4815 -177.0487805
4816 -110.6585366
4817 -619.6341463
4818   66.0731707
4819  -76.6097561
4820  335.9268293
4821  271.2926829
4822  487.4390244
4823  553.7317073
4824 -142.0243902
4825  495.3414634
4826  118.4634146
4827  792.8536585
4828   94.7073171
4829 -167.9268293
4830    6.7560976
4831 -121.4390244
4832  129.0975610
4833  104.8048780
4834 -102.8048780
4835 -280.9024390
4836 -575.5853659
4837 -374.4634146
4838 -187.0975610
4839 -542.0731707
4840 -506.0731707
4841  113.8780488
4842 -624.4146341
4843  211.8780488
4844 -306.7073171
4845  -18.1219512
4846 -526.4146341
4847 -737.2926829
4848 -622.0243902
4849 -167.0000000
4850 -592.1707317
4851 -129.3902439
4852 -423.9268293
4853   19.5365854
4854 -511.7804878
4855  538.8536585
4856   81.5365854
4857   50.0243902
4858  614.3658537
4859  515.4390244
4860  598.3170732
4861  144.0243902
4862 -613.4878049
4863 -144.0731707
4864  427.9756098
4865    8.4146341
4866   -8.3658537
4867  129.6829268
4868  -75.6341463
4869 -122.8536585
4870 -429.3414634
4871 -447.6341463
4872  600.7560976
4873  343.2439024
4874 -123.2926829
4875  109.0000000
4876  -59.3414634
4877  354.3170732
4878  577.0000000
4879 -761.1463415
4880 -237.3414634
4881  132.3658537
4882 -529.2439024
4883 -627.7317073
4884   94.6097561
4885   -1.8292683
4886 -155.8780488
4887  402.2682927
4888  443.1463415
4889  490.5121951
4890 -375.6829268
4891  -14.8048780
4892   87.5853659
4893 -467.2439024
4894   45.0487805
4895  715.7317073
4896 -606.3170732
4897  785.3902439
4898  -54.6097561
4899  535.9268293
4900  -39.5365854
4901  118.2682927
4902  579.0487805
4903  455.1951220
4904  726.5121951
4905 -366.4146341
4906  742.6585366
4907  -66.8048780
4908  539.0000000
4909 -507.9268293
4910 -800.9512195
4911  321.2926829
4912 -800.7073171
4913  -49.5853659
4914   14.1707317
4915  -31.1463415
4916 -326.9512195
4917  -18.4146341
4918  483.6341463
4919  382.9024390
4920  -51.4878049
4921 -120.2682927
4922  240.5121951
4923  201.1951220
4924 -579.7317073
4925 -526.4146341
4926 -429.6829268
4927 -644.6585366
4928   47.1951220
4929  297.0487805
4930 -380.8536585
4931 -273.5365854
4932 -374.1219512
4933  256.6097561
4934  632.3170732
4935  552.9024390
4936 -373.6829268
4937 -535.6829268
4938   90.4634146
4939  781.4390244
4940   19.5365854
4941  -63.5853659
4942 -401.7804878
4943 -472.8048780
4944  -79.2439024
4945  -48.8048780
4946 -472.9024390
4947   19.2439024
4948 -671.5365854
4949  -61.5853659
4950 -344.9512195
4951   76.6097561
4952   26.6585366
4953   32.2195122
4954  647.1951220
4955  212.0731707
4956   66.3658537
4957 -514.3658537
4958  -34.2195122
4959 -187.8780488
4960 -293.9756098
4961  627.5365854
4962 -639.5365854
4963  587.0000000
4964   31.7317073
4965    3.5853659
4966  728.6097561
4967   29.0000000
4968  474.0731707
4969  -88.2195122
4970   -0.1707317
4971  -62.4146341
4972  532.5609756
4973  748.6097561
4974 -102.9024390
4975  415.9268293
4976  -52.8536585
4977  725.6341463
4978  -69.4878049
4979 -701.2926829
4980 -108.8536585
4981 -236.9512195
4982  -90.8536585
4983 -295.5365854
4984 -693.0000000
4985  -81.7804878
4986 -520.2195122
4987 -345.7317073
4988 -758.5609756
4989 -421.8292683
4990 -420.3658537
4991 -371.5365854
4992  630.9024390
4993 -466.9024390
4994 -374.5609756
4995 -556.6097561
4996 -264.0243902
4997 -678.7073171
4998 -256.6097561
4999   18.3658537</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>obs_diff_moneyspent <span class="ot">&lt;-</span> <span class="fu">diffmean</span>(Money_spent <span class="sc">~</span> Gender, <span class="at">data =</span> pmoney_modified) </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>obs_diff_moneyspent</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> diffmean 
-55.29268 </code></pre>
</div>
</div>
<ul>
<li>Difference between the mean of money spent in females and males is 55.29</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_moneyspent, <span class="sc">~</span> diffmean, <span class="at">bins =</span> <span class="dv">25</span>) <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_moneyspent, </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>,</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">"Null Distribution by Permutation"</span>, </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">subtitle =</span> <span class="st">"Histogram"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">x =</span> <span class="st">"Difference in Means"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="do">###</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_ecdf</span>(<span class="at">data =</span> null_dist_moneyspent, <span class="sc">~</span> diffmean, </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_moneyspent, </span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">"Null Distribution by Permutation"</span>, </span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">subtitle =</span> <span class="st">"Cumulative Density"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">x =</span> <span class="st">"Difference in Means"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="inference-6" class="level3">
<h3 class="anchored" data-anchor-id="inference-6">Inference</h3>
<ul>
<li><p>The red line in the graph represents the observed difference in means of the two categories (i.e, -55.29)</p></li>
<li><p>the histogram represents the null distribution from the permutation tests</p></li>
<li><p>Since the red line falls within the central range of the null distribution, we can assume that the difference was due to random chance</p></li>
<li><p>This tells us that the difference between money spent by male and female is not statistically significant</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">prop1</span>(<span class="sc">~</span> diffmean <span class="sc">&lt;=</span> obs_diff_moneyspent, <span class="at">data =</span> null_dist_moneyspent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>prop_TRUE 
   0.5552 </code></pre>
</div>
</div>
<ul>
<li><p>There is a 56.4% chance that a difference in means equal to or greater than obs_diff_moneyspent could occur under the null hypothesis.</p></li>
<li><p>since the p-value is higher than 0.05, the observed difference is statistically insignificant, and we cannot reject the null hypothesis</p></li>
</ul>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>From our data we can say males on average spend more than women though it is not a significant amount</p>
<p>There is no significant difference between the spending habits of males and females</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>