{
  "hash": "8cab49cd31d42b7f7825ea6dc7065445",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Pocket Money\"\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: scales\n\nAttaching package: 'scales'\n\nThe following object is masked from 'package:purrr':\n\n    discard\n\nThe following object is masked from 'package:readr':\n\n    col_factor\n\nLoading required package: ggridges\n\nNew to ggformula?  Try the tutorials: \n\tlearnr::run_tutorial(\"introduction\", package = \"ggformula\")\n\tlearnr::run_tutorial(\"refining\", package = \"ggformula\")\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(crosstable)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'crosstable'\n\nThe following object is masked from 'package:purrr':\n\n    compact\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following object is masked from 'package:scales':\n\n    rescale\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npmoney <- read.csv(\"../../data/PocketMoney.csv\")\npmoney\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Sr.no         Name Gender Money_spent\n1      1        Aagam   Male         150\n2      2       Aakash   Male         240\n3      3      Aarushi Female         382\n4      4      Abheeta Female          60\n5      5      Adithya   Male          68\n6      6       Aditya   Male         300\n7      7     Akanksha Female         270\n8      8       Amruta Female         190\n9      9       Anaaya Female         300\n10    10        Anish   Male           0\n11    11       Ankush   Male         250\n12    12      Anousha Female          85\n13    13     Anoushka Female         700\n14    14      Anushka Female         140\n15    15        Arjun   Male        1143\n16    16         Arya   Male         100\n17    17        Aryan   Male       10000\n18    18         Asra Female        1070\n19    19         Aziz   Male        1433\n20    20      Bhumika Female        1200\n21    21        Daana Female          66\n22    22          Dan   Male         600\n23    23    Deborishi   Male         205\n24    24     Devanshi Female         700\n25    25       Dhiman   Male         910\n26    26        Dhruv   Male         900\n27    27        Dhurv   Male         185\n28    28        Eisha Female         300\n29    29      Ezhilan   Male         842\n30    30         Geet   Male          50\n31    31       Harjot Female        3000\n32    32      Janhavi Female         150\n33    33         Jeff   Male         200\n34    34      Jeffrey   Male         150\n35    35      Kalyani Female           0\n36    36       Kartik   Male         145\n37    37       Kashvi Female         430\n38    38       Kavana Female         500\n39    39       Khushi Female         785\n40    40      Koustav   Male         250\n41    41        Krish   Male          70\n42    42     Kshirija Female         100\n43    43       Lekith   Male         100\n44    44       Maahin   Male         310\n45    45       Maanya Female          15\n46    46       Madhav   Male        4000\n47    47        Manav   Male          40\n48    48      Nandana Female           0\n49    49        Navya Female          55\n50    50    Nayantara Female         192\n51    51        Neeti Female         280\n52    52       Nithya Female          85\n53    53       Nivaan   Male         220\n54    54       Parisa Female          80\n55    55        Rikit   Male         259\n56    56        Risha Female           0\n57    57        Ritik   Male        1000\n58    58       Rudraj   Male         478\n59    59      Rukaiya Female          20\n60    60         Ryan   Male         330\n61    61       Shaivi Female         318\n62    62     Shashank   Male         400\n63    63     Shashwat   Male         149\n64    64        Shiva   Male         250\n65    65       Shreya Female         585\n66    66       Simran Female         340\n67    67 Simran Anand Female         660\n68    68      Snigdha Female         100\n69    69       Suhaas   Male         997\n70    70      Suprita Female         500\n71    71        Sutej   Male           0\n72    72       Tanmay Female         800\n73    73        Tanya Female           0\n74    74        Taran   Male        1399\n75    75       Tarini Female         200\n76    76     Tathastu   Male        1535\n77    77        Vanya Female         350\n78    78        Varad   Male         154\n79    79     Vasantha Female         418\n80    80   Vasundhara Female       13000\n81    81         Veer   Male         566\n82    82        Viraj   Male         315\n```\n\n\n:::\n:::\n\n\n\n\nThis dataset consists of 1 quant and 3 qual variables\n\n### Data Dictionary\n\n-   S.No - Qualitative\n\n-   Name - Qualitative\n\n-   Gender - Qualitative\n\n-   Money_Spent - Quantitative\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npmoney_modified <-pmoney %>% \n  dplyr::mutate(\n    Gender = as_factor(Gender)\n  )\npmoney_modified\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Sr.no         Name Gender Money_spent\n1      1        Aagam   Male         150\n2      2       Aakash   Male         240\n3      3      Aarushi Female         382\n4      4      Abheeta Female          60\n5      5      Adithya   Male          68\n6      6       Aditya   Male         300\n7      7     Akanksha Female         270\n8      8       Amruta Female         190\n9      9       Anaaya Female         300\n10    10        Anish   Male           0\n11    11       Ankush   Male         250\n12    12      Anousha Female          85\n13    13     Anoushka Female         700\n14    14      Anushka Female         140\n15    15        Arjun   Male        1143\n16    16         Arya   Male         100\n17    17        Aryan   Male       10000\n18    18         Asra Female        1070\n19    19         Aziz   Male        1433\n20    20      Bhumika Female        1200\n21    21        Daana Female          66\n22    22          Dan   Male         600\n23    23    Deborishi   Male         205\n24    24     Devanshi Female         700\n25    25       Dhiman   Male         910\n26    26        Dhruv   Male         900\n27    27        Dhurv   Male         185\n28    28        Eisha Female         300\n29    29      Ezhilan   Male         842\n30    30         Geet   Male          50\n31    31       Harjot Female        3000\n32    32      Janhavi Female         150\n33    33         Jeff   Male         200\n34    34      Jeffrey   Male         150\n35    35      Kalyani Female           0\n36    36       Kartik   Male         145\n37    37       Kashvi Female         430\n38    38       Kavana Female         500\n39    39       Khushi Female         785\n40    40      Koustav   Male         250\n41    41        Krish   Male          70\n42    42     Kshirija Female         100\n43    43       Lekith   Male         100\n44    44       Maahin   Male         310\n45    45       Maanya Female          15\n46    46       Madhav   Male        4000\n47    47        Manav   Male          40\n48    48      Nandana Female           0\n49    49        Navya Female          55\n50    50    Nayantara Female         192\n51    51        Neeti Female         280\n52    52       Nithya Female          85\n53    53       Nivaan   Male         220\n54    54       Parisa Female          80\n55    55        Rikit   Male         259\n56    56        Risha Female           0\n57    57        Ritik   Male        1000\n58    58       Rudraj   Male         478\n59    59      Rukaiya Female          20\n60    60         Ryan   Male         330\n61    61       Shaivi Female         318\n62    62     Shashank   Male         400\n63    63     Shashwat   Male         149\n64    64        Shiva   Male         250\n65    65       Shreya Female         585\n66    66       Simran Female         340\n67    67 Simran Anand Female         660\n68    68      Snigdha Female         100\n69    69       Suhaas   Male         997\n70    70      Suprita Female         500\n71    71        Sutej   Male           0\n72    72       Tanmay Female         800\n73    73        Tanya Female           0\n74    74        Taran   Male        1399\n75    75       Tarini Female         200\n76    76     Tathastu   Male        1535\n77    77        Vanya Female         350\n78    78        Varad   Male         154\n79    79     Vasantha Female         418\n80    80   Vasundhara Female       13000\n81    81         Veer   Male         566\n82    82        Viraj   Male         315\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npmoney_modified %>%\n  gf_density(\n    ~ Money_spent,\n    fill = ~ Gender,\n    alpha = 0.5,\n    title = \"Money spent\",\n    subtitle = \"Male vs Female\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\npmoney_modified %>%\n  gf_boxplot(\n    Money_spent ~ Gender,\n    fill = ~ Gender,\n    alpha = 0.5,\n    title = \"Math Anxiety Score Box Plots\",\n    subtitle = \"Boys vs Girls\"\n  ) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-2.png){width=672}\n:::\n\n```{.r .cell-code}\n##\npmoney_modified %>% count(Gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Gender  n\n1   Male 41\n2 Female 41\n```\n\n\n:::\n\n```{.r .cell-code}\npmoney_modified %>% \n  group_by(Gender) %>% \n  summarise(mean = mean(Money_spent))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  Gender  mean\n  <fct>  <dbl>\n1 Male    749.\n2 Female  693.\n```\n\n\n:::\n:::\n\n\n\n\n### Inference\n\n-   Majority of people, men and female included spend around 0 to a few hundreds per day\n\n-   Men seem to spend a little more than women not including outliers\n\n-   There is a pretty big overlap in general in the male and female category\n\n-   The graph is left-skewed with one peak\n\n-   In boxplot, median value is similar in both categories\n\n-   There is more variance in the male category above the median\n\n-   There are few outliers in both categories\n\n-   Mean money spent of male (748.6) is larger than female (693.3)which means on average, males spend more\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(~Money_spent,fill=~\t\nGender,data=pmoney_modified,bins = 100)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\n### Inference\n\n-   most people spend from around 0 to a few hundreds\n\n-   most people spend under 2000 per day expect a few outliers\n\n-   males on average spend slightly more than females\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npmoney_modified %>%\n  gf_density( ~ Money_spent,\n              fill = ~ Gender,\n              alpha = 0.5,\n              title = \"Money spent for males and females\") %>%\n  gf_facet_grid(~ Gender) %>% \n  gf_fitdistr(dist = \"dnorm\") \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\n##\npmoney_modified %>% \n  gf_qqline(~ Money_spent, color = ~ Gender,\n            title = \"Money Spent..is it Normally Distributed?\") %>%\n  gf_qq() %>% \n  gf_facet_wrap(~ Gender)  # independent y-axis\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n\n```{.r .cell-code}\n##\nmale_moneyspent <- pmoney_modified %>% \n  filter(Gender== \"Male\") %>% \n  select(Money_spent)\n##\nfemale_moneyspent <- pmoney_modified %>% \n  filter(Gender== \"Female\") %>% \n  select(Money_spent)\n```\n:::\n\n\n\n\n### Inference\n\n-   both of the graphs are left skewed for both male and female\n\n-   the density curve of both graphs do not align with the normal fit curve which suggests the distribution may not be normal\n\n-   In the qq plot, the dots are close to the normal but do not align perfectly to it, there are also outliers in both categories\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(male_moneyspent$Money_spent)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  male_moneyspent$Money_spent\nW = 0.40726, p-value = 1.136e-11\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(female_moneyspent$Money_spent)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  female_moneyspent$Money_spent\nW = 0.29606, p-value = 8.961e-13\n```\n\n\n:::\n:::\n\n\n\n\n### Inference\n\n-   Since the p-value is less than 0.05 in both categories, it indicates that the data significantly deviates from a normal distribution. This means that the money spent by males and that spent by females are both not normally distributed\n\n## Variance Test\n\nvar.test() is designed to perform an F-test to compare the variances of two groups\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar.test(Money_spent ~ Gender, data = pmoney_modified, \n         conf.int = TRUE, conf.level = 0.95) %>% \n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nMultiple parameters; naming those columns num.df, den.df\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 9\n  estimate num.df den.df statistic p.value conf.low conf.high method alternative\n     <dbl>  <int>  <int>     <dbl>   <dbl>    <dbl>     <dbl> <chr>  <chr>      \n1    0.646     40     40     0.646   0.172    0.345      1.21 F tes… two.sided  \n```\n\n\n:::\n:::\n\n\n\n\n### Inference\n\n-   since the p-value is higher than 0.05, there is not significant difference in variance between the two groups\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf(0.646,40,40)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.126616\n```\n\n\n:::\n:::\n\n\n\n\nThis output indicates that about 64.6% of the area under the F-distribution curve with the specified degrees of freedom lies to the left of this value.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::t_test(Money_spent ~ Gender, data = pmoney_modified) %>% \n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 10\n  estimate estimate1 estimate2 statistic p.value parameter conf.low conf.high\n     <dbl>     <dbl>     <dbl>     <dbl>   <dbl>     <dbl>    <dbl>     <dbl>\n1     55.3      749.      693.     0.136   0.893      76.5    -757.      868.\n# ℹ 2 more variables: method <chr>, alternative <chr>\n```\n\n\n:::\n:::\n\n\n\n\n### Inference\n\n-   Since p value is greater than 0.05, it indicates that there is no significant difference between the groups, which indicates similar money spending behaviour in male and female categories.\n\n-   Thus null hypothesis cannot be rejected\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(Money_spent ~ Gender, data = pmoney_modified, \n            conf.int = TRUE, \n            conf.level = 0.95) %>% \n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot\ncompute exact p-value with ties\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot\ncompute exact confidence intervals with ties\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  estimate statistic p.value conf.low conf.high method               alternative\n     <dbl>     <dbl>   <dbl>    <dbl>     <dbl> <chr>                <chr>      \n1     55.0      936.   0.381    -70.0      180. Wilcoxon rank sum t… two.sided  \n```\n\n\n:::\n:::\n\n\n\n\n-   since p-value is greater than 0.05, there is insufficient evidence to suggest a difference in median money spent between male and female groups\n\n-   the confidence interval shows the range of possible median differences. Since the confidence interval contains 0 within its bounds, this means there is no significant difference between the groups\n\n## Permutation Test\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_dist_moneyspent <- \n  do(4999) * diffmean(data = pmoney_modified, Money_spent ~ shuffle(Gender))\nnull_dist_moneyspent\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         diffmean\n1      37.3902439\n2     -59.3414634\n3     196.9024390\n4     -93.8780488\n5     541.9756098\n6     365.2439024\n7      16.0243902\n8    -569.8780488\n9     -57.3902439\n10   -126.9024390\n11    606.2195122\n12    363.6341463\n13   -650.3170732\n14    495.1951220\n15   -173.5365854\n16    417.2926829\n17   -663.3902439\n18      0.4634146\n19   -607.4390244\n20    154.4634146\n21    302.1219512\n22   -401.0000000\n23   -696.0243902\n24    104.8048780\n25   -252.8536585\n26     29.3414634\n27   -118.7560976\n28     71.3902439\n29    234.0731707\n30   -382.0731707\n31    482.3170732\n32   -735.3414634\n33    510.9512195\n34    -83.3414634\n35   -457.0975610\n36     66.3658537\n37     73.0975610\n38    230.5609756\n39    -18.8048780\n40     46.3170732\n41    286.3170732\n42    576.0731707\n43    372.4146341\n44   -253.2439024\n45   -112.1219512\n46   -533.2926829\n47     24.6585366\n48    746.9024390\n49   -107.9756098\n50    142.1219512\n51    -71.2439024\n52    -58.5121951\n53    763.5853659\n54     -2.9024390\n55   -136.3170732\n56    272.9024390\n57   -175.2439024\n58   -568.3658537\n59   -580.8536585\n60   -149.9756098\n61    192.0731707\n62    593.2439024\n63   -251.8780488\n64   -351.4390244\n65    800.4634146\n66   -420.2195122\n67    -57.9268293\n68   -479.4878049\n69    104.4634146\n70     66.3170732\n71   -483.4390244\n72    716.0243902\n73    233.5365854\n74    639.5365854\n75    -55.3414634\n76    533.7804878\n77   -658.0243902\n78   -724.1219512\n79   -497.3414634\n80    200.1219512\n81    351.2926829\n82   -103.5365854\n83   -605.2439024\n84   -290.1707317\n85     35.2439024\n86   -249.0000000\n87    629.1463415\n88     25.5853659\n89    521.0975610\n90   -273.0000000\n91    703.1951220\n92   -337.6829268\n93    596.7560976\n94    869.0975610\n95   -641.0487805\n96    -84.1219512\n97    266.3658537\n98    114.7560976\n99   -368.7560976\n100  -149.9756098\n101  -593.3902439\n102  -194.7560976\n103  -447.9268293\n104   513.3902439\n105   460.9512195\n106  -354.9512195\n107  -457.4390244\n108  -483.1951220\n109   253.6829268\n110  -205.0487805\n111   158.8048780\n112   -54.0731707\n113   -25.2439024\n114   637.5365854\n115  -538.4146341\n116    53.5365854\n117  -564.4634146\n118   -46.6097561\n119  -566.3170732\n120  -464.9024390\n121   666.9024390\n122  -504.7560976\n123  -130.6585366\n124  -507.7804878\n125   279.9756098\n126   -15.9756098\n127  -673.5365854\n128   -26.1219512\n129    16.7073171\n130  -699.8292683\n131   133.1951220\n132  -789.5853659\n133  -114.8536585\n134   285.2439024\n135    92.4634146\n136  -426.1707317\n137   275.6829268\n138  -436.8536585\n139    39.5365854\n140    67.7317073\n141   133.4878049\n142  -127.0975610\n143    64.6585366\n144  -446.1219512\n145   -53.7317073\n146  -229.0975610\n147    44.4634146\n148   718.0731707\n149    -5.0975610\n150    48.5609756\n151  -713.0487805\n152  -409.4390244\n153   671.0975610\n154   612.8536585\n155  -843.9756098\n156   -41.7804878\n157  -283.1951220\n158    22.7073171\n159   -60.9512195\n160   628.2195122\n161   -30.4634146\n162  -385.7317073\n163   -44.7073171\n164   547.4878049\n165   139.3414634\n166   -67.0975610\n167  -591.8292683\n168   186.5121951\n169   175.0487805\n170    38.8048780\n171  -181.9756098\n172  -721.2926829\n173   -44.8048780\n174   521.6829268\n175  -441.0487805\n176   183.7317073\n177   -81.2926829\n178  -519.1463415\n179    90.3658537\n180   440.8536585\n181  -165.7317073\n182   220.9512195\n183  -612.9512195\n184  -161.4878049\n185  -484.7560976\n186  -605.5365854\n187  -370.7073171\n188   395.0975610\n189  -395.8292683\n190  -246.6097561\n191   608.2195122\n192    15.8292683\n193   -49.9756098\n194  -712.0731707\n195  -391.5365854\n196   744.4146341\n197   -70.2195122\n198  -813.2439024\n199   362.0731707\n200  -626.1707317\n201  -571.2439024\n202  -567.3414634\n203  -774.0243902\n204  -596.9512195\n205   526.1707317\n206   639.8292683\n207   384.2195122\n208  -160.1219512\n209   702.7073171\n210   -57.1463415\n211    95.6341463\n212  -475.1951220\n213  -513.1951220\n214    80.8536585\n215  -519.9268293\n216   429.9268293\n217  -587.8292683\n218  -537.2439024\n219  -155.2926829\n220  -471.7317073\n221     1.8780488\n222   887.7804878\n223  -651.9268293\n224  -227.0975610\n225   549.1463415\n226  -391.9756098\n227    38.7560976\n228  -326.3658537\n229    80.6585366\n230    27.0000000\n231   -47.0487805\n232   553.8292683\n233   632.2682927\n234   581.5853659\n235  -588.7073171\n236    57.8780488\n237    91.7317073\n238   130.4634146\n239    20.8048780\n240    88.7073171\n241  -409.0000000\n242  -306.7560976\n243  -622.6097561\n244   540.9512195\n245   148.1219512\n246  -604.6585366\n247    76.5609756\n248    61.4390244\n249   394.2682927\n250   568.7073171\n251   -81.5365854\n252   725.3902439\n253  -376.6585366\n254    93.9756098\n255   -13.3902439\n256   581.4878049\n257   554.4634146\n258   570.3170732\n259  -287.2926829\n260    42.0731707\n261   696.5609756\n262   726.7560976\n263  -314.3170732\n264  -638.0243902\n265   146.0243902\n266   -18.2195122\n267  -141.8780488\n268   720.9512195\n269  -110.7073171\n270    -8.1219512\n271  -500.9024390\n272   -59.8292683\n273   -57.0975610\n274   108.5609756\n275   -76.5609756\n276   341.8780488\n277  -459.9756098\n278  -582.3658537\n279  -769.2926829\n280   444.3170732\n281  -653.2926829\n282  -132.8536585\n283  -491.0487805\n284   -40.0731707\n285    31.0487805\n286   166.7560976\n287  -645.5853659\n288   702.1219512\n289  -367.3414634\n290   325.0000000\n291   274.5609756\n292    52.4634146\n293   169.0000000\n294  -466.2195122\n295   542.0243902\n296   227.4390244\n297  -580.1219512\n298  -554.9512195\n299   459.0975610\n300   351.2926829\n301  -305.1463415\n302  -130.7560976\n303  -643.8780488\n304  -198.9024390\n305  -335.2439024\n306   540.6097561\n307   532.3658537\n308   495.4390244\n309  -589.7317073\n310  -195.8292683\n311   183.9268293\n312   158.4146341\n313  -278.9024390\n314   364.8536585\n315  -242.2195122\n316   626.6097561\n317   387.5365854\n318     5.6829268\n319   660.9512195\n320  -390.2195122\n321  -711.6341463\n322   533.6829268\n323    76.7560976\n324   590.7073171\n325   154.7073171\n326   453.6829268\n327   -26.9024390\n328   676.7560976\n329  -631.3902439\n330  -409.3414634\n331   -47.8780488\n332   207.0487805\n333   510.9024390\n334  -580.4146341\n335  -241.0487805\n336   164.9024390\n337   198.7560976\n338    24.8536585\n339    48.8048780\n340  -157.3414634\n341    91.3414634\n342   -29.2926829\n343  -141.1463415\n344  -180.5121951\n345   353.3902439\n346  -257.7317073\n347   -82.9024390\n348  -694.3658537\n349   731.0975610\n350    70.5121951\n351   161.1951220\n352  -754.8048780\n353  -289.6829268\n354  -267.4878049\n355   620.5609756\n356  -229.3902439\n357   423.1951220\n358  -133.7804878\n359  -115.9268293\n360  -354.6585366\n361   663.8292683\n362  -508.9512195\n363    34.4634146\n364  -461.9268293\n365   276.6097561\n366  -587.0000000\n367    -5.2926829\n368  -577.3414634\n369  -608.4146341\n370   327.0000000\n371   105.6341463\n372  -438.6585366\n373  -224.1707317\n374    68.1707317\n375  -520.0243902\n376  -141.2926829\n377  -780.7560976\n378   -58.1219512\n379  -513.1951220\n380  -300.0243902\n381   473.4390244\n382  -209.7804878\n383   266.9512195\n384  -460.2195122\n385  -577.2926829\n386  -112.7073171\n387  -469.6341463\n388   183.6829268\n389   765.2439024\n390  -178.6097561\n391    -6.9512195\n392    86.9024390\n393   601.7317073\n394   120.1219512\n395   107.8780488\n396   -49.0975610\n397   399.2439024\n398   118.9024390\n399   639.2926829\n400  -714.6097561\n401  -518.4146341\n402   365.0975610\n403  -550.3170732\n404  -413.3902439\n405  -206.7560976\n406  -499.2926829\n407   -31.8780488\n408  -138.0243902\n409   121.1463415\n410    39.8292683\n411    62.0731707\n412  -136.3170732\n413  -553.7317073\n414   191.5853659\n415  -453.3414634\n416  -683.4878049\n417  -794.1219512\n418   749.4390244\n419   -55.7804878\n420   -60.4146341\n421   272.1219512\n422   -12.2682927\n423    53.0975610\n424  -261.7317073\n425   223.7804878\n426  -223.1951220\n427   621.1951220\n428   672.7560976\n429   -55.0000000\n430  -438.4634146\n431  -589.0487805\n432   511.0487805\n433  -181.6341463\n434   -89.7804878\n435    46.3170732\n436  -582.8048780\n437    85.0975610\n438  -246.8536585\n439    57.7317073\n440  -529.8292683\n441   638.7073171\n442   734.9024390\n443  -119.0487805\n444   721.7317073\n445   133.3414634\n446   -92.2682927\n447    37.5365854\n448    -0.6585366\n449  -289.5853659\n450   -94.1707317\n451  -703.1951220\n452    89.2439024\n453   185.0000000\n454  -454.9512195\n455    16.2195122\n456  -550.7073171\n457  -275.0975610\n458  -799.4878049\n459  -414.9024390\n460  -625.6829268\n461   157.8292683\n462   549.4390244\n463   115.7804878\n464  -572.8536585\n465   590.9512195\n466    75.0000000\n467   827.3902439\n468   213.4878049\n469  -577.1951220\n470  -442.7560976\n471    68.9512195\n472   -18.6097561\n473  -211.1951220\n474  -118.7073171\n475  -208.4634146\n476  -497.0487805\n477    28.4146341\n478   431.0975610\n479   173.7317073\n480  -337.1951220\n481    -0.8536585\n482  -513.3902439\n483   625.0487805\n484   416.8048780\n485  -113.8292683\n486   716.8048780\n487  -750.6097561\n488   173.0000000\n489   -34.8048780\n490   487.4878049\n491   178.8536585\n492   -48.1707317\n493   672.7073171\n494  -531.7317073\n495    -8.9024390\n496    37.7804878\n497   684.5121951\n498  -498.8048780\n499  -473.8780488\n500   -35.8292683\n501  -279.9268293\n502    79.4878049\n503  -320.9024390\n504  -136.3170732\n505  -492.4634146\n506  -362.0243902\n507   -24.7073171\n508  -116.4146341\n509  -658.6097561\n510  -423.7317073\n511  -199.6341463\n512   601.8292683\n513   352.1219512\n514   553.1951220\n515   718.0731707\n516  -431.6829268\n517    51.8292683\n518     7.6829268\n519  -443.8780488\n520  -557.7317073\n521   -18.4634146\n522    84.1707317\n523    40.7073171\n524   668.4634146\n525    81.4390244\n526   171.8292683\n527  -161.4390244\n528   -87.8780488\n529  -267.1463415\n530   -55.2439024\n531    19.7804878\n532  -322.0243902\n533  -143.2439024\n534    37.2926829\n535   297.0000000\n536  -125.2439024\n537  -624.5609756\n538   -87.8292683\n539   627.3902439\n540   499.9268293\n541   -52.6585366\n542  -657.5853659\n543    11.2926829\n544   542.1219512\n545    94.3170732\n546   -38.4634146\n547  -247.8292683\n548   -23.3902439\n549  -256.0731707\n550   -85.1463415\n551   599.3414634\n552   106.8048780\n553   610.6585366\n554    28.3170732\n555   687.6341463\n556   -72.9024390\n557    52.7073171\n558   413.4390244\n559    26.4146341\n560   538.6097561\n561  -741.1463415\n562    59.6341463\n563   549.8780488\n564   128.6585366\n565  -159.3902439\n566   326.8048780\n567   322.0243902\n568   -95.0000000\n569  -417.6829268\n570   517.9756098\n571  -768.4634146\n572   407.5365854\n573   -11.0975610\n574   542.7560976\n575   105.7804878\n576   159.0487805\n577  -498.0243902\n578     4.5121951\n579  -113.9268293\n580   108.1219512\n581  -390.0731707\n582  -238.8048780\n583  -572.6097561\n584  -161.3902439\n585   206.2682927\n586  -249.3902439\n587  -480.4634146\n588   173.8780488\n589   800.0243902\n590   111.2926829\n591   -15.5365854\n592   108.6585366\n593   304.7560976\n594   491.3902439\n595  -730.5121951\n596    33.8292683\n597   706.0243902\n598  -469.9268293\n599    45.2926829\n600   205.6829268\n601   176.9024390\n602    40.0243902\n603   -56.6097561\n604   -22.7560976\n605  -666.2195122\n606  -698.8536585\n607  -118.8536585\n608  -184.4634146\n609  -535.7317073\n610   142.8536585\n611  -103.9268293\n612   -87.0000000\n613  -645.6341463\n614  -431.4878049\n615  -904.9512195\n616  -503.1951220\n617  -255.4878049\n618   477.6829268\n619  -277.0000000\n620   224.1219512\n621  -495.0000000\n622    80.0731707\n623    36.4634146\n624  -266.9024390\n625   349.6341463\n626    62.4634146\n627    69.7317073\n628  -652.0731707\n629   367.0975610\n630   244.7073171\n631  -356.2195122\n632  -517.4878049\n633   592.1219512\n634  -165.6829268\n635   404.2195122\n636   717.9756098\n637   683.8292683\n638   717.0487805\n639  -565.2439024\n640   315.3414634\n641  -365.0487805\n642   120.9512195\n643   118.7560976\n644  -577.6341463\n645    12.2195122\n646   188.1707317\n647  -538.5121951\n648   304.2682927\n649   191.3902439\n650    66.0731707\n651   578.2682927\n652  -743.3902439\n653  -711.6341463\n654  -713.1951220\n655   539.9756098\n656  -129.3902439\n657  -137.4390244\n658   715.7804878\n659    11.3902439\n660  -502.5121951\n661   267.0000000\n662  -321.3902439\n663   654.5609756\n664    99.2439024\n665   570.6097561\n666   594.3658537\n667   659.0000000\n668    37.8292683\n669  -541.6829268\n670   -42.0243902\n671  -633.1951220\n672    -5.6341463\n673   171.0000000\n674   491.8292683\n675   -67.7804878\n676   561.5853659\n677  -556.9024390\n678  -749.3414634\n679  -456.9512195\n680    99.0487805\n681   824.9512195\n682   461.9268293\n683   419.4390244\n684  -505.6341463\n685  -248.1219512\n686     3.3902439\n687  -292.8536585\n688    84.5609756\n689    17.8292683\n690   -88.5609756\n691  -482.5609756\n692  -320.0731707\n693  -592.8536585\n694  -252.0731707\n695   443.6341463\n696    30.9024390\n697  -285.0487805\n698   154.4634146\n699  -115.1463415\n700  -496.6585366\n701   740.5121951\n702  -772.4146341\n703   227.6341463\n704  -116.8536585\n705   677.7317073\n706   -83.2926829\n707   119.7317073\n708  -573.7317073\n709   535.0487805\n710   375.2926829\n711  -461.0487805\n712  -438.1219512\n713    67.0975610\n714    84.4634146\n715  -623.3902439\n716  -252.0243902\n717  -328.9512195\n718   525.4878049\n719  -755.3902439\n720   -21.3902439\n721   599.7317073\n722    59.7317073\n723  -596.6097561\n724   496.7073171\n725  -286.1707317\n726   637.6341463\n727   234.8536585\n728  -589.7804878\n729  -608.3170732\n730    91.6341463\n731  -628.3170732\n732  -424.4146341\n733   542.0731707\n734   -17.8780488\n735  -354.0243902\n736    51.5365854\n737   122.2682927\n738   260.9024390\n739  -534.6585366\n740   624.4146341\n741  -724.2682927\n742  -704.9512195\n743   176.1707317\n744  -163.6341463\n745    87.3902439\n746   690.8536585\n747   -35.5853659\n748   618.4146341\n749  -710.1707317\n750  -419.8780488\n751  -459.2439024\n752   211.0975610\n753  -320.0731707\n754   -45.5853659\n755   271.8780488\n756   551.5365854\n757    -6.0243902\n758   338.4634146\n759   442.5121951\n760   -17.6341463\n761   596.8048780\n762   370.8536585\n763  -147.7804878\n764  -543.3414634\n765   179.9268293\n766  -607.1951220\n767    -3.1463415\n768   765.0487805\n769  -855.9756098\n770    51.9756098\n771   638.3658537\n772  -501.6341463\n773  -148.7560976\n774   124.9512195\n775   729.5365854\n776   434.3170732\n777    70.7560976\n778   503.2439024\n779   445.8780488\n780  -560.7560976\n781  -293.1463415\n782    88.2195122\n783  -202.3658537\n784   484.3170732\n785  -601.5365854\n786   240.0243902\n787  -571.5853659\n788    -7.2439024\n789   676.0243902\n790  -551.2439024\n791  -499.0000000\n792  -273.0975610\n793   678.5609756\n794  -100.0731707\n795  -386.8536585\n796  -461.4878049\n797   -64.7560976\n798  -546.7073171\n799   732.7560976\n800  -425.1951220\n801   -90.1219512\n802   -62.5609756\n803   639.5853659\n804    48.9024390\n805    21.9268293\n806  -516.0731707\n807  -806.9512195\n808   -11.2439024\n809   601.9756098\n810  -161.5365854\n811   487.5853659\n812     0.9024390\n813  -229.5853659\n814   388.3658537\n815   588.5609756\n816    51.0975610\n817     1.4390244\n818   -25.6341463\n819   -67.0000000\n820  -604.1219512\n821   108.5609756\n822    -9.3414634\n823    18.5609756\n824   220.3658537\n825   471.7317073\n826   120.6585366\n827  -600.9512195\n828  -434.2682927\n829  -422.7560976\n830  -165.4878049\n831   734.0731707\n832  -184.0731707\n833   366.5121951\n834  -575.8292683\n835   210.0731707\n836  -528.1219512\n837  -227.9756098\n838  -380.7560976\n839   559.4390244\n840   455.2926829\n841  -571.4878049\n842   154.5609756\n843  -597.8780488\n844   661.2926829\n845  -177.2926829\n846  -134.7560976\n847    75.0000000\n848   -80.5121951\n849   194.0243902\n850  -180.7073171\n851  -149.1951220\n852    29.6341463\n853  -485.0487805\n854   461.2439024\n855   -52.3658537\n856  -627.5853659\n857  -164.3170732\n858    86.6097561\n859   -58.4146341\n860    61.3902439\n861   -98.7073171\n862   701.0000000\n863  -217.3902439\n864   679.1463415\n865   397.4878049\n866   316.4146341\n867  -163.9268293\n868  -127.6341463\n869   -26.4634146\n870  -636.3658537\n871  -483.2926829\n872   114.0243902\n873  -524.4146341\n874    -2.3658537\n875    -4.4634146\n876  -523.7804878\n877   -90.5609756\n878  -578.2682927\n879  -555.4878049\n880  -331.5365854\n881  -325.7804878\n882  -663.1951220\n883    47.1463415\n884  -627.6341463\n885  -557.8780488\n886   373.6829268\n887  -543.9756098\n888     5.7317073\n889  -360.1707317\n890   676.8536585\n891  -323.4390244\n892  -440.1219512\n893  -272.2682927\n894   223.4390244\n895  -423.0487805\n896   725.9756098\n897   112.7073171\n898   -45.9268293\n899  -640.4634146\n900  -691.7804878\n901   698.6097561\n902   -52.8536585\n903  -726.6097561\n904  -413.1951220\n905  -760.9024390\n906  -743.1463415\n907   257.2926829\n908  -123.5365854\n909    43.3902439\n910   553.6341463\n911  -557.4390244\n912   517.3414634\n913  -187.0487805\n914     6.7560976\n915   590.4146341\n916  -533.4878049\n917     4.6097561\n918  -123.5853659\n919    18.9024390\n920  -550.1707317\n921  -237.6341463\n922   460.5121951\n923    53.3902439\n924   544.0243902\n925  -146.8536585\n926    89.5853659\n927  -568.5121951\n928     5.4390244\n929  -402.9512195\n930  -230.5609756\n931  -599.1463415\n932    45.6341463\n933   583.1951220\n934   450.3170732\n935  -362.5121951\n936   129.1951220\n937   119.9756098\n938  -168.2195122\n939   501.7804878\n940  -290.9512195\n941  -751.4878049\n942  -673.6341463\n943  -136.2195122\n944   214.2195122\n945   130.9024390\n946     0.5609756\n947   684.1219512\n948  -324.5121951\n949   270.2682927\n950  -119.2926829\n951  -147.9268293\n952   649.6341463\n953  -188.8536585\n954  -422.6097561\n955    61.2439024\n956  -588.4146341\n957   167.9268293\n958   -34.5609756\n959  -201.6341463\n960   -37.1951220\n961    88.6097561\n962  -187.4390244\n963  -129.0487805\n964  -230.9512195\n965   615.4390244\n966   644.5121951\n967  -383.6341463\n968  -131.6829268\n969   372.4634146\n970   499.9268293\n971  -658.6097561\n972   503.6341463\n973   -86.0731707\n974  -143.1463415\n975   762.2195122\n976   110.5609756\n977  -236.5121951\n978  -390.0243902\n979   102.7560976\n980   -50.2682927\n981   269.0000000\n982   237.0975610\n983  -804.9024390\n984   385.9756098\n985   171.6829268\n986    80.1219512\n987   321.5365854\n988  -113.0975610\n989     8.6585366\n990  -662.8048780\n991   499.6829268\n992   501.0487805\n993    56.4634146\n994  -139.4390244\n995   133.7804878\n996  -172.8048780\n997   582.7073171\n998    21.6829268\n999   -27.2439024\n1000  114.2682927\n1001 -308.7560976\n1002 -681.4878049\n1003   23.2926829\n1004 -709.2439024\n1005  508.2682927\n1006 -540.9024390\n1007  682.8536585\n1008  428.3170732\n1009 -566.9024390\n1010  486.4146341\n1011  -40.3658537\n1012   71.9268293\n1013 -132.0731707\n1014   37.0487805\n1015  -43.9268293\n1016 -297.2439024\n1017  201.8780488\n1018 -200.7073171\n1019  708.1219512\n1020 -541.0000000\n1021 -731.6829268\n1022 -119.0000000\n1023 -574.0243902\n1024  112.0731707\n1025  -40.0243902\n1026 -657.8292683\n1027 -111.0000000\n1028  466.3170732\n1029  -14.0243902\n1030 -540.3658537\n1031   80.9512195\n1032  -55.2926829\n1033  717.1951220\n1034 -410.2682927\n1035  133.2439024\n1036 -384.9024390\n1037  401.3902439\n1038 -496.2682927\n1039 -371.3414634\n1040  -91.0975610\n1041 -155.9756098\n1042 -543.4878049\n1043  576.1707317\n1044   88.3170732\n1045  440.0731707\n1046  210.7073171\n1047 -174.7073171\n1048  695.3414634\n1049 -765.2439024\n1050   98.1707317\n1051 -170.4146341\n1052  391.8780488\n1053  525.1951220\n1054  198.1707317\n1055 -719.1463415\n1056 -783.0000000\n1057 -557.7317073\n1058  132.0731707\n1059   87.2439024\n1060   -5.0975610\n1061  764.7073171\n1062  -91.4390244\n1063  -77.4390244\n1064 -592.6097561\n1065 -404.7560976\n1066 -487.9756098\n1067  746.2195122\n1068  414.7073171\n1069 -759.0000000\n1070  427.2926829\n1071  141.5853659\n1072 -709.5853659\n1073   -5.6341463\n1074 -177.2439024\n1075  380.7073171\n1076  -97.8780488\n1077 -528.5121951\n1078 -568.2682927\n1079 -426.1219512\n1080  556.9024390\n1081  663.4390244\n1082  -75.9268293\n1083  -71.8292683\n1084 -514.3658537\n1085   16.6097561\n1086 -551.4390244\n1087   95.0975610\n1088  164.4634146\n1089 -517.7804878\n1090  495.5853659\n1091  587.3414634\n1092  690.5609756\n1093   42.5121951\n1094  479.7804878\n1095  394.3170732\n1096  -87.0975610\n1097  538.4634146\n1098 -543.0000000\n1099 -281.9756098\n1100   29.0487805\n1101  461.0000000\n1102  762.4634146\n1103   -1.4390244\n1104  798.3170732\n1105  471.8292683\n1106  170.6097561\n1107  717.3414634\n1108  557.8292683\n1109   40.1219512\n1110 -589.9268293\n1111 -449.7317073\n1112  606.4146341\n1113  237.3414634\n1114  130.9024390\n1115  753.0487805\n1116  664.9024390\n1117 -487.2926829\n1118 -498.0731707\n1119  118.6097561\n1120  -80.0731707\n1121   43.9756098\n1122  380.9024390\n1123   58.8048780\n1124  -12.1707317\n1125  -70.2682927\n1126  126.5121951\n1127 -717.4878049\n1128  -33.8292683\n1129  692.2195122\n1130 -309.7317073\n1131  114.7560976\n1132  597.2926829\n1133 -120.4146341\n1134 -645.1951220\n1135  151.1463415\n1136 -583.1951220\n1137  -30.2682927\n1138 -406.8536585\n1139  499.0000000\n1140  159.8292683\n1141 -181.6829268\n1142  405.1463415\n1143   46.3170732\n1144  132.8536585\n1145 -154.6097561\n1146  145.1463415\n1147    5.2926829\n1148 -139.2926829\n1149  456.3170732\n1150 -673.6829268\n1151 -710.1707317\n1152 -649.6341463\n1153  -18.2195122\n1154   35.8780488\n1155  131.8780488\n1156  129.1951220\n1157  595.0000000\n1158   64.8536585\n1159  432.8536585\n1160  810.8048780\n1161  686.3170732\n1162  907.1463415\n1163  696.5121951\n1164  -91.0000000\n1165  179.4878049\n1166   23.8780488\n1167 -679.4390244\n1168 -638.7073171\n1169 -439.3902439\n1170  -66.8536585\n1171 -301.4390244\n1172  -48.9512195\n1173   42.8048780\n1174 -469.4390244\n1175 -671.4878049\n1176  -22.8048780\n1177 -429.3902439\n1178  351.5853659\n1179  501.7317073\n1180 -193.3902439\n1181  703.6829268\n1182 -230.2195122\n1183 -702.9512195\n1184 -483.2926829\n1185 -136.5121951\n1186  537.4390244\n1187 -149.8780488\n1188 -378.9024390\n1189 -218.7560976\n1190  -29.3414634\n1191    6.5121951\n1192 -481.4390244\n1193 -246.9024390\n1194  118.3170732\n1195 -190.7560976\n1196  -24.1219512\n1197   85.2439024\n1198  638.2195122\n1199 -700.0731707\n1200 -189.2926829\n1201  558.2682927\n1202  169.1951220\n1203  -17.7804878\n1204 -280.3658537\n1205  143.9268293\n1206  213.5365854\n1207 -741.9756098\n1208  213.6829268\n1209 -487.5853659\n1210  511.3414634\n1211  241.7317073\n1212  636.9024390\n1213  410.0731707\n1214 -375.2439024\n1215 -446.2195122\n1216  598.3170732\n1217  424.8048780\n1218 -450.5121951\n1219 -655.4390244\n1220  -13.0975610\n1221 -593.0975610\n1222 -261.5365854\n1223 -527.5853659\n1224  607.0975610\n1225  252.4146341\n1226  670.4146341\n1227    4.0243902\n1228 -626.0731707\n1229   97.7804878\n1230 -238.5609756\n1231 -611.3414634\n1232 -345.1463415\n1233 -267.1951220\n1234   18.8048780\n1235 -626.1219512\n1236 -325.1951220\n1237  227.6829268\n1238   17.9268293\n1239  -69.7317073\n1240 -250.9024390\n1241 -128.1707317\n1242 -166.0731707\n1243  126.8048780\n1244  125.1951220\n1245 -561.2439024\n1246  166.2195122\n1247  -88.6097561\n1248  309.0487805\n1249  -16.5121951\n1250 -131.6341463\n1251  -16.1219512\n1252  641.5365854\n1253 -455.3414634\n1254  -83.1463415\n1255 -551.8292683\n1256 -143.6829268\n1257 -608.7073171\n1258  317.7317073\n1259 -445.8292683\n1260  152.5609756\n1261 -163.1951220\n1262 -619.2439024\n1263 -439.3414634\n1264  296.0731707\n1265  -25.0000000\n1266 -275.2439024\n1267 -611.9756098\n1268  480.8536585\n1269 -510.5121951\n1270   97.4390244\n1271 -311.4390244\n1272  603.8292683\n1273 -461.9268293\n1274  395.1463415\n1275  427.5365854\n1276  586.5121951\n1277 -148.1219512\n1278 -334.2682927\n1279  690.5609756\n1280  562.8536585\n1281  -19.0975610\n1282  470.8048780\n1283  587.9268293\n1284   53.3414634\n1285 -534.1707317\n1286    3.2926829\n1287 -159.9756098\n1288  114.5121951\n1289  190.0243902\n1290 -611.5365854\n1291  499.5853659\n1292  299.8780488\n1293   27.8780488\n1294 -329.4878049\n1295 -395.8780488\n1296 -586.0731707\n1297  587.3414634\n1298  658.7560976\n1299  623.6341463\n1300  542.6585366\n1301 -434.5121951\n1302 -128.4146341\n1303  233.6341463\n1304  297.2439024\n1305  -89.2926829\n1306 -479.0487805\n1307    7.3414634\n1308  176.7073171\n1309 -508.4146341\n1310 -548.3658537\n1311   67.3414634\n1312   96.6585366\n1313  -90.8536585\n1314  432.4146341\n1315 -217.5853659\n1316 -553.0487805\n1317  569.9756098\n1318 -571.4390244\n1319 -115.2439024\n1320 -678.1707317\n1321    2.5121951\n1322   34.5609756\n1323 -680.4634146\n1324 -704.6585366\n1325  139.0975610\n1326 -167.4390244\n1327  522.2682927\n1328 -501.6829268\n1329 -146.6585366\n1330 -461.8780488\n1331  -61.0487805\n1332 -163.6829268\n1333 -490.2682927\n1334  143.6341463\n1335 -742.8048780\n1336  752.1219512\n1337  541.6829268\n1338  -91.5365854\n1339  414.5609756\n1340   28.5121951\n1341 -746.3658537\n1342  471.9756098\n1343  144.3658537\n1344  -10.3658537\n1345 -499.3414634\n1346 -680.5121951\n1347  610.3658537\n1348   64.9024390\n1349 -470.1707317\n1350  125.0487805\n1351 -576.3658537\n1352  -60.6097561\n1353 -229.5365854\n1354 -123.5365854\n1355 -473.7804878\n1356 -284.9512195\n1357  669.2926829\n1358 -275.9756098\n1359 -126.0243902\n1360   93.2926829\n1361 -581.6829268\n1362  -29.0000000\n1363  675.2926829\n1364   86.2195122\n1365  662.8048780\n1366  -68.4634146\n1367   -9.5365854\n1368 -453.7804878\n1369 -454.3170732\n1370   17.0000000\n1371  -47.9268293\n1372  742.6097561\n1373 -122.1219512\n1374 -433.3902439\n1375  135.2926829\n1376 -252.6097561\n1377 -570.6585366\n1378   50.8536585\n1379  -56.6097561\n1380  603.1951220\n1381  671.7317073\n1382  727.8780488\n1383  225.0975610\n1384  -78.5121951\n1385  108.4146341\n1386  479.4390244\n1387 -180.3170732\n1388  270.0731707\n1389  857.4878049\n1390   33.8292683\n1391 -590.7560976\n1392   72.8048780\n1393  589.5365854\n1394 -619.1951220\n1395   50.1219512\n1396 -385.8292683\n1397  850.3170732\n1398 -140.2195122\n1399 -539.3414634\n1400  -20.5609756\n1401  149.7317073\n1402  243.3902439\n1403  265.5853659\n1404 -475.3414634\n1405   39.1463415\n1406  609.8780488\n1407  141.6341463\n1408  582.7073171\n1409  -50.1219512\n1410  381.1463415\n1411  -55.4390244\n1412 -558.8536585\n1413  752.5121951\n1414 -273.1463415\n1415   91.2926829\n1416  360.6097561\n1417 -274.5609756\n1418  -55.9268293\n1419 -680.5121951\n1420  156.4634146\n1421   -1.5853659\n1422  492.8048780\n1423  127.2926829\n1424  -13.9268293\n1425 -351.8292683\n1426  290.0243902\n1427   28.5121951\n1428 -558.3170732\n1429  615.5853659\n1430 -129.5853659\n1431 -352.5121951\n1432  643.4390244\n1433 -127.4390244\n1434 -808.9024390\n1435  420.5609756\n1436  228.0731707\n1437 -584.8048780\n1438  544.9512195\n1439  331.3902439\n1440  254.5609756\n1441  -19.0975610\n1442 -371.0000000\n1443  596.1707317\n1444  482.0731707\n1445  463.9268293\n1446  150.0243902\n1447 -635.8780488\n1448   60.0731707\n1449  730.4146341\n1450  551.6829268\n1451 -423.2926829\n1452  394.3658537\n1453  308.4146341\n1454   -4.5121951\n1455  234.5609756\n1456  453.3902439\n1457 -428.4634146\n1458  109.2926829\n1459  753.1951220\n1460 -378.0731707\n1461 -385.4878049\n1462 -795.3414634\n1463 -500.4146341\n1464  157.5365854\n1465 -621.7317073\n1466  337.6829268\n1467 -526.3658537\n1468  343.5365854\n1469  577.0000000\n1470  189.7317073\n1471 -506.4634146\n1472 -525.5365854\n1473  587.6829268\n1474 -670.4146341\n1475  487.4878049\n1476 -431.0000000\n1477  569.0000000\n1478   87.6829268\n1479   77.9756098\n1480  249.5853659\n1481  607.8292683\n1482  -27.7317073\n1483  -44.2195122\n1484 -613.1463415\n1485 -503.7804878\n1486 -168.2682927\n1487 -603.1951220\n1488  290.1219512\n1489 -310.9512195\n1490  424.9512195\n1491 -577.2439024\n1492 -185.0000000\n1493  -83.8292683\n1494  394.7073171\n1495   -3.3902439\n1496   25.9756098\n1497   18.7073171\n1498 -164.8536585\n1499   10.4146341\n1500 -465.6829268\n1501  225.6829268\n1502  154.3170732\n1503  569.4390244\n1504  175.0000000\n1505 -279.7317073\n1506 -450.8536585\n1507  563.2439024\n1508  338.3170732\n1509 -242.6585366\n1510   70.7073171\n1511 -507.0487805\n1512  105.0975610\n1513 -675.2439024\n1514 -368.3170732\n1515 -174.6097561\n1516  674.0243902\n1517  -20.0731707\n1518 -620.2195122\n1519  423.9756098\n1520   96.4634146\n1521 -155.6829268\n1522 -513.5365854\n1523  627.4878049\n1524    9.3902439\n1525   -1.7804878\n1526    8.5121951\n1527  602.9024390\n1528 -169.9268293\n1529  737.8292683\n1530 -649.7804878\n1531  -53.1463415\n1532  514.1707317\n1533 -237.5365854\n1534  -55.0000000\n1535 -725.3902439\n1536  569.3902439\n1537 -371.5365854\n1538 -649.0000000\n1539 -689.3414634\n1540 -345.5853659\n1541  360.0243902\n1542 -743.7804878\n1543    2.5121951\n1544 -729.2439024\n1545 -868.3658537\n1546 -586.6097561\n1547  720.6585366\n1548  477.6829268\n1549 -433.4878049\n1550  670.6097561\n1551  348.2195122\n1552 -345.5853659\n1553  117.9756098\n1554 -262.0243902\n1555 -382.3170732\n1556   -5.5365854\n1557  -73.7804878\n1558  628.4146341\n1559   82.8536585\n1560  723.0487805\n1561 -160.2682927\n1562 -592.0731707\n1563   69.0975610\n1564  146.8048780\n1565 -530.7560976\n1566 -547.7804878\n1567 -615.0975610\n1568  105.4390244\n1569   84.7560976\n1570  591.3414634\n1571    7.9756098\n1572  548.4634146\n1573 -521.7317073\n1574  218.6585366\n1575   35.5853659\n1576 -465.8292683\n1577  123.8780488\n1578  666.7560976\n1579  467.4878049\n1580 -552.1219512\n1581   -5.3902439\n1582 -329.4390244\n1583  848.6585366\n1584  484.6097561\n1585   41.2926829\n1586  510.2682927\n1587  549.6341463\n1588   35.0975610\n1589 -475.7804878\n1590  790.5609756\n1591 -336.6585366\n1592 -245.2439024\n1593  -43.4878049\n1594  787.1951220\n1595  594.6585366\n1596  244.9024390\n1597  538.1707317\n1598  -76.9024390\n1599  512.4634146\n1600  -93.2439024\n1601  295.3902439\n1602  540.2195122\n1603  -39.4878049\n1604 -527.7317073\n1605  178.3170732\n1606  561.9756098\n1607  -94.7560976\n1608  613.9756098\n1609 -602.4146341\n1610  -16.7560976\n1611 -322.8048780\n1612   -3.7317073\n1613 -432.3170732\n1614  138.6585366\n1615 -499.1951220\n1616  -10.7560976\n1617 -104.4634146\n1618  -11.4390244\n1619 -155.6341463\n1620 -491.0000000\n1621 -450.1219512\n1622 -119.6341463\n1623  -71.8292683\n1624 -585.9268293\n1625 -409.1463415\n1626  100.3658537\n1627  -77.4878049\n1628  682.0731707\n1629  494.1707317\n1630 -160.7560976\n1631  574.3170732\n1632   89.6341463\n1633  627.4390244\n1634 -484.0731707\n1635 -568.8048780\n1636 -247.1463415\n1637  -12.0731707\n1638 -676.1707317\n1639  286.4634146\n1640  135.3902439\n1641 -146.4634146\n1642  215.9756098\n1643  267.5853659\n1644  435.7317073\n1645  -29.7317073\n1646  144.7560976\n1647 -458.1707317\n1648 -456.0731707\n1649  -82.9024390\n1650  550.2682927\n1651 -425.0975610\n1652 -116.3658537\n1653 -341.8780488\n1654 -179.0000000\n1655  -73.5853659\n1656   17.9756098\n1657 -428.5121951\n1658  -47.1951220\n1659 -298.5121951\n1660   -6.7560976\n1661  139.5365854\n1662  -58.5609756\n1663   50.3170732\n1664  -25.5365854\n1665   58.6097561\n1666 -568.6097561\n1667 -669.3902439\n1668  391.4390244\n1669  527.8292683\n1670  179.4390244\n1671  338.2682927\n1672 -155.3902439\n1673  468.1707317\n1674 -201.7317073\n1675 -211.9268293\n1676  136.9024390\n1677  211.7317073\n1678  -91.7804878\n1679 -510.0731707\n1680  791.4390244\n1681  -29.0487805\n1682 -735.2439024\n1683  642.0243902\n1684 -515.6829268\n1685  326.8048780\n1686 -427.3414634\n1687  439.3902439\n1688 -419.8292683\n1689  113.8780488\n1690   27.9268293\n1691 -512.9512195\n1692   -3.0487805\n1693 -559.6341463\n1694 -490.5609756\n1695 -123.2439024\n1696 -410.9024390\n1697  485.7804878\n1698 -441.5853659\n1699   89.3414634\n1700  -99.8780488\n1701  118.0243902\n1702 -592.4634146\n1703  -20.9512195\n1704 -198.8048780\n1705  284.4146341\n1706  419.8292683\n1707  -86.0731707\n1708 -586.1707317\n1709 -136.0731707\n1710 -164.5121951\n1711  493.3414634\n1712 -412.7073171\n1713  -72.3658537\n1714  520.4634146\n1715   54.6585366\n1716 -616.1219512\n1717 -124.4634146\n1718  613.7804878\n1719  241.2439024\n1720  -13.9268293\n1721  541.5365854\n1722 -466.2195122\n1723 -506.9024390\n1724 -350.7560976\n1725  -17.9756098\n1726 -575.1463415\n1727   19.6341463\n1728  -67.9756098\n1729 -249.9268293\n1730  126.7073171\n1731 -116.0731707\n1732  -15.9756098\n1733   87.7804878\n1734 -547.0975610\n1735 -236.4634146\n1736 -514.6097561\n1737  258.6585366\n1738  475.9268293\n1739  509.4390244\n1740   -5.5853659\n1741  -16.4634146\n1742  294.0731707\n1743  277.4878049\n1744  -31.3414634\n1745  617.3902439\n1746  -72.9512195\n1747  226.4146341\n1748 -528.9512195\n1749   79.2439024\n1750 -539.0975610\n1751 -295.1951220\n1752   31.7804878\n1753   35.2926829\n1754  526.0731707\n1755  138.1219512\n1756 -554.4634146\n1757 -177.1951220\n1758 -662.9024390\n1759  170.8048780\n1760 -369.7317073\n1761 -853.0487805\n1762   78.2195122\n1763   44.3170732\n1764  -17.3414634\n1765   85.2439024\n1766  284.0731707\n1767  115.1951220\n1768 -296.7073171\n1769  521.3414634\n1770  -27.5365854\n1771   11.6341463\n1772  130.6585366\n1773   23.1463415\n1774 -115.1463415\n1775 -620.1707317\n1776   57.7317073\n1777 -595.3902439\n1778  670.6585366\n1779   76.5121951\n1780  -92.1707317\n1781 -166.1219512\n1782  -47.3414634\n1783   88.2195122\n1784 -534.7560976\n1785  119.9268293\n1786 -138.2682927\n1787  613.8780488\n1788  -20.5121951\n1789  538.6585366\n1790  383.0487805\n1791  176.9512195\n1792   67.6341463\n1793  699.6341463\n1794  -81.8292683\n1795 -509.0000000\n1796  629.4878049\n1797 -579.1463415\n1798 -649.5853659\n1799  -18.8048780\n1800   59.4878049\n1801  326.4634146\n1802  521.4390244\n1803 -204.6097561\n1804 -601.5853659\n1805   22.5121951\n1806  274.6097561\n1807  290.3170732\n1808  221.1951220\n1809  623.1951220\n1810  254.8048780\n1811  193.9756098\n1812 -608.1219512\n1813 -134.1707317\n1814 -687.5853659\n1815  141.6341463\n1816  -97.5853659\n1817  122.0243902\n1818 -503.2926829\n1819 -460.9024390\n1820  -30.8048780\n1821 -114.5609756\n1822  471.8780488\n1823   99.3902439\n1824 -132.5609756\n1825 -630.0731707\n1826 -261.3414634\n1827  199.7317073\n1828  269.7317073\n1829   35.6829268\n1830  140.4634146\n1831   83.5365854\n1832 -100.0243902\n1833  469.9268293\n1834  536.6585366\n1835  -60.1219512\n1836  118.6585366\n1837 -513.6341463\n1838 -454.0731707\n1839  -78.6097561\n1840 -276.8048780\n1841  421.7804878\n1842  -69.6829268\n1843 -288.1219512\n1844  240.4634146\n1845 -621.4390244\n1846  164.0243902\n1847 -561.8292683\n1848  -75.0000000\n1849  440.3658537\n1850   78.8536585\n1851  379.0975610\n1852  112.0731707\n1853 -686.9512195\n1854  322.5121951\n1855  410.2682927\n1856  250.1707317\n1857 -501.8292683\n1858  -11.9756098\n1859  505.0000000\n1860 -143.9268293\n1861   -0.5609756\n1862   43.1951220\n1863 -375.4390244\n1864  -39.7804878\n1865 -541.1951220\n1866   20.7073171\n1867 -454.2195122\n1868  219.5365854\n1869 -567.0975610\n1870 -634.1707317\n1871  671.3414634\n1872  517.4878049\n1873  -16.7073171\n1874  525.7317073\n1875  137.3902439\n1876  -35.2439024\n1877  261.8780488\n1878   95.6829268\n1879   16.5609756\n1880  771.5853659\n1881 -135.0487805\n1882  171.9268293\n1883  -35.2439024\n1884 -160.7560976\n1885 -112.0731707\n1886  -66.7073171\n1887  -96.4146341\n1888 -542.3658537\n1889  133.9268293\n1890  104.4146341\n1891    2.3170732\n1892 -271.2439024\n1893 -572.9512195\n1894  478.5609756\n1895  -96.8536585\n1896  475.3902439\n1897 -407.0000000\n1898 -374.0731707\n1899  565.1951220\n1900   69.4390244\n1901 -295.0000000\n1902  -50.5121951\n1903 -780.1219512\n1904   41.9268293\n1905 -202.5609756\n1906  703.9756098\n1907 -186.1707317\n1908 -302.0731707\n1909 -141.9756098\n1910  357.6341463\n1911  629.6341463\n1912   98.3658537\n1913  102.7073171\n1914  152.9024390\n1915  491.1951220\n1916  326.1219512\n1917 -596.9512195\n1918  616.3170732\n1919  464.5609756\n1920  311.2439024\n1921    5.6829268\n1922  739.0975610\n1923 -230.2195122\n1924  747.4390244\n1925  427.1951220\n1926  391.8292683\n1927 -244.6585366\n1928 -378.6585366\n1929    1.4878049\n1930  -53.9268293\n1931  -17.9268293\n1932  421.2926829\n1933  151.0975610\n1934 -600.9512195\n1935  479.0487805\n1936 -775.0000000\n1937  485.1951220\n1938  -27.8292683\n1939  657.5365854\n1940  492.7560976\n1941 -602.1707317\n1942 -102.3658537\n1943 -520.1219512\n1944  514.1707317\n1945 -114.8536585\n1946  251.0487805\n1947    9.5853659\n1948 -674.3170732\n1949  521.8780488\n1950  210.5609756\n1951 -158.1219512\n1952  212.9512195\n1953  649.4878049\n1954 -632.5121951\n1955  306.0243902\n1956  -95.6341463\n1957  194.7073171\n1958 -470.1219512\n1959 -139.1951220\n1960 -403.6829268\n1961  700.4634146\n1962 -847.0975610\n1963 -604.4634146\n1964  -73.5853659\n1965  319.0000000\n1966  -74.5121951\n1967  218.1219512\n1968   84.7073171\n1969  -12.7560976\n1970   15.0975610\n1971  166.6097561\n1972 -285.2439024\n1973    0.7560976\n1974 -371.0975610\n1975 -183.2439024\n1976    9.3902439\n1977  -13.5365854\n1978  489.5853659\n1979  770.2682927\n1980  -78.9512195\n1981  -16.6585366\n1982  147.8292683\n1983  178.8048780\n1984 -544.6585366\n1985  691.7804878\n1986 -244.1707317\n1987  150.5609756\n1988  263.6829268\n1989  528.4146341\n1990  -95.1951220\n1991 -224.5609756\n1992  204.0243902\n1993   -6.7073171\n1994 -567.1463415\n1995  301.6341463\n1996  -39.3414634\n1997  380.6097561\n1998  327.7317073\n1999   35.3414634\n2000  298.9024390\n2001 -371.4390244\n2002  660.5609756\n2003 -522.6097561\n2004 -461.2439024\n2005 -340.0731707\n2006 -203.5853659\n2007  655.8292683\n2008  290.7073171\n2009  122.4634146\n2010  543.2926829\n2011 -599.2439024\n2012   21.3902439\n2013 -138.1707317\n2014  642.1707317\n2015   17.9268293\n2016  -72.4146341\n2017  -47.7804878\n2018 -111.4878049\n2019  732.9512195\n2020   45.7317073\n2021 -206.7073171\n2022  -57.0000000\n2023    0.2195122\n2024  -32.8536585\n2025  356.4146341\n2026  728.5609756\n2027 -628.8536585\n2028  282.0243902\n2029  456.9512195\n2030  110.6585366\n2031  583.0000000\n2032 -743.9756098\n2033  651.7317073\n2034  639.5365854\n2035 -105.9268293\n2036 -135.6829268\n2037  572.5609756\n2038   86.0731707\n2039 -134.7073171\n2040  -45.7804878\n2041  283.2439024\n2042  571.5365854\n2043  534.5609756\n2044  -58.9024390\n2045  329.9268293\n2046  214.0243902\n2047 -429.7317073\n2048 -441.5365854\n2049 -510.4146341\n2050  591.4390244\n2051 -169.1951220\n2052  309.4390244\n2053  -37.4878049\n2054  102.5609756\n2055 -525.5365854\n2056   99.9268293\n2057  401.1951220\n2058   -2.3170732\n2059  783.9268293\n2060  585.5365854\n2061 -124.9024390\n2062 -103.7804878\n2063  136.2195122\n2064  828.1707317\n2065 -436.5609756\n2066 -397.1463415\n2067 -209.7317073\n2068 -424.5121951\n2069  550.2195122\n2070  103.2439024\n2071 -502.3170732\n2072 -147.9268293\n2073  251.1951220\n2074  628.9024390\n2075  151.8780488\n2076 -445.3902439\n2077  358.5121951\n2078 -194.6097561\n2079  485.7317073\n2080 -595.6341463\n2081   -0.2195122\n2082  427.8292683\n2083   -2.6585366\n2084 -698.7560976\n2085   41.6829268\n2086 -648.4146341\n2087  808.7560976\n2088 -388.8536585\n2089  168.0243902\n2090 -394.7560976\n2091  112.7560976\n2092 -146.0731707\n2093  231.1463415\n2094  157.6829268\n2095 -364.7073171\n2096 -235.6829268\n2097  -11.2439024\n2098 -111.7317073\n2099 -103.0487805\n2100 -133.2439024\n2101  566.2195122\n2102 -315.1463415\n2103 -176.1219512\n2104 -696.1707317\n2105  604.0243902\n2106 -646.3170732\n2107 -330.7073171\n2108 -659.4390244\n2109 -175.8780488\n2110  120.6585366\n2111   49.6829268\n2112 -261.3902439\n2113  340.3170732\n2114 -286.2682927\n2115 -725.7317073\n2116   20.6097561\n2117  -42.8536585\n2118  193.7317073\n2119  132.1219512\n2120  305.2926829\n2121 -527.8780488\n2122 -156.5609756\n2123  -48.2195122\n2124  543.6341463\n2125  -90.5609756\n2126 -566.4146341\n2127 -497.6341463\n2128  -39.5853659\n2129  154.9024390\n2130 -594.3658537\n2131  468.1707317\n2132  687.7317073\n2133   -4.9512195\n2134  551.0975610\n2135  866.7560976\n2136  557.1951220\n2137 -113.3414634\n2138  416.8048780\n2139  -34.0731707\n2140  -28.7073171\n2141  149.1951220\n2142  747.4878049\n2143  -56.6585366\n2144 -883.9756098\n2145  -69.0000000\n2146   61.8292683\n2147   32.0731707\n2148  133.1463415\n2149 -543.9268293\n2150  101.1463415\n2151 -538.0243902\n2152  100.4634146\n2153  -59.7317073\n2154  -95.7804878\n2155   32.7560976\n2156  745.2439024\n2157  156.1707317\n2158   61.0000000\n2159    4.0243902\n2160 -256.4146341\n2161  591.5853659\n2162  137.3414634\n2163 -430.1219512\n2164 -401.7317073\n2165  314.8536585\n2166 -511.3414634\n2167  135.1463415\n2168  117.5853659\n2169 -342.7073171\n2170 -367.9756098\n2171 -520.4634146\n2172 -416.9024390\n2173  392.0731707\n2174 -390.1219512\n2175  537.1463415\n2176 -488.4634146\n2177 -555.2926829\n2178  240.0243902\n2179  443.6341463\n2180 -578.3170732\n2181  436.0731707\n2182  113.8780488\n2183  745.4878049\n2184  104.6585366\n2185  129.2439024\n2186  -73.4390244\n2187  463.5365854\n2188   -8.4146341\n2189  454.5121951\n2190  454.9512195\n2191  350.1219512\n2192 -486.0243902\n2193  123.1951220\n2194 -480.5121951\n2195 -577.1463415\n2196  105.1463415\n2197 -289.5853659\n2198 -868.5609756\n2199 -429.5365854\n2200 -789.0975610\n2201   -7.7804878\n2202 -581.6829268\n2203  258.0243902\n2204  522.1219512\n2205 -543.5853659\n2206 -619.3414634\n2207 -684.9512195\n2208 -414.9512195\n2209  703.9756098\n2210  654.2682927\n2211  -19.4390244\n2212  201.0975610\n2213  608.5609756\n2214  421.2926829\n2215  121.7804878\n2216 -685.3902439\n2217 -578.2682927\n2218 -352.3170732\n2219 -777.2926829\n2220 -325.4878049\n2221   95.2439024\n2222 -201.6829268\n2223 -178.7560976\n2224   95.6829268\n2225  123.4390244\n2226 -526.9512195\n2227   91.4390244\n2228  -81.5365854\n2229 -338.5121951\n2230 -546.6097561\n2231 -622.3658537\n2232  319.0000000\n2233  445.7317073\n2234  142.7073171\n2235 -443.0000000\n2236 -488.2195122\n2237 -103.3902439\n2238 -167.9268293\n2239  -78.0243902\n2240  179.4390244\n2241 -576.8536585\n2242 -441.3902439\n2243  -75.3414634\n2244 -165.8292683\n2245  795.5365854\n2246    4.1707317\n2247 -160.6097561\n2248  109.6829268\n2249 -552.9512195\n2250 -123.0000000\n2251  242.1219512\n2252  107.3902439\n2253  272.6585366\n2254    7.1463415\n2255  261.6829268\n2256  -50.7560976\n2257 -496.2195122\n2258   27.2926829\n2259 -244.2195122\n2260  -63.7317073\n2261   76.3658537\n2262  120.6097561\n2263  -28.5121951\n2264 -645.0487805\n2265 -244.4146341\n2266  129.4390244\n2267 -277.2439024\n2268  232.6585366\n2269   49.5365854\n2270 -612.5609756\n2271  388.3658537\n2272 -101.8780488\n2273 -336.4146341\n2274  533.8780488\n2275  -64.9024390\n2276 -137.0000000\n2277 -292.9024390\n2278  101.3902439\n2279  480.6097561\n2280   63.9268293\n2281 -476.6097561\n2282  448.1707317\n2283 -535.7317073\n2284 -120.6097561\n2285 -411.6341463\n2286 -509.0000000\n2287 -450.6097561\n2288 -561.0000000\n2289  165.5365854\n2290  532.6585366\n2291  462.3658537\n2292 -528.0731707\n2293 -586.5121951\n2294  425.2926829\n2295   -6.4634146\n2296 -131.7804878\n2297  638.5609756\n2298  102.4146341\n2299  409.8780488\n2300  591.6341463\n2301  660.3170732\n2302  -92.4634146\n2303 -384.4146341\n2304 -458.4634146\n2305 -109.4390244\n2306 -107.7317073\n2307   11.4878049\n2308  510.5609756\n2309  545.5853659\n2310 -788.2195122\n2311   23.0487805\n2312  -94.9024390\n2313 -312.3658537\n2314 -412.6585366\n2315  196.1707317\n2316  415.4390244\n2317  112.5121951\n2318  148.9512195\n2319  -30.0731707\n2320  117.8292683\n2321  160.2682927\n2322  -53.3414634\n2323  198.0731707\n2324  102.5121951\n2325   35.0975610\n2326 -121.9756098\n2327 -149.1463415\n2328 -123.8780488\n2329   62.8536585\n2330  618.3170732\n2331  548.1219512\n2332  124.1707317\n2333 -141.2439024\n2334 -736.6097561\n2335  111.8780488\n2336  687.1463415\n2337  317.2439024\n2338   48.2682927\n2339  647.7317073\n2340 -632.0731707\n2341 -565.1951220\n2342 -301.4390244\n2343 -273.1463415\n2344  793.6829268\n2345 -230.8048780\n2346  -17.4390244\n2347   87.4390244\n2348  337.8292683\n2349 -333.5853659\n2350  327.1951220\n2351 -557.5853659\n2352 -165.1951220\n2353 -721.6829268\n2354  -17.1951220\n2355  -82.4634146\n2356  460.1219512\n2357  372.7073171\n2358  569.3414634\n2359  724.8048780\n2360  -20.0243902\n2361  171.0975610\n2362  612.1707317\n2363 -680.6097561\n2364 -138.2682927\n2365 -495.9268293\n2366  -28.8536585\n2367 -463.1463415\n2368  485.9268293\n2369 -385.1463415\n2370 -139.0975610\n2371  493.0000000\n2372   -0.1219512\n2373  -18.5121951\n2374  602.4634146\n2375 -612.4146341\n2376  127.1463415\n2377 -640.0731707\n2378  336.2195122\n2379  552.5609756\n2380 -325.7804878\n2381   -7.7804878\n2382 -316.3170732\n2383 -487.4878049\n2384  182.7073171\n2385  277.0487805\n2386  203.0000000\n2387  186.9024390\n2388 -186.2195122\n2389 -731.8292683\n2390  452.4146341\n2391 -177.7317073\n2392  -25.3902439\n2393 -671.6829268\n2394 -129.0487805\n2395   65.7804878\n2396  332.5121951\n2397  -42.5121951\n2398 -504.7560976\n2399 -132.5609756\n2400 -396.8536585\n2401  244.8536585\n2402  518.6585366\n2403  481.0975610\n2404 -102.5609756\n2405 -188.4634146\n2406 -425.3902439\n2407  659.6341463\n2408  683.9756098\n2409   47.7317073\n2410  341.3902439\n2411  -63.3902439\n2412   70.1219512\n2413   57.2439024\n2414  409.7804878\n2415  147.8292683\n2416 -128.6097561\n2417    9.1951220\n2418 -110.5121951\n2419  484.1219512\n2420 -148.6097561\n2421 -608.6097561\n2422 -646.1707317\n2423  141.6829268\n2424 -559.0487805\n2425 -115.6829268\n2426  555.6341463\n2427  -89.7804878\n2428  -65.3414634\n2429 -158.2682927\n2430  461.0487805\n2431 -245.6829268\n2432 -207.5365854\n2433 -185.3414634\n2434 -276.9512195\n2435  551.6829268\n2436  166.9512195\n2437 -699.0975610\n2438 -373.6829268\n2439 -287.5853659\n2440  407.3414634\n2441  178.9512195\n2442 -491.1463415\n2443  -52.4634146\n2444  587.6829268\n2445  484.3658537\n2446  471.0975610\n2447  646.8048780\n2448  486.0243902\n2449   25.3414634\n2450  481.2926829\n2451 -735.6341463\n2452 -256.7560976\n2453  755.1951220\n2454 -775.3414634\n2455  655.9268293\n2456  469.0000000\n2457  184.2195122\n2458  446.4146341\n2459 -274.0731707\n2460  -67.1463415\n2461  -55.9268293\n2462   54.3658537\n2463 -198.1219512\n2464 -204.2682927\n2465 -129.7317073\n2466   14.7073171\n2467   13.0487805\n2468   90.6097561\n2469 -497.6341463\n2470  640.3170732\n2471 -844.6585366\n2472  423.9268293\n2473  360.5121951\n2474 -753.6829268\n2475 -761.0487805\n2476  113.0000000\n2477  360.4146341\n2478  550.4146341\n2479  799.5365854\n2480 -139.5853659\n2481 -101.1463415\n2482   48.1219512\n2483  -63.3414634\n2484  650.7073171\n2485  -11.3902439\n2486  569.5853659\n2487 -400.4146341\n2488 -122.5609756\n2489 -622.1707317\n2490 -462.4634146\n2491   24.6585366\n2492 -698.2682927\n2493   59.6341463\n2494 -403.2926829\n2495  -29.5853659\n2496 -291.1463415\n2497  458.7560976\n2498 -223.4878049\n2499   96.5609756\n2500  -96.4634146\n2501 -922.1219512\n2502  589.3414634\n2503  -53.4390244\n2504   23.8292683\n2505   29.8292683\n2506   24.3170732\n2507   22.4634146\n2508   -5.7804878\n2509  163.4390244\n2510    2.3170732\n2511   98.8048780\n2512 -443.2439024\n2513  204.7560976\n2514  -38.3658537\n2515  -45.6341463\n2516  -56.4634146\n2517  560.9024390\n2518  292.7073171\n2519  471.7317073\n2520 -208.2195122\n2521  386.0731707\n2522  252.5121951\n2523  255.2926829\n2524 -435.0487805\n2525  156.5121951\n2526  179.5365854\n2527  603.7804878\n2528 -102.1707317\n2529 -112.5609756\n2530 -523.6829268\n2531 -259.0000000\n2532  -69.4390244\n2533    9.6829268\n2534 -378.9024390\n2535 -525.4390244\n2536   19.1463415\n2537   92.1707317\n2538 -277.1463415\n2539 -509.1463415\n2540  684.8048780\n2541  209.0000000\n2542 -500.4634146\n2543   43.6829268\n2544 -124.0243902\n2545   59.5365854\n2546 -731.8292683\n2547  489.0487805\n2548 -363.9756098\n2549  635.0000000\n2550 -279.2439024\n2551 -658.7560976\n2552  -39.3902439\n2553  183.5853659\n2554   50.8048780\n2555 -548.4146341\n2556  -59.7317073\n2557  235.8292683\n2558  -43.1463415\n2559  341.6341463\n2560   68.5609756\n2561  145.0975610\n2562  346.2195122\n2563 -147.2439024\n2564  173.0975610\n2565  554.7073171\n2566 -605.3414634\n2567 -545.8780488\n2568 -241.7804878\n2569  543.3414634\n2570 -156.1219512\n2571  455.3414634\n2572  599.7804878\n2573  -80.4146341\n2574 -168.2195122\n2575    1.0000000\n2576 -723.1951220\n2577   45.1463415\n2578  462.7073171\n2579 -106.1707317\n2580  -90.0243902\n2581  -29.5365854\n2582   92.2195122\n2583  484.0731707\n2584 -547.9268293\n2585   -8.8536585\n2586 -741.6341463\n2587 -546.0731707\n2588 -503.0000000\n2589  592.9024390\n2590 -619.5853659\n2591  441.4878049\n2592 -832.5121951\n2593  251.5365854\n2594  725.7317073\n2595  577.4390244\n2596 -129.3902439\n2597  726.2195122\n2598 -610.6585366\n2599  124.7073171\n2600 -493.0000000\n2601 -197.8780488\n2602 -400.7073171\n2603  155.3414634\n2604 -262.6097561\n2605 -444.7560976\n2606   56.1219512\n2607 -534.0243902\n2608  422.7073171\n2609 -712.6585366\n2610  849.0000000\n2611 -546.4146341\n2612 -113.6341463\n2613  440.3658537\n2614  575.5853659\n2615  107.1951220\n2616    9.8780488\n2617  802.5121951\n2618 -197.4390244\n2619  573.2926829\n2620  619.0487805\n2621  -62.2682927\n2622 -140.3658537\n2623  161.0975610\n2624  -63.3414634\n2625  -52.8536585\n2626 -585.0975610\n2627  280.3658537\n2628 -707.5853659\n2629 -506.2195122\n2630   68.7073171\n2631  843.2926829\n2632   92.5121951\n2633  150.9512195\n2634  -60.7560976\n2635 -505.4390244\n2636  -29.2439024\n2637 -464.0243902\n2638  357.4390244\n2639   62.5609756\n2640 -323.4390244\n2641   31.2439024\n2642 -628.3658537\n2643 -561.7804878\n2644  475.3414634\n2645  642.9024390\n2646 -489.6341463\n2647  616.2195122\n2648   91.7317073\n2649  353.0487805\n2650  598.8536585\n2651   24.1707317\n2652 -624.9512195\n2653   24.3170732\n2654  -18.6097561\n2655  385.3902439\n2656 -588.6097561\n2657  574.6585366\n2658 -264.5609756\n2659  132.4634146\n2660 -284.2682927\n2661 -425.8780488\n2662  434.0243902\n2663  -95.1951220\n2664 -635.6341463\n2665  -85.4878049\n2666  187.5853659\n2667  -92.5609756\n2668 -543.2926829\n2669   26.1219512\n2670  101.6829268\n2671 -669.6341463\n2672 -618.1707317\n2673    8.3170732\n2674  513.4390244\n2675  392.5121951\n2676   51.5365854\n2677  129.8292683\n2678  626.2195122\n2679 -150.4634146\n2680 -506.9512195\n2681 -323.0000000\n2682  -78.2682927\n2683  703.4390244\n2684  601.9756098\n2685 -513.6341463\n2686   24.3170732\n2687    9.6829268\n2688 -539.9756098\n2689 -423.2926829\n2690 -166.0731707\n2691  -16.3170732\n2692  -78.6097561\n2693  437.5365854\n2694  312.7560976\n2695  151.3414634\n2696 -105.9756098\n2697 -151.7804878\n2698 -370.2682927\n2699 -375.2926829\n2700  -11.0000000\n2701   83.1951220\n2702  455.0000000\n2703  170.9512195\n2704  229.9268293\n2705  669.1463415\n2706 -434.1219512\n2707  458.3658537\n2708    0.6585366\n2709 -604.4634146\n2710  143.2439024\n2711  357.0487805\n2712   49.9756098\n2713  489.3414634\n2714  577.0000000\n2715  566.4634146\n2716 -767.6341463\n2717 -225.5365854\n2718   81.5853659\n2719   74.9024390\n2720  -24.1219512\n2721 -240.1219512\n2722  204.4146341\n2723  599.7317073\n2724 -582.7073171\n2725  259.4878049\n2726  542.9024390\n2727 -412.3658537\n2728   98.6097561\n2729  182.4634146\n2730 -406.4146341\n2731  339.3902439\n2732  169.8292683\n2733  -66.6097561\n2734  -44.0731707\n2735 -112.5609756\n2736  433.6829268\n2737  127.6829268\n2738  521.7804878\n2739  695.0975610\n2740 -389.9268293\n2741  144.0243902\n2742  -77.5853659\n2743 -248.4634146\n2744 -755.3902439\n2745  -56.0243902\n2746  -88.8048780\n2747  204.4634146\n2748  -55.6341463\n2749 -363.4390244\n2750 -252.5121951\n2751 -315.8780488\n2752  -33.0975610\n2753 -159.9756098\n2754  249.5365854\n2755   77.4390244\n2756 -566.4634146\n2757   44.8048780\n2758   21.9756098\n2759 -691.0975610\n2760 -115.2439024\n2761 -240.6585366\n2762 -428.8536585\n2763 -598.9512195\n2764 -302.7073171\n2765 -150.9512195\n2766 -120.2195122\n2767 -788.7073171\n2768  551.8780488\n2769 -449.6829268\n2770  -27.5365854\n2771 -332.5609756\n2772   -6.9512195\n2773 -798.1707317\n2774 -600.5121951\n2775 -515.2439024\n2776  -77.3414634\n2777 -622.2682927\n2778 -476.9024390\n2779 -800.1219512\n2780 -611.5853659\n2781 -673.2926829\n2782 -466.3658537\n2783  165.0487805\n2784 -420.1707317\n2785   21.6341463\n2786  568.7560976\n2787 -326.9512195\n2788  208.9512195\n2789  517.5853659\n2790 -643.8780488\n2791  560.9024390\n2792 -625.7317073\n2793  460.6097561\n2794  763.0487805\n2795  356.1219512\n2796 -277.6341463\n2797  210.0731707\n2798 -563.8780488\n2799 -126.3658537\n2800  647.9268293\n2801 -318.0243902\n2802  295.3902439\n2803   21.4390244\n2804 -522.7560976\n2805 -325.8292683\n2806  191.8780488\n2807 -287.1463415\n2808  381.1951220\n2809  368.2195122\n2810  467.0975610\n2811 -248.9024390\n2812 -483.7317073\n2813 -170.2195122\n2814  510.0243902\n2815 -536.2195122\n2816  335.1951220\n2817  -56.4146341\n2818  -34.6097561\n2819 -701.0000000\n2820 -169.3414634\n2821  102.7560976\n2822  -60.0243902\n2823  -10.5121951\n2824 -155.3414634\n2825 -139.1463415\n2826   22.5609756\n2827  777.6341463\n2828   11.6829268\n2829 -447.3902439\n2830 -568.4146341\n2831 -478.1707317\n2832 -710.7073171\n2833 -118.8536585\n2834  101.5853659\n2835  591.4390244\n2836   45.1951220\n2837   81.7317073\n2838 -492.9512195\n2839 -524.3658537\n2840   90.0243902\n2841   59.2439024\n2842  108.2682927\n2843 -281.6829268\n2844 -351.1463415\n2845 -234.0731707\n2846 -129.3902439\n2847  -87.4878049\n2848   37.4878049\n2849  581.8292683\n2850 -387.6341463\n2851   71.3414634\n2852  -45.0975610\n2853 -168.4146341\n2854  664.1219512\n2855 -135.5853659\n2856 -103.9756098\n2857   -7.3902439\n2858  106.7073171\n2859  242.2682927\n2860  -80.0243902\n2861   93.7804878\n2862 -602.5121951\n2863 -454.2195122\n2864  -13.5853659\n2865  172.9024390\n2866 -241.4390244\n2867  306.2195122\n2868  347.4878049\n2869  441.7317073\n2870  -90.2195122\n2871 -497.0975610\n2872    9.6341463\n2873 -364.9512195\n2874 -556.2682927\n2875 -395.8780488\n2876  129.5853659\n2877  732.0243902\n2878  199.7317073\n2879   24.1707317\n2880 -492.7073171\n2881  655.4390244\n2882  -95.0487805\n2883   -3.2439024\n2884  445.7804878\n2885  539.5853659\n2886  494.4146341\n2887  662.2195122\n2888  394.1707317\n2889  793.5853659\n2890  -59.9268293\n2891  -67.7804878\n2892  306.4146341\n2893 -410.2682927\n2894  357.3902439\n2895  632.9024390\n2896  -51.7804878\n2897   75.2926829\n2898 -113.0000000\n2899 -129.1463415\n2900 -297.1951220\n2901 -106.5609756\n2902   90.8536585\n2903 -478.8048780\n2904 -720.4634146\n2905 -579.5853659\n2906 -300.9024390\n2907 -451.7804878\n2908  272.8536585\n2909  171.9268293\n2910 -358.1219512\n2911  806.9512195\n2912  463.1463415\n2913 -667.3414634\n2914 -698.1707317\n2915   -0.3170732\n2916  -17.8780488\n2917 -187.0000000\n2918  247.6341463\n2919 -218.3658537\n2920  326.5609756\n2921  129.0975610\n2922    3.9268293\n2923   73.9268293\n2924    4.8048780\n2925 -410.8048780\n2926  327.6829268\n2927   35.2926829\n2928 -792.1707317\n2929 -116.7073171\n2930  550.7073171\n2931  589.6829268\n2932 -132.0243902\n2933   99.6341463\n2934 -647.9268293\n2935   91.7317073\n2936  108.7560976\n2937  603.3902439\n2938  -50.1707317\n2939 -770.5121951\n2940 -246.8536585\n2941  127.0000000\n2942 -705.6341463\n2943  -52.7560976\n2944  -67.0975610\n2945 -122.6585366\n2946  613.9756098\n2947  652.6585366\n2948 -132.3170732\n2949  -83.6829268\n2950 -190.4634146\n2951  511.5853659\n2952 -127.2439024\n2953 -382.9512195\n2954 -483.1463415\n2955 -425.1951220\n2956 -163.0975610\n2957 -368.2195122\n2958 -548.8536585\n2959  556.1707317\n2960  139.3902439\n2961   53.4390244\n2962  606.7073171\n2963   21.9268293\n2964 -173.2926829\n2965  597.0975610\n2966  118.1707317\n2967 -619.4878049\n2968  132.1219512\n2969 -509.6829268\n2970 -177.5853659\n2971 -530.8048780\n2972 -491.5365854\n2973 -550.6585366\n2974  190.3170732\n2975   86.3170732\n2976  168.0243902\n2977  343.9756098\n2978  -89.9756098\n2979 -566.2195122\n2980  442.3658537\n2981  283.0000000\n2982  515.0000000\n2983 -675.0000000\n2984 -547.4878049\n2985 -226.6585366\n2986 -426.8536585\n2987 -572.0731707\n2988 -542.3170732\n2989  -81.8292683\n2990 -122.0731707\n2991 -647.6341463\n2992  319.8292683\n2993 -106.7560976\n2994  150.6097561\n2995 -283.8780488\n2996 -614.1707317\n2997  760.6585366\n2998  565.5853659\n2999 -314.4634146\n3000   34.9024390\n3001 -565.4878049\n3002   58.2682927\n3003 -140.6585366\n3004  -79.0000000\n3005  105.1463415\n3006 -401.3902439\n3007 -196.2195122\n3008  546.7560976\n3009 -446.8048780\n3010  182.2682927\n3011  354.0731707\n3012 -604.4634146\n3013  601.7804878\n3014  649.0487805\n3015  564.8048780\n3016 -441.5853659\n3017  210.8048780\n3018 -713.5365854\n3019  108.2682927\n3020  601.5365854\n3021   -7.0975610\n3022  327.6829268\n3023  593.8780488\n3024  616.3658537\n3025   26.9024390\n3026 -133.9268293\n3027  607.8780488\n3028  718.7560976\n3029 -598.7560976\n3030  597.4390244\n3031 -304.1707317\n3032 -458.8048780\n3033  693.1951220\n3034   73.2439024\n3035 -104.3658537\n3036  529.1951220\n3037  302.0243902\n3038 -660.9024390\n3039  857.8780488\n3040 -175.3902439\n3041   18.6097561\n3042 -494.1707317\n3043 -115.7317073\n3044  414.3658537\n3045  365.9756098\n3046 -500.0731707\n3047  727.3414634\n3048 -560.2195122\n3049 -458.3170732\n3050  231.5853659\n3051 -623.0000000\n3052   35.6829268\n3053  515.2926829\n3054  582.9512195\n3055 -172.3658537\n3056  113.0975610\n3057   -7.8292683\n3058 -108.4634146\n3059  -38.1707317\n3060  602.2195122\n3061 -576.4634146\n3062  130.0731707\n3063  -72.0243902\n3064 -768.2682927\n3065  296.9512195\n3066 -461.2439024\n3067  650.7560976\n3068  640.5121951\n3069  448.2195122\n3070  320.8536585\n3071 -291.2926829\n3072  -83.0000000\n3073  788.3658537\n3074  675.5365854\n3075  262.1707317\n3076  153.1951220\n3077  296.9512195\n3078 -568.3658537\n3079  601.0487805\n3080 -879.2926829\n3081  136.6585366\n3082  263.2439024\n3083   41.9268293\n3084 -135.4390244\n3085  132.6585366\n3086  -79.6341463\n3087  679.3414634\n3088  119.4390244\n3089 -512.1219512\n3090  -73.2926829\n3091   -3.6829268\n3092  490.3170732\n3093  -44.3658537\n3094   26.7073171\n3095  581.8292683\n3096  549.9268293\n3097  -72.8048780\n3098  -35.5365854\n3099   79.6829268\n3100  -44.4634146\n3101 -167.7317073\n3102  -95.9268293\n3103  503.8292683\n3104 -339.2439024\n3105  150.2682927\n3106  194.6097561\n3107 -672.9512195\n3108 -634.2682927\n3109  -73.2926829\n3110   98.7073171\n3111  121.1463415\n3112  192.3658537\n3113 -175.5853659\n3114 -308.6097561\n3115   97.1951220\n3116  -75.3414634\n3117   -8.4634146\n3118  850.1707317\n3119  451.6829268\n3120 -326.9512195\n3121  597.2926829\n3122  521.9268293\n3123  644.0731707\n3124 -133.7804878\n3125  -90.5609756\n3126 -835.8780488\n3127  526.3658537\n3128 -493.4390244\n3129 -452.0243902\n3130  513.1951220\n3131 -670.7560976\n3132 -483.6829268\n3133 -198.3170732\n3134  392.1219512\n3135  217.5853659\n3136  276.9512195\n3137 -184.6097561\n3138 -204.4146341\n3139 -454.8536585\n3140  117.7804878\n3141  573.9268293\n3142 -558.0243902\n3143  695.2439024\n3144  626.7073171\n3145   44.5609756\n3146 -385.3414634\n3147   41.0487805\n3148 -375.1463415\n3149  329.0487805\n3150  277.8780488\n3151   13.0487805\n3152  198.8536585\n3153  457.2439024\n3154  -73.6341463\n3155   14.5609756\n3156  565.0000000\n3157   12.5121951\n3158 -706.3170732\n3159  212.4146341\n3160  -96.6585366\n3161 -228.8536585\n3162  303.9756098\n3163  240.6097561\n3164  -28.4634146\n3165  318.3658537\n3166 -438.0243902\n3167  170.4634146\n3168  464.4634146\n3169 -119.9268293\n3170  344.2682927\n3171  239.2926829\n3172  309.0975610\n3173  -50.0243902\n3174  440.6585366\n3175 -217.5365854\n3176  320.4634146\n3177  502.1707317\n3178   -4.2682927\n3179 -775.9268293\n3180  -33.9268293\n3181 -234.3658537\n3182 -145.2926829\n3183  748.7560976\n3184  132.2195122\n3185 -465.0975610\n3186  -83.8292683\n3187   15.2439024\n3188 -397.7804878\n3189   61.2926829\n3190  600.2195122\n3191  188.3170732\n3192 -626.2195122\n3193 -452.3170732\n3194 -581.6829268\n3195   13.0487805\n3196 -264.9024390\n3197 -706.7073171\n3198 -285.1951220\n3199 -529.0487805\n3200  532.9512195\n3201  -94.7073171\n3202 -665.5365854\n3203 -743.2926829\n3204 -497.1463415\n3205 -251.6341463\n3206  -58.1707317\n3207 -817.9268293\n3208  -99.3414634\n3209 -449.9756098\n3210  -46.8536585\n3211 -637.8780488\n3212 -141.1463415\n3213  -93.4878049\n3214   92.8048780\n3215  -92.7073171\n3216 -315.9756098\n3217  513.6829268\n3218  -15.2926829\n3219 -814.2195122\n3220   53.2439024\n3221  735.2439024\n3222 -156.5609756\n3223 -622.5121951\n3224  -49.6341463\n3225  -72.5609756\n3226 -222.3658537\n3227  -23.9756098\n3228  774.5121951\n3229  205.3902439\n3230 -610.3658537\n3231 -129.0000000\n3232  613.1463415\n3233 -529.4878049\n3234 -426.0243902\n3235  147.3414634\n3236  484.7560976\n3237 -191.9756098\n3238    5.2926829\n3239 -181.3902439\n3240 -181.2439024\n3241  124.8536585\n3242 -626.3658537\n3243  -78.7560976\n3244  138.3170732\n3245  119.6829268\n3246 -116.8536585\n3247   74.5609756\n3248  408.4146341\n3249 -389.9268293\n3250 -200.1707317\n3251 -116.6097561\n3252 -188.8048780\n3253 -167.0487805\n3254 -384.7073171\n3255    1.0975610\n3256 -519.0975610\n3257  492.4634146\n3258  -96.3170732\n3259   91.1951220\n3260 -306.4146341\n3261 -501.3902439\n3262 -588.0243902\n3263  -13.5853659\n3264   87.9268293\n3265 -135.2926829\n3266 -652.6585366\n3267  -60.7073171\n3268 -468.1707317\n3269  602.4634146\n3270  696.5121951\n3271 -412.5609756\n3272  663.2439024\n3273  411.5853659\n3274  -88.6585366\n3275 -618.1707317\n3276  398.4146341\n3277 -596.5121951\n3278   89.5853659\n3279  378.1219512\n3280 -107.5365854\n3281 -667.5853659\n3282  156.4146341\n3283 -450.3658537\n3284 -260.8048780\n3285  555.1951220\n3286   43.6341463\n3287  -95.3414634\n3288 -110.7560976\n3289 -422.9024390\n3290 -691.2926829\n3291  519.7804878\n3292  103.7804878\n3293  375.0487805\n3294   83.2926829\n3295  -54.2682927\n3296 -118.1219512\n3297  111.3414634\n3298 -557.9756098\n3299  252.5121951\n3300  282.2195122\n3301 -134.1219512\n3302 -139.9756098\n3303   77.8780488\n3304  133.1463415\n3305 -543.7317073\n3306 -874.9512195\n3307 -488.8048780\n3308   69.6829268\n3309 -361.8780488\n3310  494.7073171\n3311  557.4390244\n3312  917.2926829\n3313  723.1951220\n3314   39.3414634\n3315  586.3658537\n3316 -143.3902439\n3317   79.3902439\n3318  460.3170732\n3319 -529.8780488\n3320  227.8780488\n3321  540.8536585\n3322  112.7073171\n3323 -170.0243902\n3324  195.4878049\n3325  102.7073171\n3326  -62.8048780\n3327  350.8048780\n3328  651.2926829\n3329   31.8292683\n3330 -612.1219512\n3331  701.1951220\n3332 -226.6097561\n3333  -55.2926829\n3334 -462.5609756\n3335 -351.9756098\n3336  -44.0243902\n3337  158.6097561\n3338 -237.4878049\n3339  100.8536585\n3340  541.4878049\n3341  416.5121951\n3342  -49.9756098\n3343  283.9756098\n3344 -323.3414634\n3345 -597.4390244\n3346   72.2682927\n3347   25.1951220\n3348 -439.0487805\n3349  709.4390244\n3350 -198.5609756\n3351  105.2439024\n3352  527.6829268\n3353   29.5365854\n3354  383.2439024\n3355 -279.0975610\n3356 -159.9268293\n3357    1.0487805\n3358  330.4146341\n3359 -568.8048780\n3360  538.2682927\n3361 -557.9268293\n3362  -18.1219512\n3363  316.6585366\n3364  500.4146341\n3365  -54.0243902\n3366  178.3170732\n3367 -159.2439024\n3368   97.7804878\n3369 -760.5121951\n3370  460.7560976\n3371 -623.7317073\n3372  608.5121951\n3373  -30.6585366\n3374   16.6585366\n3375  624.2682927\n3376  740.2682927\n3377 -322.5609756\n3378   77.5365854\n3379 -224.3658537\n3380   87.5853659\n3381 -421.7317073\n3382 -596.5121951\n3383 -123.9756098\n3384 -177.1951220\n3385  -62.5121951\n3386  439.4878049\n3387 -649.8780488\n3388 -368.4146341\n3389  -96.4634146\n3390  564.6585366\n3391 -491.0000000\n3392 -381.9756098\n3393  -91.2439024\n3394 -140.6097561\n3395  -92.3658537\n3396 -533.8292683\n3397 -499.8292683\n3398 -236.9024390\n3399  -43.2439024\n3400   74.3170732\n3401   46.4146341\n3402 -158.5121951\n3403  204.8536585\n3404 -155.6341463\n3405 -299.6829268\n3406  179.8292683\n3407 -253.7804878\n3408 -521.0975610\n3409 -309.6829268\n3410  526.8048780\n3411 -217.2926829\n3412   12.1707317\n3413  722.1707317\n3414   75.8292683\n3415  150.2682927\n3416  114.1707317\n3417  294.7073171\n3418  469.1951220\n3419 -495.0487805\n3420  541.3414634\n3421   42.7073171\n3422 -576.2195122\n3423  510.8048780\n3424 -459.0975610\n3425 -443.1463415\n3426 -737.0000000\n3427  -85.1463415\n3428 -443.2926829\n3429   95.8780488\n3430  677.0000000\n3431  -77.0975610\n3432 -566.5121951\n3433 -149.5365854\n3434  677.7804878\n3435  463.3414634\n3436  559.6341463\n3437   46.4146341\n3438 -453.4390244\n3439  685.5365854\n3440  457.9268293\n3441   25.9756098\n3442  132.2682927\n3443 -117.3902439\n3444  673.2926829\n3445  594.5609756\n3446 -314.8536585\n3447 -565.0487805\n3448  -21.0000000\n3449 -536.1219512\n3450  502.8536585\n3451 -129.9756098\n3452 -245.8292683\n3453   57.6829268\n3454   34.1219512\n3455  552.3170732\n3456  -54.5609756\n3457 -593.2926829\n3458 -593.8780488\n3459  484.7560976\n3460 -564.2682927\n3461 -662.5121951\n3462 -181.8292683\n3463 -162.8536585\n3464 -314.8536585\n3465 -102.6097561\n3466 -487.0000000\n3467  335.5365854\n3468   46.8536585\n3469  185.0975610\n3470 -672.7560976\n3471 -161.6341463\n3472  -18.7073171\n3473 -217.6341463\n3474  636.2195122\n3475  -92.4146341\n3476  142.6097561\n3477  306.2195122\n3478 -215.3902439\n3479 -354.1219512\n3480 -531.5365854\n3481  763.2926829\n3482  783.2439024\n3483   86.7560976\n3484 -545.2439024\n3485   20.9512195\n3486  193.3414634\n3487  352.2195122\n3488  -68.8536585\n3489 -636.7560976\n3490 -531.6829268\n3491  292.6097561\n3492  165.5853659\n3493 -535.8780488\n3494 -678.9024390\n3495  266.7560976\n3496  442.6097561\n3497 -288.7560976\n3498  418.1219512\n3499  220.4146341\n3500   25.2926829\n3501  -66.0731707\n3502  683.3902439\n3503  582.3170732\n3504  725.0487805\n3505  365.0975610\n3506  242.0731707\n3507   55.9756098\n3508 -515.9756098\n3509 -255.5365854\n3510 -516.5121951\n3511   43.4390244\n3512 -644.9512195\n3513 -381.2926829\n3514   51.1951220\n3515 -490.3170732\n3516   -5.3902439\n3517   79.9268293\n3518  372.9024390\n3519  263.8780488\n3520   86.8536585\n3521 -454.4146341\n3522 -441.1951220\n3523 -210.6585366\n3524 -114.5121951\n3525 -151.0975610\n3526  -53.0975610\n3527 -108.7073171\n3528 -139.5365854\n3529 -357.2439024\n3530  610.8536585\n3531  699.4878049\n3532  864.2195122\n3533 -150.8048780\n3534  882.7560976\n3535 -501.4390244\n3536  -12.7073171\n3537  282.6585366\n3538  -78.3658537\n3539   -5.0975610\n3540  -18.2682927\n3541  390.0243902\n3542 -601.7317073\n3543  166.1219512\n3544  481.2926829\n3545   -1.1951220\n3546 -135.1463415\n3547  -28.3170732\n3548 -390.4146341\n3549  622.1219512\n3550   16.5121951\n3551   72.8048780\n3552   18.2682927\n3553 -651.0000000\n3554 -436.8536585\n3555   73.8292683\n3556  404.4634146\n3557   17.1951220\n3558  194.2682927\n3559   -4.1219512\n3560  385.8292683\n3561 -678.9512195\n3562 -672.4634146\n3563  464.8536585\n3564 -586.3658537\n3565 -551.7317073\n3566 -425.1951220\n3567   52.3658537\n3568  513.7317073\n3569 -669.2439024\n3570 -312.2682927\n3571  113.3902439\n3572  -83.4878049\n3573  -31.3902439\n3574 -128.1219512\n3575   14.0731707\n3576 -429.2439024\n3577  627.8780488\n3578 -189.8780488\n3579  524.4146341\n3580  -99.7804878\n3581 -615.1463415\n3582  -90.1707317\n3583 -736.8048780\n3584  413.8292683\n3585    7.6341463\n3586 -154.1219512\n3587  246.5121951\n3588 -327.0975610\n3589  101.1951220\n3590  687.5365854\n3591 -464.1219512\n3592 -308.1707317\n3593  548.9512195\n3594   75.2926829\n3595  186.6585366\n3596   33.6829268\n3597  729.5365854\n3598  -55.0000000\n3599 -294.4146341\n3600  -53.7317073\n3601  143.0487805\n3602 -258.5609756\n3603   33.3902439\n3604  -33.1463415\n3605 -470.6097561\n3606 -554.4146341\n3607   52.1707317\n3608   31.6341463\n3609    2.3658537\n3610 -758.8536585\n3611  457.7804878\n3612  175.6341463\n3613  -68.8048780\n3614  346.5121951\n3615 -574.1219512\n3616 -124.8048780\n3617 -384.4146341\n3618  588.3658537\n3619  765.2926829\n3620  -15.9756098\n3621  217.3414634\n3622  534.1219512\n3623 -127.1951220\n3624  605.5853659\n3625 -739.8780488\n3626   78.7560976\n3627 -603.0487805\n3628   91.9756098\n3629 -627.1463415\n3630  262.5609756\n3631   -2.3658537\n3632   55.0000000\n3633  622.9024390\n3634 -675.1463415\n3635  327.7804878\n3636  554.5609756\n3637  -51.9268293\n3638 -368.5121951\n3639  396.8048780\n3640  413.0487805\n3641  -43.0975610\n3642  132.0243902\n3643  -53.3414634\n3644 -172.3658537\n3645   45.2926829\n3646   77.0487805\n3647 -245.5853659\n3648 -458.6097561\n3649   55.0487805\n3650 -104.8048780\n3651  652.6097561\n3652  -80.6585366\n3653 -162.9024390\n3654  126.3170732\n3655 -483.7317073\n3656  750.1219512\n3657 -101.5365854\n3658  243.9756098\n3659  561.4878049\n3660  -39.5365854\n3661  423.1951220\n3662  239.6829268\n3663  235.8292683\n3664  226.9024390\n3665  400.3170732\n3666 -663.4878049\n3667   19.1951220\n3668  245.0000000\n3669  259.7317073\n3670   48.7073171\n3671 -750.0243902\n3672  -58.4634146\n3673 -606.9512195\n3674  150.4146341\n3675  333.1951220\n3676   42.0243902\n3677   44.4146341\n3678  102.8048780\n3679  648.6097561\n3680 -285.8292683\n3681  739.3414634\n3682  618.7073171\n3683  305.7804878\n3684  595.6829268\n3685 -221.5365854\n3686 -551.4878049\n3687 -402.8536585\n3688 -108.6585366\n3689 -602.9512195\n3690  264.4634146\n3691  201.6341463\n3692 -772.4146341\n3693 -218.6585366\n3694  203.5365854\n3695  243.8292683\n3696   53.0487805\n3697  562.7560976\n3698 -525.9756098\n3699   23.4878049\n3700  702.5121951\n3701  569.2439024\n3702  127.6341463\n3703 -449.0000000\n3704  155.4878049\n3705  143.0000000\n3706  108.9024390\n3707    0.1707317\n3708  679.7804878\n3709  203.6829268\n3710  706.4146341\n3711   37.8780488\n3712 -345.8292683\n3713  333.9756098\n3714  141.4390244\n3715 -100.0731707\n3716 -455.0000000\n3717 -410.9024390\n3718 -496.0731707\n3719 -300.9512195\n3720  548.5609756\n3721  107.3902439\n3722 -315.8780488\n3723 -420.2682927\n3724  162.7073171\n3725 -591.7804878\n3726  -18.4634146\n3727 -492.6585366\n3728  342.2682927\n3729 -721.3902439\n3730  -17.2439024\n3731  564.3658537\n3732  751.8292683\n3733   48.4146341\n3734   80.0731707\n3735 -564.1707317\n3736  655.7317073\n3737 -506.2682927\n3738  139.0000000\n3739  414.9512195\n3740   17.6341463\n3741 -540.8048780\n3742  -48.4146341\n3743    5.5365854\n3744   95.2926829\n3745 -547.1951220\n3746  426.0731707\n3747  151.5365854\n3748  521.9756098\n3749 -371.9268293\n3750 -429.2926829\n3751  -41.5365854\n3752  379.2439024\n3753 -740.9024390\n3754  455.7804878\n3755  505.0000000\n3756  -70.7560976\n3757  -44.2195122\n3758 -363.0975610\n3759 -135.6829268\n3760 -536.1219512\n3761  291.8780488\n3762   86.0731707\n3763  135.4878049\n3764 -648.8536585\n3765  185.2926829\n3766  -42.3170732\n3767 -639.7317073\n3768  -67.6829268\n3769  -29.2926829\n3770    6.1707317\n3771  159.6829268\n3772   45.0000000\n3773   53.3414634\n3774 -579.7804878\n3775 -667.4390244\n3776  648.8048780\n3777  391.0975610\n3778  586.0243902\n3779 -233.5853659\n3780  622.2682927\n3781 -158.7560976\n3782 -525.5365854\n3783  166.9512195\n3784   85.7804878\n3785  726.3658537\n3786  431.6829268\n3787  221.4390244\n3788 -733.1463415\n3789  453.0487805\n3790 -467.8780488\n3791 -138.6585366\n3792  -33.8780488\n3793  402.0243902\n3794 -191.0975610\n3795  -41.0000000\n3796 -306.1707317\n3797  -10.1219512\n3798 -576.3658537\n3799 -631.0975610\n3800  150.9512195\n3801  -56.8048780\n3802 -191.8780488\n3803   -7.6829268\n3804 -150.0731707\n3805   49.6341463\n3806 -171.6341463\n3807   13.3414634\n3808 -650.9512195\n3809 -645.1463415\n3810  355.2439024\n3811  578.6097561\n3812  200.9512195\n3813  -17.9756098\n3814   80.4146341\n3815 -498.5609756\n3816 -277.1951220\n3817   19.7804878\n3818 -601.2439024\n3819  333.1951220\n3820   16.5609756\n3821   68.7560976\n3822 -433.3902439\n3823  -18.5121951\n3824  336.2195122\n3825  618.4146341\n3826  -50.9024390\n3827 -147.3414634\n3828  695.0000000\n3829  148.8048780\n3830  133.3414634\n3831 -751.0487805\n3832  279.4390244\n3833 -392.2195122\n3834 -206.7073171\n3835   78.1219512\n3836  -37.7804878\n3837 -487.1951220\n3838  567.3414634\n3839 -162.0731707\n3840  -69.3902439\n3841 -280.3658537\n3842  575.2439024\n3843  454.2195122\n3844  -10.4634146\n3845 -261.8292683\n3846 -142.2682927\n3847 -436.9512195\n3848  -37.2439024\n3849  -61.6829268\n3850 -417.7804878\n3851  781.5853659\n3852 -456.5121951\n3853  -29.0000000\n3854  394.3658537\n3855 -383.0975610\n3856 -531.7317073\n3857  668.5121951\n3858  514.7073171\n3859 -626.9024390\n3860  280.6097561\n3861 -214.0243902\n3862  693.4878049\n3863  553.5853659\n3864  538.4146341\n3865   99.5853659\n3866  720.8048780\n3867  616.6585366\n3868 -141.5853659\n3869  -47.2926829\n3870 -624.4634146\n3871   54.5609756\n3872  508.8536585\n3873 -482.1219512\n3874  116.2682927\n3875 -200.9024390\n3876  291.0000000\n3877   43.1951220\n3878  769.8780488\n3879 -492.3170732\n3880   71.1463415\n3881  182.2195122\n3882  552.9024390\n3883  534.5609756\n3884   54.9512195\n3885 -164.9512195\n3886 -118.2682927\n3887  591.1951220\n3888 -434.3658537\n3889    8.0243902\n3890 -229.1951220\n3891 -662.4146341\n3892  -50.9024390\n3893 -171.2926829\n3894  -60.1219512\n3895 -702.5121951\n3896 -200.1707317\n3897  106.1219512\n3898  121.8292683\n3899 -640.1219512\n3900  -19.2439024\n3901   65.7804878\n3902   30.4634146\n3903  -10.3170732\n3904  221.2439024\n3905 -756.5609756\n3906 -512.4634146\n3907   54.2195122\n3908  467.3414634\n3909 -618.4634146\n3910    3.1463415\n3911  281.4878049\n3912   35.7317073\n3913  135.3414634\n3914  155.2926829\n3915   90.8048780\n3916  452.2195122\n3917  440.8536585\n3918 -231.0487805\n3919  547.0000000\n3920  109.3414634\n3921  245.9268293\n3922   72.1219512\n3923 -350.9024390\n3924   78.5121951\n3925  571.6341463\n3926  150.1707317\n3927 -136.3170732\n3928  525.9268293\n3929 -440.5121951\n3930 -636.2195122\n3931 -595.8780488\n3932 -182.9024390\n3933   14.2682927\n3934 -382.8536585\n3935  487.7804878\n3936 -336.9512195\n3937  671.2926829\n3938 -105.0000000\n3939 -597.1951220\n3940   38.4146341\n3941 -275.4390244\n3942 -675.6829268\n3943 -275.8292683\n3944  515.5853659\n3945  100.1219512\n3946  448.4146341\n3947  462.3658537\n3948  613.0000000\n3949 -270.1219512\n3950 -527.1463415\n3951 -131.1463415\n3952 -104.0243902\n3953  -43.1463415\n3954  107.8292683\n3955  -67.1463415\n3956   92.9512195\n3957  772.0243902\n3958  257.0487805\n3959   62.7560976\n3960  496.6585366\n3961 -124.0243902\n3962   47.4390244\n3963 -272.7073171\n3964  800.9512195\n3965 -600.9512195\n3966  313.3414634\n3967  578.1219512\n3968  630.6585366\n3969  175.6829268\n3970  319.4878049\n3971  333.9268293\n3972    8.8536585\n3973   32.0243902\n3974   24.8048780\n3975  292.7073171\n3976 -590.3658537\n3977 -226.3658537\n3978 -169.2439024\n3979  187.2926829\n3980   -9.2926829\n3981 -286.8048780\n3982  676.3170732\n3983  103.8292683\n3984 -117.9756098\n3985 -235.3414634\n3986  265.4390244\n3987    7.1463415\n3988  -15.0487805\n3989  856.5609756\n3990  -67.7804878\n3991  -27.6341463\n3992  137.0487805\n3993  114.1707317\n3994   26.7073171\n3995  -42.9024390\n3996 -659.5365854\n3997   66.2195122\n3998  587.2439024\n3999  109.7804878\n4000 -451.0000000\n4001  773.6341463\n4002  -25.8292683\n4003  331.1463415\n4004 -301.4878049\n4005   83.7804878\n4006   34.2682927\n4007  -16.4634146\n4008 -136.4634146\n4009  720.7560976\n4010   84.8536585\n4011 -384.3658537\n4012   65.6341463\n4013  640.7560976\n4014   41.3414634\n4015   28.1707317\n4016    5.6829268\n4017 -627.9756098\n4018 -792.0731707\n4019 -209.7804878\n4020 -679.5365854\n4021  256.3658537\n4022   78.3658537\n4023 -865.0000000\n4024  123.2926829\n4025 -245.1951220\n4026  283.5365854\n4027  599.2439024\n4028 -219.4878049\n4029 -482.5121951\n4030 -123.4390244\n4031  209.5365854\n4032 -667.3902439\n4033   54.5121951\n4034  149.5365854\n4035  452.9512195\n4036 -310.3170732\n4037   60.8536585\n4038 -772.1707317\n4039  343.4878049\n4040 -248.5609756\n4041  680.6097561\n4042  457.6341463\n4043  439.5853659\n4044 -785.9268293\n4045 -682.6097561\n4046 -126.3658537\n4047 -318.9024390\n4048  616.4146341\n4049   68.9024390\n4050  431.1951220\n4051   30.6585366\n4052 -702.3170732\n4053 -432.5609756\n4054 -509.7804878\n4055 -203.2439024\n4056  579.4878049\n4057  -10.1707317\n4058 -707.3902439\n4059  168.6585366\n4060  661.8292683\n4061  702.4146341\n4062  190.9024390\n4063 -739.5365854\n4064  514.1707317\n4065  -30.6585366\n4066  403.4390244\n4067  -81.3414634\n4068 -775.8292683\n4069 -529.0000000\n4070  430.3658537\n4071  105.1951220\n4072 -576.9512195\n4073  643.8292683\n4074 -291.9268293\n4075  451.0975610\n4076  -26.4634146\n4077 -501.4878049\n4078  121.7804878\n4079  304.2195122\n4080  566.1707317\n4081  -20.1707317\n4082  274.1707317\n4083 -150.7073171\n4084 -450.0243902\n4085 -661.0487805\n4086  244.3658537\n4087 -477.8292683\n4088  -92.3658537\n4089 -219.5365854\n4090  601.9268293\n4091 -481.0000000\n4092 -422.1219512\n4093  223.0487805\n4094  525.4390244\n4095  243.0975610\n4096 -353.6341463\n4097 -345.2926829\n4098  379.0975610\n4099 -629.3414634\n4100  182.1219512\n4101 -161.6829268\n4102  463.8780488\n4103 -135.1463415\n4104 -588.5609756\n4105 -393.7804878\n4106  -61.0000000\n4107  453.4390244\n4108 -704.9024390\n4109  -13.4878049\n4110  -29.5853659\n4111  404.5609756\n4112    1.1951220\n4113  702.0731707\n4114 -660.9512195\n4115  492.8048780\n4116  682.2195122\n4117    8.8536585\n4118 -547.0000000\n4119   82.5121951\n4120   37.1463415\n4121 -838.4146341\n4122  458.6585366\n4123  -44.3658537\n4124 -143.0487805\n4125  180.6097561\n4126  164.7560976\n4127  537.5365854\n4128 -733.3414634\n4129  605.0000000\n4130 -687.2439024\n4131 -528.9024390\n4132 -108.0243902\n4133 -507.6341463\n4134  701.3414634\n4135  282.7560976\n4136  581.7317073\n4137  581.5853659\n4138 -275.0487805\n4139 -456.0731707\n4140  583.0000000\n4141   45.9268293\n4142  -12.5609756\n4143 -369.7804878\n4144  164.9024390\n4145  220.0243902\n4146  105.0000000\n4147  349.4878049\n4148  105.5365854\n4149  709.8292683\n4150  447.8292683\n4151 -386.2195122\n4152  425.9268293\n4153 -199.0975610\n4154   28.7073171\n4155 -750.3658537\n4156   79.6341463\n4157  428.9024390\n4158  777.0000000\n4159  -93.2926829\n4160  642.3170732\n4161  741.5365854\n4162   19.4390244\n4163  590.4634146\n4164 -692.6097561\n4165  731.3902439\n4166  332.2682927\n4167   -7.8292683\n4168  556.2682927\n4169 -193.3902439\n4170  -35.5365854\n4171   -2.6097561\n4172 -205.3902439\n4173 -759.2439024\n4174  104.7560976\n4175 -426.5609756\n4176 -333.2439024\n4177 -159.3414634\n4178 -466.5609756\n4179   58.1219512\n4180   82.5121951\n4181  -79.5365854\n4182  426.3170732\n4183 -133.8292683\n4184  621.3902439\n4185 -218.3658537\n4186 -596.3170732\n4187 -291.9756098\n4188 -772.2195122\n4189  596.2195122\n4190  570.9024390\n4191  129.8780488\n4192 -199.0000000\n4193 -160.4634146\n4194 -393.2439024\n4195 -292.8536585\n4196  528.4634146\n4197  669.3902439\n4198   44.4146341\n4199  261.0487805\n4200  555.1951220\n4201  -22.5121951\n4202 -603.4390244\n4203 -371.6829268\n4204 -278.5609756\n4205   63.1951220\n4206 -126.7560976\n4207   30.3658537\n4208  -68.0731707\n4209  -19.5853659\n4210  -36.9024390\n4211    1.6829268\n4212  517.7317073\n4213  -19.0975610\n4214   37.4878049\n4215  210.3170732\n4216  189.2926829\n4217  314.2195122\n4218  732.9512195\n4219   -4.3170732\n4220  196.8536585\n4221 -490.9512195\n4222 -137.0487805\n4223 -721.2439024\n4224   26.6585366\n4225  -27.0487805\n4226 -218.6585366\n4227  491.9756098\n4228 -624.0731707\n4229  352.8536585\n4230  325.0000000\n4231  642.5121951\n4232 -509.2926829\n4233  626.9512195\n4234  319.7317073\n4235  552.8048780\n4236  488.4634146\n4237   72.2682927\n4238 -175.7317073\n4239 -514.1707317\n4240 -812.4146341\n4241  112.4146341\n4242  530.9024390\n4243 -159.5365854\n4244 -118.7560976\n4245 -110.8048780\n4246  162.6097561\n4247  519.1951220\n4248  175.3902439\n4249   -7.0487805\n4250   81.9268293\n4251 -514.9512195\n4252 -355.6829268\n4253 -632.3170732\n4254  634.9512195\n4255 -732.1707317\n4256  492.5609756\n4257  256.0731707\n4258  602.3658537\n4259   65.7317073\n4260  699.6341463\n4261   12.1707317\n4262  629.2926829\n4263 -133.0000000\n4264  579.2926829\n4265  145.1463415\n4266 -309.1463415\n4267  -70.6097561\n4268  -66.2682927\n4269  -47.7804878\n4270  474.7073171\n4271 -147.8780488\n4272   13.0000000\n4273 -349.6341463\n4274 -470.7073171\n4275  208.6097561\n4276  517.1951220\n4277 -673.8292683\n4278 -807.3902439\n4279  713.8780488\n4280  226.6097561\n4281 -162.1219512\n4282  -92.6097561\n4283 -578.8536585\n4284 -712.1707317\n4285  519.2926829\n4286 -741.4390244\n4287   86.6097561\n4288  234.4634146\n4289 -419.1463415\n4290 -302.2682927\n4291 -489.2926829\n4292 -337.1951220\n4293  469.2439024\n4294 -335.1951220\n4295 -111.2439024\n4296  532.3658537\n4297  187.5365854\n4298  111.0487805\n4299  -31.4390244\n4300 -581.3902439\n4301  159.8780488\n4302   99.0000000\n4303  688.1707317\n4304  -24.0243902\n4305  501.0000000\n4306 -120.8536585\n4307  199.4878049\n4308  -40.4146341\n4309 -120.2682927\n4310    7.4390244\n4311 -567.4390244\n4312  -95.5853659\n4313   44.2195122\n4314  -26.4146341\n4315  407.2926829\n4316 -195.7317073\n4317  -92.1707317\n4318 -515.8292683\n4319 -360.0731707\n4320 -377.5853659\n4321  480.2195122\n4322  -60.0731707\n4323  540.9512195\n4324   13.4878049\n4325  801.3902439\n4326  -74.7560976\n4327 -645.3902439\n4328  430.1707317\n4329 -637.0000000\n4330 -433.1463415\n4331 -518.6097561\n4332   30.4146341\n4333  277.6829268\n4334  231.0975610\n4335 -371.6341463\n4336  420.5609756\n4337  -45.3902439\n4338 -745.1463415\n4339   26.2195122\n4340   68.4146341\n4341  677.8292683\n4342   31.9268293\n4343 -317.6829268\n4344 -711.8780488\n4345   39.9756098\n4346  110.1707317\n4347 -650.3658537\n4348  354.0731707\n4349  582.7073171\n4350   51.1951220\n4351  493.1951220\n4352  115.0487805\n4353 -637.2439024\n4354  820.6585366\n4355  351.7804878\n4356   91.3902439\n4357   81.0000000\n4358  426.0731707\n4359    4.4146341\n4360  251.2439024\n4361  793.5853659\n4362 -473.5853659\n4363 -631.1463415\n4364 -687.3902439\n4365 -133.2926829\n4366   14.8048780\n4367  765.5853659\n4368 -421.2926829\n4369 -680.2682927\n4370  785.7317073\n4371 -120.5121951\n4372  588.7560976\n4373 -167.7804878\n4374 -142.4146341\n4375  635.6341463\n4376  602.2195122\n4377  567.6341463\n4378  -29.4878049\n4379 -187.2439024\n4380   55.0000000\n4381 -689.8780488\n4382  560.3658537\n4383  497.7804878\n4384 -567.0487805\n4385   43.0487805\n4386 -642.2682927\n4387 -433.5365854\n4388   67.2439024\n4389  669.0975610\n4390  378.3658537\n4391   97.3902439\n4392 -339.5853659\n4393 -504.3658537\n4394  -78.8536585\n4395  119.4878049\n4396   42.6097561\n4397   51.0487805\n4398 -261.0975610\n4399 -786.4146341\n4400  -10.8048780\n4401  -66.2195122\n4402  290.7073171\n4403  163.3414634\n4404 -493.9756098\n4405  -65.0000000\n4406   44.1707317\n4407  747.0975610\n4408  634.3170732\n4409  450.6585366\n4410  653.6829268\n4411  555.2439024\n4412 -456.2195122\n4413  -84.3658537\n4414 -685.7317073\n4415  644.4634146\n4416  -70.3658537\n4417 -376.0243902\n4418  594.9512195\n4419  -29.6341463\n4420  495.7317073\n4421  -86.7560976\n4422    4.7560976\n4423  516.0731707\n4424 -240.2682927\n4425  370.7560976\n4426  136.5609756\n4427 -497.0000000\n4428  186.4146341\n4429  786.6097561\n4430 -535.0487805\n4431  773.3902439\n4432  190.8048780\n4433  207.4390244\n4434 -194.3658537\n4435 -193.0975610\n4436  225.3902439\n4437  332.9024390\n4438 -416.4634146\n4439   17.5365854\n4440  349.5853659\n4441   84.5121951\n4442  157.9268293\n4443  125.3414634\n4444 -528.3658537\n4445   88.6097561\n4446  -21.0975610\n4447  -32.0731707\n4448  600.4146341\n4449   41.3414634\n4450  433.5853659\n4451  606.3658537\n4452 -518.4146341\n4453 -275.6341463\n4454  -13.3414634\n4455 -371.5365854\n4456 -595.2926829\n4457  129.4878049\n4458  533.8780488\n4459 -830.2195122\n4460 -469.1463415\n4461  -84.9024390\n4462  -78.2195122\n4463   17.9268293\n4464   92.2682927\n4465  127.8292683\n4466  -36.0243902\n4467 -833.1463415\n4468  250.2682927\n4469  301.6341463\n4470   10.7073171\n4471  325.1951220\n4472   81.7317073\n4473  511.2926829\n4474  115.6341463\n4475  186.6585366\n4476 -246.5121951\n4477 -346.7560976\n4478  -17.6341463\n4479  162.3658537\n4480  341.8780488\n4481  499.4878049\n4482 -126.0243902\n4483 -460.7073171\n4484 -138.3170732\n4485  421.6341463\n4486 -633.0000000\n4487   70.6097561\n4488  324.7073171\n4489  180.2195122\n4490  433.9756098\n4491    9.5853659\n4492    5.9268293\n4493   73.9268293\n4494  668.0243902\n4495  -40.2682927\n4496 -413.3902439\n4497   59.1463415\n4498  -63.0487805\n4499 -206.5609756\n4500 -671.0000000\n4501 -301.8780488\n4502  206.8048780\n4503  579.9756098\n4504 -295.1463415\n4505    1.7804878\n4506  635.7804878\n4507 -684.0731707\n4508  523.4390244\n4509  249.4390244\n4510 -289.1951220\n4511 -352.0243902\n4512  164.3658537\n4513 -463.3414634\n4514 -503.0000000\n4515   21.5853659\n4516   41.2926829\n4517  249.4878049\n4518   77.4390244\n4519 -605.5853659\n4520   10.0731707\n4521 -625.0487805\n4522  196.2682927\n4523  123.9268293\n4524 -139.8292683\n4525 -684.5121951\n4526   96.1219512\n4527 -164.0243902\n4528    3.0487805\n4529 -337.9756098\n4530   23.4390244\n4531  162.0243902\n4532 -356.3170732\n4533  292.4146341\n4534   -4.9024390\n4535 -155.3902439\n4536 -328.4146341\n4537  454.2682927\n4538  139.9268293\n4539 -287.8780488\n4540 -200.6585366\n4541 -618.2195122\n4542 -609.6341463\n4543 -400.1219512\n4544  111.3414634\n4545  150.6585366\n4546  636.6585366\n4547 -408.8048780\n4548  655.0000000\n4549 -250.8048780\n4550   91.0000000\n4551  -17.3902439\n4552 -746.1219512\n4553   18.2682927\n4554  625.1951220\n4555 -295.1463415\n4556   94.8536585\n4557 -273.6341463\n4558 -187.7317073\n4559 -116.4146341\n4560  -22.8048780\n4561 -531.7317073\n4562    7.1463415\n4563 -639.5853659\n4564  223.3902439\n4565  -61.4390244\n4566  162.4146341\n4567   87.7804878\n4568  385.8292683\n4569  315.5853659\n4570  743.6341463\n4571   -7.2439024\n4572  116.3658537\n4573  271.0000000\n4574  465.2439024\n4575 -151.3902439\n4576   12.0243902\n4577  -65.3414634\n4578 -713.4390244\n4579 -170.6585366\n4580  258.1707317\n4581  112.9512195\n4582  -17.1463415\n4583 -235.6341463\n4584  627.8292683\n4585  660.7560976\n4586   78.8048780\n4587  705.1951220\n4588 -237.6341463\n4589   20.0243902\n4590 -453.1463415\n4591  203.8780488\n4592 -182.9512195\n4593 -540.2682927\n4594  195.2439024\n4595 -132.0731707\n4596   92.7073171\n4597  582.7560976\n4598  -88.8536585\n4599 -576.2195122\n4600  357.0000000\n4601 -597.0000000\n4602 -471.4878049\n4603 -565.1951220\n4604 -754.4634146\n4605   57.2926829\n4606 -509.9268293\n4607 -194.7560976\n4608 -154.1219512\n4609 -464.7073171\n4610   71.9756098\n4611  -91.0000000\n4612  129.2926829\n4613 -120.3658537\n4614  499.6829268\n4615  -70.2682927\n4616 -113.4390244\n4617  496.0243902\n4618  560.3658537\n4619  -82.1219512\n4620  531.1463415\n4621 -165.6829268\n4622  135.7317073\n4623 -265.0000000\n4624 -102.1707317\n4625 -467.8780488\n4626 -796.9024390\n4627  188.3170732\n4628 -176.8048780\n4629  588.0243902\n4630  643.4390244\n4631  -28.7073171\n4632 -662.3658537\n4633 -144.0243902\n4634 -772.1707317\n4635 -160.9512195\n4636  588.8048780\n4637 -104.0243902\n4638  -35.9756098\n4639    4.2682927\n4640  336.2682927\n4641 -605.3902439\n4642 -611.5365854\n4643  632.3658537\n4644  -27.2439024\n4645 -303.2926829\n4646 -131.9268293\n4647   29.1463415\n4648 -621.1463415\n4649   -8.4146341\n4650 -379.0487805\n4651 -138.5121951\n4652   -1.0975610\n4653  -27.2926829\n4654  269.8780488\n4655 -419.8780488\n4656  523.0000000\n4657  675.7804878\n4658  571.0000000\n4659  413.8292683\n4660 -724.4146341\n4661  -30.7073171\n4662 -205.9756098\n4663  569.2439024\n4664  758.9024390\n4665    7.6829268\n4666 -114.4634146\n4667 -478.0731707\n4668  366.1707317\n4669  713.6829268\n4670   69.1463415\n4671   86.7073171\n4672   -7.1463415\n4673  596.3170732\n4674 -354.0731707\n4675 -555.6829268\n4676 -140.6097561\n4677  167.8292683\n4678  619.7804878\n4679 -705.6829268\n4680  684.7560976\n4681  546.6585366\n4682 -254.0731707\n4683  419.2926829\n4684  -85.7804878\n4685   60.5121951\n4686 -228.4634146\n4687  482.9512195\n4688  448.9024390\n4689 -588.6585366\n4690  377.5853659\n4691  403.6829268\n4692 -312.2195122\n4693 -266.4146341\n4694  133.6829268\n4695 -348.1219512\n4696   70.0243902\n4697  -72.3170732\n4698  534.0731707\n4699  733.8780488\n4700   24.8536585\n4701   26.5609756\n4702  673.3902439\n4703   15.6829268\n4704  560.2195122\n4705 -177.1951220\n4706 -148.5609756\n4707  654.4634146\n4708 -157.8780488\n4709  473.3414634\n4710 -451.7804878\n4711  305.5365854\n4712 -118.1707317\n4713 -515.7804878\n4714   21.9268293\n4715  602.6585366\n4716 -588.1707317\n4717   19.1463415\n4718 -208.0731707\n4719 -405.4390244\n4720 -180.0243902\n4721 -266.1707317\n4722  308.2195122\n4723   38.3170732\n4724 -562.9024390\n4725 -123.9756098\n4726  520.8048780\n4727 -553.3414634\n4728  548.4146341\n4729  836.2195122\n4730 -347.6341463\n4731  643.4878049\n4732 -674.6097561\n4733 -386.2195122\n4734  -69.5365854\n4735 -518.6585366\n4736   98.1219512\n4737   42.2682927\n4738  563.1463415\n4739  142.6097561\n4740  -37.7804878\n4741  -71.2926829\n4742 -676.4146341\n4743  696.6097561\n4744 -539.8292683\n4745  -99.7804878\n4746  181.0975610\n4747  -12.6585366\n4748   30.8048780\n4749 -177.3902439\n4750  590.8536585\n4751  715.3414634\n4752   36.8048780\n4753 -567.5853659\n4754 -686.6097561\n4755  750.1219512\n4756 -273.7317073\n4757  -73.3414634\n4758 -659.5365854\n4759  152.8048780\n4760  867.3902439\n4761  561.7317073\n4762  322.5121951\n4763 -158.5121951\n4764  197.2439024\n4765 -566.6585366\n4766  219.6829268\n4767  437.5365854\n4768 -224.8536585\n4769  -82.2195122\n4770  -48.5609756\n4771 -711.1463415\n4772  163.7317073\n4773  192.5121951\n4774    2.6585366\n4775 -125.9756098\n4776  -53.5365854\n4777 -347.8292683\n4778 -441.7804878\n4779  -46.0731707\n4780 -108.8536585\n4781  566.4146341\n4782 -237.7804878\n4783 -426.6097561\n4784  -60.4146341\n4785  619.6341463\n4786   52.4146341\n4787 -317.2439024\n4788 -644.4634146\n4789 -126.9024390\n4790 -527.1463415\n4791 -384.2195122\n4792   41.3414634\n4793  663.7317073\n4794  785.4390244\n4795   49.4390244\n4796  158.3170732\n4797  -36.3170732\n4798 -154.7560976\n4799 -506.0243902\n4800   14.1219512\n4801   10.7560976\n4802 -445.9268293\n4803  114.0731707\n4804  227.9268293\n4805  -29.7317073\n4806  -95.9756098\n4807  639.9756098\n4808  495.0487805\n4809  161.1463415\n4810  414.5609756\n4811  526.6097561\n4812 -485.2926829\n4813 -726.8048780\n4814  378.7073171\n4815 -177.0487805\n4816 -110.6585366\n4817 -619.6341463\n4818   66.0731707\n4819  -76.6097561\n4820  335.9268293\n4821  271.2926829\n4822  487.4390244\n4823  553.7317073\n4824 -142.0243902\n4825  495.3414634\n4826  118.4634146\n4827  792.8536585\n4828   94.7073171\n4829 -167.9268293\n4830    6.7560976\n4831 -121.4390244\n4832  129.0975610\n4833  104.8048780\n4834 -102.8048780\n4835 -280.9024390\n4836 -575.5853659\n4837 -374.4634146\n4838 -187.0975610\n4839 -542.0731707\n4840 -506.0731707\n4841  113.8780488\n4842 -624.4146341\n4843  211.8780488\n4844 -306.7073171\n4845  -18.1219512\n4846 -526.4146341\n4847 -737.2926829\n4848 -622.0243902\n4849 -167.0000000\n4850 -592.1707317\n4851 -129.3902439\n4852 -423.9268293\n4853   19.5365854\n4854 -511.7804878\n4855  538.8536585\n4856   81.5365854\n4857   50.0243902\n4858  614.3658537\n4859  515.4390244\n4860  598.3170732\n4861  144.0243902\n4862 -613.4878049\n4863 -144.0731707\n4864  427.9756098\n4865    8.4146341\n4866   -8.3658537\n4867  129.6829268\n4868  -75.6341463\n4869 -122.8536585\n4870 -429.3414634\n4871 -447.6341463\n4872  600.7560976\n4873  343.2439024\n4874 -123.2926829\n4875  109.0000000\n4876  -59.3414634\n4877  354.3170732\n4878  577.0000000\n4879 -761.1463415\n4880 -237.3414634\n4881  132.3658537\n4882 -529.2439024\n4883 -627.7317073\n4884   94.6097561\n4885   -1.8292683\n4886 -155.8780488\n4887  402.2682927\n4888  443.1463415\n4889  490.5121951\n4890 -375.6829268\n4891  -14.8048780\n4892   87.5853659\n4893 -467.2439024\n4894   45.0487805\n4895  715.7317073\n4896 -606.3170732\n4897  785.3902439\n4898  -54.6097561\n4899  535.9268293\n4900  -39.5365854\n4901  118.2682927\n4902  579.0487805\n4903  455.1951220\n4904  726.5121951\n4905 -366.4146341\n4906  742.6585366\n4907  -66.8048780\n4908  539.0000000\n4909 -507.9268293\n4910 -800.9512195\n4911  321.2926829\n4912 -800.7073171\n4913  -49.5853659\n4914   14.1707317\n4915  -31.1463415\n4916 -326.9512195\n4917  -18.4146341\n4918  483.6341463\n4919  382.9024390\n4920  -51.4878049\n4921 -120.2682927\n4922  240.5121951\n4923  201.1951220\n4924 -579.7317073\n4925 -526.4146341\n4926 -429.6829268\n4927 -644.6585366\n4928   47.1951220\n4929  297.0487805\n4930 -380.8536585\n4931 -273.5365854\n4932 -374.1219512\n4933  256.6097561\n4934  632.3170732\n4935  552.9024390\n4936 -373.6829268\n4937 -535.6829268\n4938   90.4634146\n4939  781.4390244\n4940   19.5365854\n4941  -63.5853659\n4942 -401.7804878\n4943 -472.8048780\n4944  -79.2439024\n4945  -48.8048780\n4946 -472.9024390\n4947   19.2439024\n4948 -671.5365854\n4949  -61.5853659\n4950 -344.9512195\n4951   76.6097561\n4952   26.6585366\n4953   32.2195122\n4954  647.1951220\n4955  212.0731707\n4956   66.3658537\n4957 -514.3658537\n4958  -34.2195122\n4959 -187.8780488\n4960 -293.9756098\n4961  627.5365854\n4962 -639.5365854\n4963  587.0000000\n4964   31.7317073\n4965    3.5853659\n4966  728.6097561\n4967   29.0000000\n4968  474.0731707\n4969  -88.2195122\n4970   -0.1707317\n4971  -62.4146341\n4972  532.5609756\n4973  748.6097561\n4974 -102.9024390\n4975  415.9268293\n4976  -52.8536585\n4977  725.6341463\n4978  -69.4878049\n4979 -701.2926829\n4980 -108.8536585\n4981 -236.9512195\n4982  -90.8536585\n4983 -295.5365854\n4984 -693.0000000\n4985  -81.7804878\n4986 -520.2195122\n4987 -345.7317073\n4988 -758.5609756\n4989 -421.8292683\n4990 -420.3658537\n4991 -371.5365854\n4992  630.9024390\n4993 -466.9024390\n4994 -374.5609756\n4995 -556.6097561\n4996 -264.0243902\n4997 -678.7073171\n4998 -256.6097561\n4999   18.3658537\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_diff_moneyspent <- diffmean(Money_spent ~ Gender, data = pmoney_modified) \nobs_diff_moneyspent\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n diffmean \n-55.29268 \n```\n\n\n:::\n:::\n\n\n\n\n-   Difference between the mean of money spent in females and males is 55.29\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(data = null_dist_moneyspent, ~ diffmean, bins = 25) %>%\n  gf_vline(xintercept = obs_diff_moneyspent, \n           colour = \"red\", linewidth = 1,\n           title = \"Null Distribution by Permutation\", \n           subtitle = \"Histogram\") %>% \n  gf_labs(x = \"Difference in Means\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n\n```{.r .cell-code}\n###\ngf_ecdf(data = null_dist_moneyspent, ~ diffmean, \n        linewidth = 1) %>%\n  gf_vline(xintercept = obs_diff_moneyspent, \n           colour = \"red\", linewidth = 1,\n           title = \"Null Distribution by Permutation\", \n           subtitle = \"Cumulative Density\") %>% \n  gf_labs(x = \"Difference in Means\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-2.png){width=672}\n:::\n:::\n\n\n\n\n### Inference\n\n-   The red line in the graph represents the observed difference in means of the two categories (i.e, -55.29)\n\n-   the histogram represents the null distribution from the permutation tests\n\n-   Since the red line falls within the central range of the null distribution, we can assume that the difference was due to random chance\n\n-   This tells us that the difference between money spent by male and female is not statistically significant\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1-prop1(~ diffmean <= obs_diff_moneyspent, data = null_dist_moneyspent)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nprop_TRUE \n   0.5552 \n```\n\n\n:::\n:::\n\n\n\n\n-   There is a 56.4% chance that a difference in means equal to or greater than obs_diff_moneyspent could occur under the null hypothesis.\n\n-   since the p-value is higher than 0.05, the observed difference is statistically insignificant, and we cannot reject the null hypothesis\n\n## Conclusion\n\nFrom our data we can say males on average spend more than women though it is not a significant amount\n\nThere is no significant difference between the spending habits of males and females\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}