---
title: "Summaries"
---

## Introduction

We are working with Data summaries. First 'mpg'

```{r}
#|label: setup
library(tidyverse)
library(ggformula)
library(mosaic)
library(skimr)
library(kableExtra)
library(babynames)
```

```         
```

```         
```

## Look at the mpg dataset

```{r}
mpg
```

```{r}
mpg %>% 
  head(10)
```

```{r}
glimpse(mpg)
```

```{r}
inspect(mpg)
```

```{r}
skimr::skim(mpg)
```

```         
```

```{r}
skimr::skim(mpg)

```

```{r}
mpg_modified <- mpg %>% 
  dplyr::mutate(cyl = as_factor(cyl),
                fl = as_factor(fl),
                drv = as_factor(drv),
                class = as_factor(class),
                trans = as_factor(trans))
glimpse(mpg_modified)
```

Always close the previous qmd file to avoid cross-contamination of packages.

```{r}
mpg_modified %>% 
  group_by(cyl) %>% 
  summarize(average_hmy =mean(hwy),count =n())
```

```{r}
mpg %>% group_by(manufacturer) %>% summarize(mean_mileage_manf = mean(hwy))
```

```{r}
mpg %>% group_by(manufacturer) %>% summarize(mean_mileage_manf = mean(cty))
```

## Analysing Math Anxiety Data

```{r}
math_anxiety <-read_delim(file = "../../data/MathAnxiety.csv",delim=";")
math_anxiety
```

```{r}
inspect(math_anxiety)
```

```{r}
math_anxiety_modified <- math_anxiety %>% 
  dplyr::mutate(Age=as.integer(Age/120), 
    Gender = as_factor(Gender),
    Grade = as_factor(Grade))
math_anxiety_modified
```

```{r}
skimr::skim(math_anxiety)
```

```{r}
inspect(math_anxiety_modified)
```

```{r}
math_anxiety_modified %>% group_by(Gender) %>% summarize(mean_AMAS = mean(AMAS),mean(RCMAS), count=n())
```
